### ISSUE TITLE
[Richiesta Canale] Canali Discovery

### ISSUE THREAD

**Issue by btv1111** [Tundrak/IPTV-Italia#1]
**Tutti i canali Discovery mancanti:**
- Nove
- Real Time
- Giallo
- Food Network
- DMAX
- Motor Trend
- Home and Garden TV
- K2
- Frisbee
---
Testo originale:
ciao puoi aggiungere l'm3u8 a k2? quando provo a estrapolare io i link da dplay sono criptati

**Comment by Tundrak** [comment]
Ciao
Purtroppo quando il sito di Dplay è cambiato in Discovery+ è stata aggiunta una crittografia con DRM ai vari stream, per cui mi è impossibile estrarre un link "pulito". Questo problema è lo stesso che mi rende impossibile di aggiungere anche altri canali come La7 e La7d.
Tuttavia dovrei aggiungere altri canali di cartoni animati in un grande aggiornamento che spero di riuscire a pubblicare entro fine settimana.
Mantengo aperta l'issue nel caso la situazione cambi in futuro

**Comment by evodash** [comment]
ah ok, comunque ho trovato i link di boing e super che sono https://live3-radio-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(kb)/index.m3u8 per boing e https://viacomitalytest-lh.akamaihd.net/i/sbshdlive_1@357018/master.m3u8 per super

**Comment by Tundrak** [comment]
Aggiunti proprio ieri alla prova della nuova lista, insieme a Cartoonito: https://live3.msf.cdn.mediaset.net/Content/dash_d0_clr_vos/live/channel(la)/manifest.mpd

**Comment by Tundrak** [comment]
Pubblicato l'aggiornamento proprio adesso, v04-2021:
https://github.com/Tundrak/IPTV-Italia/releases/tag/v04-2021

**Comment by Trifone46** [comment]
Buon giorno ho trovato dei link per NOVE Real-time Giallo e Dmax non ufficiali ma non sono sempre stabili perche succede che saltano ho si bloccano dopo un po e possibile stabilizzarli in qualche modo
Nove http://45.153.35.200:8001/play/a06c
Giallo http://45.153.35.200:8001/play/a06b 
Real-time http://45.153.35.200:8001/play/a0a9 Dmax http://45.153.35.200:8001/play/a0aa

**Comment by Trifone46** [comment]
Specifico che questi link funzionano con il lettore iptv pro creando un file txt per poi inserire il file nel lettore iptv pro .

**Comment by Trifone46** [comment]
Ho trovato ulteriori 2 link non ufficiali Tv8 e Cielo entrambi sono in HD ma anno i stessi problemi che ho descritto con i canali NOVE Real-time ecc
Cielo HD http://45.153.35.200:8001/play/a068
Tv8 HD http://45.153.35.200:8001/play/a069

**Comment by Trifone46** [comment]
Ho trovato ulteriori 2 link non ufficiali Tv8 e Cielo entrambi sono in HD ma anno i stessi problemi che ho descritto con i canali NOVE Real-time ecc
E possibile stabilizzarli in qualche modo
Cielo HD http://45.153.35.200:8001/play/a068
Tv8 HD http://45.153.35.200:8001/play/a069

**Comment by Trifone46** [comment]
Specifico che tutti i link che vi ho segnalato funzionano con il lettore iptv pro creando un file txt per poi inserire il file nel lettore iptv pro .

**Comment by Trifone46** [comment]
Qualcuno riesce a trovare il link per il nuovo canale di discoyer Warner TV

**Comment by Trifone46** [comment]
Buon giorno ci siete ?

**Comment by Trifone46** [comment]
Ci siete ? Essistete ? Perché ho notato che nessuno mi risponde .

**Comment by Tundrak** [comment]
Ciao e scusa per il ritardo nella risposta, non controllo tutti i giorni per vedere se ci sono nuovi commenti.
Grazie per aver trovato questi link, ma purtroppo non li aggiungerò alla lista in quanto non sono ufficiali. Se qualcuno li vuole usare, li può aggiungere manualmente (anche se so che è più brigoso)
Per quanto riguarda i problemi di stabilità, io non ne ho osservati su Iptv pro (la versione gratuita, probabilmente simile alla tua) ed altri lettori, forse la tua connessione a Internet non è veloce a sufficienza? Puoi provare a migliorare la situazione aumentando il periodo di buffering da Impostazioni > Preferenze del riproduttore video > Imposta dimensione del buffer di rete e inserire un valore grande tipo 10000 (però non so se possa aiutare perchè non posso riprodurre il tuo problema)

**Comment by Trifone46** [comment]
Buon giorno vi segnalato questi link a differenza di quelli che vi ho segnalato in precedenza questi funzionari solo se si apre un qualsiasi browser non so se saranno utilizzabili in futuro per una lista . la ringrazio per avermi risposto in precedenza 
DIRETTA DMAX
https://ok.ru/videoembed/4270313250416?nochat=1&autoplay-1

DIRETTA NOVE
https://ok.ru/videoembed/4158335557232?nochat=1&autoplay-1

DIRETTA REAL-TIME
https://ok.ru/videoembed/4154672881264?nochat=1&autoplay-1

DIRETTA GIALLO
https://ok.ru/videoembed/4144906903152?nochat=1&autoplay-1

**Comment by Trifone46** [comment]
Buon giorno segnalo un indirizzo iptv
http://inthemix.altervista.org/tv.m3u
dove ci sono molti canali inclusi Pluto Tv & Rakuten Tv

**Comment by Trifone46** [comment]
Buon giorno vi segnalo questi link che a differenza di quelli che vi ho segnalato in precedenza questi funzionano solo usando un qualsiasi browser . Non so se in futuro sia possibile usarli in qualche modo tramite una lista 
La ringrazio per la risposta che mi a dato in precedenza .

DIRETTA DMAX
https://ok.ru/videoembed/4270313250416?nochat=1&autoplay-1

DIRETTA NOVE
https://ok.ru/videoembed/4158335557232?nochat=1&autoplay-1

DIRETTA REAL-TIME
https://ok.ru/videoembed/4154672881264?nochat=1&autoplay-1

DIRETTA GIALLO
https://ok.ru/videoembed/4144906903152?nochat=1&autoplay-1

**Comment by Trifone46** [comment]
Buon giorno segnalo un indirizzo iptv
http://inthemix.altervista.org/tv.m3u
dove ci sono molti canali inclusi Pluto Tv & Rakuten Tv

**Comment by Trifone46** [comment]
Buon giorno vi segnalo questi link che a differenza di quelli che vi ho segnalato in precedenza questi funzionano solo usando un qualsiasi browser . Non so se in futuro sia possibile usarli in qualche modo tramite il lettore iptv pro creando una lista
La ringrazio per la risposta che mi a dato in precedenza .

DIRETTA DMAX
https://ok.ru/videoembed/4270313250416?nochat=1&autoplay-1

DIRETTA NOVE
https://ok.ru/videoembed/4158335557232?nochat=1&autoplay-1

DIRETTA REAL-TIME
https://ok.ru/videoembed/4154672881264?nochat=1&autoplay-1

DIRETTA GIALLO
https://ok.ru/videoembed/4144906903152?nochat=1&autoplay-1

**Comment by Trifone46** [comment]
Buon giorno segnalo un indirizzo iptv
http://inthemix.altervista.org/tv.m3u
dove ci sono molti canali inclusi Pluto Tv & Rakuten Tv

**Comment by Trifone46** [comment]
Buon giorno segnalo un indirizzo iptv
http://inthemix.altervista.org/tv.m3u
dove ci sono molti canali inclusi
Pluto Tv 
Rakuten Tv
Samsung Tv .

**Comment by Trifone46** [comment]
Buon giorno segnalo un indirizzo iptv
http://inthemix.altervista.org/tv.m3u
dove ci sono molti canali inclusi
Pluto Tv
Rakuten Tv
Samsung Tv

**Comment by Trifone46** [comment]
Buon giorno vi segnalo questi link che a differenza di quelli che vi ho
segnalato in precedenza questi funzionano solo usando un qualsiasi browser
. Non so se in futuro sia possibile usarli in qualche modo tramite il
lettore iptv pro creando una lista
La ringrazio per la risposta che mi a dato in precedenza inoltre le segnalo
un indirizzo iptv
http://inthemix.altervista.org/tv.m3u
dove ci sono molti canali inclusi
Pluto Tv
Rakuten Tv
Samsung Tv

DIRETTA DMAX
https://ok.ru/videoembed/4270313250416?nochat=1&autoplay-1

DIRETTA NOVE
https://ok.ru/videoembed/4158335557232?nochat=1&autoplay-1

DIRETTA REAL-TIME
https://ok.ru/videoembed/4154672881264?nochat=1&autoplay-1

DIRETTA GIALLO
https://ok.ru/videoembed/4144906903152?nochat=1&autoplay-1

Il giorno venerdì 4 novembre 2022, Tundrak ***@***.***> ha
scritto:

**Comment by Trifone46** [comment]
Quando ci sara un nuovo aggiornamento sulla lista dato che da luglio non viene aggiornata e quindi e passato del tempo ?

**Comment by comleoita** [comment]
Ciao ci sono aggiornamenti?

**Comment by Tundrak** [comment]
Purtroppo niente, mi dispiace :(
Anche dal sito di Discovery+ si possono ottenere link, ma quelli sono protetti sia con Widevine (tanto per cambiare). Da quello che mi sembra di capire la maggior parte dei player non supporta la decrittazione di stream cifrati o almeno non facilmente, per cui mi sa che dovremo continuare ad aspettare.

**Comment by comleoita** [comment]
Vabbè niente, peggio per loro non guarderò più i canali discovery…

**Comment by Trifone46** [comment]
Buon giorno ho trovato dei  canali in HD per quanto riguarda i canali discovery che sono 
i seguenti
Nove
http://51.179.188.106:4000/play/a012/index.m3u8
Giallo
http://51.179.188.106:4000/play/a011/index.m3u8
Real-time
http://51.179.188.106:4000/play/a00t/index.m3u8
Dmax
http://51.179.188.106:4000/play/a00u/index.m3u8

**Comment by Trifone46** [comment]
Buon giorno ho trovato dei canali in HD per quanto riguarda i canali discovery che sono
i seguenti
Nove
http://51.179.188.106:4000/play/a012/index.m3u8
Giallo
http://51.179.188.106:4000/play/a011/index.m3u8
Real-time
http://51.179.188.106:4000/play/a00t/index.m3u8
Dmax
http://51.179.188.106:4000/play/a00u/index.m3u8
Funzionano con iptv pro ho va bene anche quello non pro basta aprirli con il lettore che vi ho indicato .

**Comment by comleoita** [comment]
Funzionano molto bene purtroppo non sono ufficiali

**Comment by Trifone46** [comment]
Buon giorno ho trovato ulteriori canali per quanto riguarda discovery sono i seguenti
WanerTv HD http://51.179.188.106:4000/play/a00y/index.m3u8
Motor Trend HD
http://51.179.188.106:4000/play/a010/index.m3u8
Hgtv HD
http://51.179.188.106:4000/play/a013/index.m3u8
Food Network
http://51.179.188.106:4000/play/a00v/index.m3u8

**Comment by Trifone46** [comment]
Buon giorno ho trovato ulteriori canali per quanto riguarda discovery sono i seguenti
WanerTv HD http://51.179.188.106:4000/play/a00y/index.m3u8
Motor Trend HD
http://51.179.188.106:4000/play/a010/index.m3u8
Hgtv HD
http://51.179.188.106:4000/play/a013/index.m3u8
Food Network HD
http://51.179.188.106:4000/play/a00v/index.m3u8

**Comment by Trifone46** [comment]
Buon giorno ho trovato ulteriori canali per quanto riguarda discovery sono i seguenti
WanerTv HD http://51.179.188.106:4000/play/a00y/index.m3u8
Motor Trend HD
http://51.179.188.106:4000/play/a010/index.m3u8
Hgtv HD
http://51.179.188.106:4000/play/a013/index.m3u8
Food Network
http://51.179.188.106:4000/play/a00v/index.m3u8
Funzionano con iptv pro ho va bene anche quello non pro basta aprirli con il lettore che vi ho indicato .

**Comment by alespita82** [comment]
ciao trifone grazie tanto per i link funzionano tutti. volevo chiederti se è possible su quale sito li hai trovati

**Comment by Trifone46** [comment]
Buona sera ho trovato questi link per i canali discovery ma funzionano solo aprendo un qualsiasi browser se qualcuno riesce a farli funzionare con iptv pro puo segnalarlo qui

Nove
https://ok.ru/video/4158335557232

Real-time
https://ok.ru/video/4154672881264

Dmax
https://ok.ru/video/4270313250416

Giallo
https://ok.ru/video/4144906903152

**Comment by Trifone46** [comment]
Buon pomeriggio per chi cerca canali discovery ho trovato un app  gratuita senza pubblicita include ulteriori canali Mediaset Rai Ecc ma se volete il link ve lo posso passare ma non qui .

**Comment by Trifone46** [comment]
Buon giorno ho trovato un link iptv  nuovo con tantissimi canali di ogni genere ci sono tante regioni e tanto altro anche canali discovery ma non posso postarlo qui .

**Comment by FrancescoRosi** [comment]
**LI HO TROVATI!**
Grazie a Samsung TV Plus, abbiamo dei link puliti, in chiaro e in alta definizione di quasi tutti i canali WBD (manca solo Warner TV).

#168

**Comment by Tundrak** [comment]
Sembra incredibile, e invece sono proprio qua
Tutti i canali Discovery sono ora disponibili nella nuova [Release Gennaio 2024](https://github.com/Tundrak/IPTV-Italia/releases/tag/v01-2024)!
