### ISSUE TITLE
[Problema]

### ISSUE THREAD

**Issue by Damians0** [Tundrak/IPTV-Italia#10]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)
Tutti i canali rai

**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.
I canali Rai non funzionano non si aprono.

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: Smartphone
 - Programma utilizzato IPTV extreme pro
 - Versione lista: lista autoaggiornante (link)

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by Tundrak** [comment]
Quest'Issue è praticamente un duplicato di #5, ha a che fare con l'User Agent dell'app.
Per risolverla, devi impostare la playlist aggiungendola con questo User Agent: Mozilla/5.0 (guarda la foto).
![1](https://user-images.githubusercontent.com/77153792/122111810-76107f00-ce20-11eb-9926-072614360b46.png)
Poi, devi andare in Impostazioni > Video Player > Player Interno e impostarlo su FFPlay (o davvero uno qualsiasi tranne Advanced, FFPlay mi è sembrato quello che funzionava meglio).
![2](https://user-images.githubusercontent.com/77153792/122111848-7f015080-ce20-11eb-8d43-53b7ce01e2f9.png)
Purtroppo però facendo così perderesti i canali Mediaset, perchè sono in formato .mpd 🤦‍♂️, dunque dovresti usare la scorsa versione della lista con [questo](https://raw.githubusercontent.com/Tundrak/IPTV-Italia/main/iptvita-History/iptvita(v05-2021).m3u) link per vedere tutto in una volta, oppure se vuoi continuare a usare quella autoaggiornante dovresti specificare per ogni canale con quale player lo vuoi riprodurre tenendo premuto sul suo nome (Advanced per quelli Mediaset, un altro per tutti gli altri).
Dimmi se con questi cambiamenti la lista funziona, vedrò di fare qualcosa per i canali Mediaset in un prossimo aggiornamento.

**Comment by Tundrak** [comment]
@Damians0 , sei riuscito a risolvere il problema?
Non avendo più ricevuto tua risposta, tra qualche giorno chiuderò l'Issue come risolta.

**Comment by Damians0** [comment]
Ciao grazie A dire il vero non ho più provato

Il mar 29 giu 2021, 5:47 PM Tundrak ***@***.***> ha scritto:

**Comment by Tundrak** [comment]
Oh.
Allora per il momento chiudo l'Issue, se per caso provi e hai ancora problemi puoi scrivere anche se è chiusa

**Comment by Damians0** [comment]
Grazie mille 👍

Il mer 30 giu 2021, 9:29 PM Tundrak ***@***.***> ha scritto:
