### ISSUE TITLE
Bella Radio TV

### ISSUE THREAD

**Issue by Trifone46** [Tundrak/IPTV-Italia#101]
Bella Radio TV

Vi chiedo per favore ve ne prego mi fareste un grandissimo regalo appena sara possibile potete inserire questo canale della Sicilia con qualche altro canale regionale in una lista futura nei mesi a venire .

https://server.bellaradio.it:1443/live/bellaradiotv/playlist.m3u8

**Comment by Trifone46** [comment]
> Bella Radio TV
> 
> Ve lo chiedo per favore ve ne prego mi fareste un grandissimo regalo appena sara possibile potete inserire questo canale della Sicilia con qualche altro canale regionale in una lista futura nei mesi a venire .
> 
> https://server.bellaradio.it:1443/live/bellaradiotv/playlist.m3u8

**Comment by Trifone46** [comment]
Ci siete ?

**Comment by Tundrak** [comment]
Come ho detto in #100, il canale è già in un'altra lista insieme a tanti altri: è [quella regionale](https://github.com/Tundrak/IPTV-Italia/releases/tag/regionale-pre9).
Per favore, non aprire nuove Issue su argomenti già discussi. Se vuoi dire qualcosa fallo su una di quelle che hai già creato.
