### ISSUE TITLE
[Richiesta Canale]

### ISSUE THREAD

**Issue by dariobike** [Tundrak/IPTV-Italia#102]
**Canale Richiesto**
Radio Marte TV 
Napoli regione Campania 
molto seguita in tutto il sud Italia e dai concittadini all'estero 
**URL Streaming**
https://www.radiomarte.it/marte/radio-marte-tv/

**Comment by Tundrak** [comment]
Ciao
Questo canale è già nella [lista regionale](https://github.com/Tundrak/IPTV-Italia/releases/tag/regionale-pre9) della Campania all'LCN 655 (potrebbe non essere quello di adesso, ma evidentemente era così quando l'ho creata nel lontano 2021 e il link funziona ancora incredibilmente tra una marea che non vanno più).
Non so quando aggiornerò nuovamente le liste regionali perchè sono un impegno davvero grande, ma nel frattempo è lì e il link funziona
