### ISSUE TITLE
Da VLC riesco ad aprire i link M3U8 ma non quelli (ad esempio RAI) tipo questo: http://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=16     come devo fare?

### ISSUE THREAD

**Issue by VirtualExperience** [Tundrak/IPTV-Italia#104]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)

**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]
 - Programma utilizzato [es. VLC, Potplayer]
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by Tundrak** [comment]
Parli della lista o intendi i link da soli? Nella lista funzionano grazie alle linee #EXTVLCOPT:http-user-agent=Mozilla/5.0 che permettono di impostare l'User Agent giusto, se stai usando link sciolti non credo possano funizonare. L'unico modo è inserirli in un file m3u con l'User Agent
In ogni modo sconsiglio vivamente VLC per guardare la lista, è fonte di metà delle Issue qui

**Comment by VirtualExperience** [comment]
Ho l'esigenza contraria... utilizzare dei link per visualizzare dei flussi streaming su un'app.

   Con i file M3U8 nessun problema, ma quando ho elementi tipo:

   http://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=16

   non so come fare a farlo funzionare

   Puoi darmi una mano?

   Grazie

   Da "Tundrak" ***@***.***
   A "Tundrak/IPTV-Italia" ***@***.***
   Cc "VirtualExperience" ***@***.***,"Author" ***@***.***
   Data Mon, 27 Mar 2023 12:27:17 -0700
   Oggetto Re: [Tundrak/IPTV-Italia] Da VLC riesco ad aprire i link M3U8 ma non quelli (ad esempio RAI) tipo questo: http://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=16 come devo fare? (Issue #104)

   Parli della lista o intendi i link da soli? Nella lista funzionano grazie alle linee #EXTVLCOPT:http-user-agent=Mozilla/5.0 che permettono di impostare l'User Agent giusto, se stai usando link sciolti non credo possano funizonare. L'unico modo è inserirli in un file m3u con l'User Agent
   In ogni modo sconsiglio vivamente VLC per guardare la lista, è fonte di metà delle Issue qui

**Comment by Tundrak** [comment]
Scusa, ma non sono sicuro di capire
Devi usare VLC o un'altra app?
Ti serve di aprire link singolarmente (tipo incollandoli nel player)?
Più informazioni mi dai, più riesco ad aiuarti (spero)

**Comment by VirtualExperience** [comment]
Ciao,

   abbiamo sviluppato un app che permette di visualizzare i canali italiani (quelli in chiaro)

   La maggior parte dei canali si vedono senza problemi, alcuni (es. RAI 1 - RAI 2, ecc.) funzionano saltuariamente e mi costringono ad aggiornare il link M3U8 che cambia in continuazione

   L'app e' la seguente:

   https://play.google.com/store/apps/details?id=it.italiaonlinetv.italiaonlineandroidtv

   che funziona sia per smartphone che per smart tv (entrambe android)

   Nel mio backend, quando aggiungo un canale, devo specificare l'M3U8

   Li trovo da liste in rete, oppure tramite l'estensione Chrome "Video M3U8 Sniffer"

   Credo di averti detto tutto.

   Ti ringrazio per il supporto!

   Alessandro

   Da "Tundrak" ***@***.***
   A "Tundrak/IPTV-Italia" ***@***.***
   Cc "VirtualExperience" ***@***.***,"Author" ***@***.***
   Data Wed, 29 Mar 2023 07:32:32 -0700
   Oggetto Re: [Tundrak/IPTV-Italia] Da VLC riesco ad aprire i link M3U8 ma non quelli (ad esempio RAI) tipo questo: http://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=16 come devo fare? (Issue #104)

   Scusa, ma non sono sicuro di capire
   Devi usare VLC o un'altra app?
   Ti serve di aprire link singolarmente (tipo incollandoli nel player)?
   Più informazioni mi dai, più riesco ad aiuarti (spero)

**Comment by Tundrak** [comment]
Ora capisco, che bel progetto!
Purtroppo negli anni in cui ho mantenuto questa lista non ho mai visto da nessuna parte link .m3u8 ai canali Rai (tranne Rai 4K), ma se il vostro sistema accetta playlist .mpd, ci sono link permanenti di quel tipo (prova a guardare [questo commento](https://github.com/Tundrak/IPTV-Italia/issues/87#issuecomment-1364647716) di un'altra Issue).
Io non li uso nella mia lista (nonostante siano in 1080p al contrario di quelli correnti in 720p) perchè generano caos ancora maggiore di quelli di adesso su VLC, ma forse per voi vanno bene

**Comment by VirtualExperience** [comment]
Ti ringrazio per la risposta, provero' a fare qualche altro tentativo

   Se ti viene qualche idea, sarebbe preziosa.

   Buona giornata

   Da "Tundrak" ***@***.***
   A "Tundrak/IPTV-Italia" ***@***.***
   Cc "VirtualExperience" ***@***.***,"Author" ***@***.***
   Data Wed, 29 Mar 2023 12:05:24 -0700
   Oggetto Re: [Tundrak/IPTV-Italia] Da VLC riesco ad aprire i link M3U8 ma non quelli (ad esempio RAI) tipo questo: http://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=16 come devo fare? (Issue #104)

   Ora capisco, che bel progetto!
   Purtroppo negli anni in cui ho mantenuto questa lista non ho mai visto da nessuna parte link .m3u8 ai canali Rai (tranne Rai 4K), ma se il vostro sistema accetta playlist .mpd, ci sono link permanenti di quel tipo (prova a guardare questo commento di un'altra Issue).
   Io non li uso nella mia lista (nonostante siano in 1080p al contrario di quelli correnti in 720p) perchè generano caos ancora maggiore di quelli di adesso su VLC, ma forse per voi vanno bene

**Comment by Tundrak** [comment]
Se troverò link m3u8 per i canali Rai, di sicuro li aggiungerò alla lista. Quindi continua a controllare ogni tanto
In bocca al lupo per lo sviluppo della vostra app!
