### ISSUE TITLE
[Problema]

### ISSUE THREAD

**Issue by artizan777** [Tundrak/IPTV-Italia#106]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)

**Descrivi il problema**
tutti canali RAI non funczionati!  Descrivi brevemente e in modo conciso qual è il problema.

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]
 - Programma utilizzato [es. VLC, Potplayer]
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by artizan777** [comment]
tutti i canali RAI sono un paradiso non funziona!!

**Comment by Tundrak** [comment]
Ho controllato adesso e i link funzionano, forse il player che usi non è in grado di riprodurli.
Puoi darmi qualche informazione in più sul tuo player/dispositivo?

**Comment by Tundrak** [comment]
Visto che non ho più tue notizie, chiudo l'Issue.
Se stai ancora avendo problemi, puoi riaprirla e scrivere un nuovo commento con più informazioni
