### ISSUE TITLE
Rai 4k non si vede più

### ISSUE THREAD

**Issue by hackaros** [Tundrak/IPTV-Italia#108]
RAI4K
Il canale risiede nelle due liste di canali iptv.
Fino a qualche giorno fa il canale si vedeva. Da ieri non si vede più.

I link rai sono visibili direttamente aprendoli, su android, da un browser qualsiasi.

Dispositivi android samsung, huawei, motorola.

**Comment by Trifone46** [comment]
Buon pomeriggio questo e il nuovo link di Rai 4k ma non tanto stabile l immagine
https://raievent10-elem-live.akamaized.net/hls/live/619189/raievent10/raievent10/playlist.m3u8

**Comment by Tundrak** [comment]
Ciao.
Ho controllato e il link di Rai 4K sembra ancora funzionare perfettamente, nella lista c'è proprio lo stesso postato da @Trifone46
Forse puoi fornire qualche informazione in più?

**Comment by Trifone46** [comment]
Buona Sera Segnalato Questo Link Dove Troverete Svariati Canali https://tivustream.website/urls/listm3u

**Comment by Trifone46** [comment]
Buona Sera Segnalato Questo Link Dove Troverete Svariati Canali https://tivustream.website/urls/listm3u
Dovete inserirlo Nel l app usando l app IPTV ho IPTV PRO

**Comment by Trifone46** [comment]
Buona Sera Segnalato Questo Link Dove Troverete Svariati Canali https://tivustream.website/urls/listm3u
Dovete inserirlo Nel l app usando Iptv HO IPTV PRO .

**Comment by Tundrak** [comment]
Visto che non ho più ricevuto risposta e Rai 4K si vede tranquillamente, chiudo l'Issue.
@Trifone46 Se vuoi utilizzare quella lista fallo pure, ma sarei contento se non la pubblicizzassi qui. Capisco che sia più ricca, ma non è necessariamente una buona cosa (mi sembra molto confusionaria a momenti)
