### ISSUE TITLE
Tv regionali suddivisione in cartelle

### ISSUE THREAD

**Issue by MarkPorty** [Tundrak/IPTV-Italia#11]
Buongiorno e grazie sempre per il tuo lavoro.
Un suggerimento:

Le tv regionali perché non le dividi in sottocartelle per ogni regione(oppure crei un link, o file singoli, per ogni regione)?

In questo modo ognuno può seguire la/le regioni di interesse.

Grazie

**Comment by Tundrak** [comment]
Effettivamente non ci avevo mai davvero pensato, e ha senso.
Già fatto con l'ultimo aggiornamento [Test Regionale 6](https://github.com/Tundrak/IPTV-Italia/releases/tag/regionale-pre6)!

**Comment by MarkPorty** [comment]
Grazie!!
Se un domani riesci anche a fare un link diretto (come per la TV italiana e la radio) faresti una cosa davvero completa.

Marco

**Comment by Tundrak** [comment]
I link diretti sono sempre disponibili, ma li scriverò chiaramente nel readme soltanto quando la lista sarà completa e uscirà dalla fase pre-release.
Nel frattempo puoi comunque ottenerli tutti dalla struttura https://github.com/Tundrak/IPTV-Italia/raw/main/iptvregionale-History/iptvregionale-preX/iptvregione-preX.m3u sostituendo le due *X* con il numero di una pre-release (in questo caso 6) e *regione* con il nome della regione che ti interessa.
Per esempio, se vuoi la lista del Lazio della 6a pre-release usa https://github.com/Tundrak/IPTV-Italia/raw/main/iptvregionale-History/iptvregionale-pre6/iptvlazio-pre6.m3u
