### ISSUE TITLE
[Richiesta Canale] Sky TG24

### ISSUE THREAD

**Issue by Shuggy999** [Tundrak/IPTV-Italia#112]
questo URL proviene da ticktock e potrebbe cambiare

https://pull-f5-va01.tiktokcdn.com/game/stream-2995384338401198168_hd.flv

**Comment by Tundrak** [comment]
Ciao.
Grazie per il link, ma purtroppo non posso accettarlo in quanto come hai detto tu potrebbe cambiare. Inoltre non è ufficiale, e tra l'altro ho già un link funzionante nella lista.

**Comment by Shuggy999** [comment]
scusa, errore mio. Anche il tuo URL non scadrà tra 6 mesi? l'epoca nell'url è 1702463400 e quindi anche lo stream scadrà.

**Comment by Shuggy999** [comment]
ma l'url è ufficiale no? da qui https://www.tiktok.com/@skytg24/live

**Comment by Tundrak** [comment]
Oh, è vero. Non ho Tiktok e non avevo immaginato che fosse in streaming anche lì.
Nonostante anche il mio link scada preferisco mantenere quello in quanto è già nella lista, e il tuo non porta nessun beneficio specifico in più. Tuttavia lo considererò sicuramente se quando quello corrente scade non ce ne sarà uno nuovo utilizzabile sul sito.
