### ISSUE TITLE
[Richiesta Canale]

### ISSUE THREAD

**Issue by dxvvide** [Tundrak/IPTV-Italia#12]
TV8
#EXTINF:-1 tvg-id="" tvg-name="TV8" tvg-country="" tvg-language="" tvg-logo="https://upload.wikimedia.org/wikipedia/it/thumb/6/6d/TV8_Logo_2016.svg/1200px-TV8_Logo_2016.svg.png" group-title="",TV8
https://www.mytivu.it/Application/Channels/TV8.php

**Comment by Tundrak** [comment]
Mi dispiace, ma il link non è di un sito ufficiale di Sky (anzi lo estrae in modo forzato), quindi preferisco non aggiungerlo per evitare grane future.
Vedi anche #9 in cui è successa una cosa simile
Dovesse diventare disponibile un link ufficiale per TV8, appena lo noterò verrà aggiunto subito :)
