### ISSUE TITLE
[Problema]

### ISSUE THREAD

**Issue by Lusien58** [Tundrak/IPTV-Italia#124]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)

**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]
 - Programma utilizzato [es. VLC, Potplayer]
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

Buongiorno,
Spero di trovarmi nel posto giusto, a causa del maltempo che mi ha distrutto l'antenna tv, sto usando iptv per vedere la tv da ieri mi sono accorto che raitv 1 non si riceve più,
tutti gli altri funzionano, sto usando ss iptv su smart tv lg, 
sto usando la versione 06-2023.
ringraziandovi anticipatamente, spero in una risoluzione del problema.

**Comment by Tundrak** [comment]
Ciao, sei nel posto giusto!
Purtroppo l'app che stai usando (come tante altre) ha problemi con la riproduzione dei canali Rai, puoi seguire la discussione qui: #120
Questa issue verrà chiusa per tenere tutti i commenti consolidati là.
