### ISSUE TITLE
Canali non funzionanti

### ISSUE THREAD

**Issue by Seby1986** [Tundrak/IPTV-Italia#127]
Buongiorno,ho provato le varie liste e i canali RAI e mediaset non partono,ho provato su smartphone android con varie app tra cui vlc e il problema è sempre lo stesso,sbaglio io?

**Comment by Tundrak** [comment]
Ciao!
Purtroppo lo stato del supporto delle opzioni nelle app IPTV per il telefono è terribile (e VLC non è meglio delle altre), mi dispiace :(
Probabilmente sei stato semplicemente sfortunato nel trovare quelle sbagliate
Sono sicuro che un'app che funziona si chiama [Televizo](https://play.google.com/store/apps/details?id=com.ottplay.ottplay) (penso senza cambiare nessuna impostazione predefinita), ma se cerchi abbastanza di sicuro ne trovi anche delle altre
Dimmi se ha funzionato

**Comment by Seby1986** [comment]
Buonasera,con l'app televizo la lista funziona tranquillamente, volevo
sapere se è possibile aggiungere dei canali tipo realtime. Grazie

Il Mar 10 Ott 2023, 19:26 Tundrak ***@***.***> ha scritto:

**Comment by Tundrak** [comment]
Contento che sia riuscito a risolvere.
Ovviamente puoi aggiungere tutti i canali che vuoi alla lista se conosci il loro link, purtroppo quelli di Discovery al momento sono off-limits (sono protetti da DRM)
