### ISSUE TITLE
non funziona l'audio ra1 ra2 ra3

### ISSUE THREAD

**Issue by rufy81** [Tundrak/IPTV-Italia#130]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)

**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]
 - Programma utilizzato [es. VLC, Potplayer]
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by rufy81** [comment]
<html>
<body>


https://github.com/Tundrak/IPTV-Italia/raw/main/iptvitaplus.m3u
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by rufy81** [comment]
non funziona l'audio ra1 ra2 ra3

**Comment by Tundrak** [comment]
Probabilmente il tuo problema è stato risolto nella nuova [Versione Dicembre 2023](https://github.com/Tundrak/IPTV-Italia/releases/tag/v12-2023)!
