### ISSUE TITLE
[Richiesta Canale] Kiss Kiss TV + Radio TV Serie A (pronte all'uso)

### ISSUE THREAD

**Issue by infid0** [Tundrak/IPTV-Italia#133]
**iptvita.m3u**
```
#EXTINF:-1,[158] RADIO KISS KISS TV
https://kk.fluid.stream/KKMulti/smil:KissKissTV.smil/playlist.m3u8

#EXTINF:-1,[899] Radio TV Serie A con RDS
https://stream.radioseriea.com/50773f0d0070476a8612d9984c6059d8/index.m3u8
```
**iptvitaplus.m3u**
```
#EXTINF:-1 tvg-id="RadioKissKiss.it" tvg-chno="158" tvg-logo="https://cdn.jsdelivr.net/gh/Tundrak/IPTV-Italia/logos/radiokisskisstv.png" group-title="Radio",RADIO KISS KISS TV
https://kk.fluid.stream/KKMulti/smil:KissKissTV.smil/playlist.m3u8

#EXTINF:-1 tvg-id="RadioTvSerieA.it" tvg-chno="899" tvg-logo="https://i.imgur.com/MnjiF8C.png" group-title="Radio",Radio TV Serie A con RDS
https://stream.radioseriea.com/50773f0d0070476a8612d9984c6059d8/index.m3u8
```
_P.S. Il logo di Radio TV Serie A è caricato su imgur ma è già in linea con gli altri loghi in 133x99 px. Spero di aver fatto una cosa gradita, un saluto! :3_

**Comment by Tundrak** [comment]
Grazie del contributo!
Di sicuro includerò i canali nella prossima release, ma intendo aspettare un po' perchè si sta avvicinando la data di scadenza dei link dei canali Sky, e preferisco fare un aggiornamento unico dove cambio anche quelli (o li elimino se quelli nuovi non funzionano :( )

**Comment by infid0** [comment]
Grazie a te per la playlist! Se ti serve una mano taggami pure e appena posso aiuto volentieri :3

**Comment by Tundrak** [comment]
Alla fine l'aiuto è arrivato :)
Grazie ancora

**Comment by Tundrak** [comment]
Canali inclusi nella nuova [Versione Dicembre 2023](https://github.com/Tundrak/IPTV-Italia/releases/tag/v12-2023)!
