### ISSUE TITLE
[Problema vari canali]

### ISSUE THREAD

**Issue by SimoSalv** [Tundrak/IPTV-Italia#134]
Buongiorno,
sto cercando di utilizzare il vostro link per vedere i canali in "chiaro" tramite MyIPTV Player dalla Grecia, ma a parte qualche canale radio e video, danno tutti errore (es. tutta la RAI e Mediaset + Focus, ecc.) C'è possibilità di risolvere?

**Comment by Tundrak** [comment]
Ciao!
Purtroppo so che molti canali non sono visualizzabili dall'estero, ma non posso fare niente di concreto per migliorare la situazione: voglio continuare a usare link ufficiali e Rai e Mediaset bloccano la visualizzazione a indirizzi non italiani.
L'unica cosa che posso fare è consigliare una VPN (non sono un esperto ma penso che ci possano essere anche piani gratuiti accettabili)
Mi dispiace di non poter essere più d'aiuto
