### ISSUE TITLE
[Problema]

### ISSUE THREAD

**Issue by Ginomaster1234** [Tundrak/IPTV-Italia#135]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)
Tutta la Rai non funziona
**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Android
 - my IPTV player
 - giugno 2023

**Comment by Tundrak** [comment]
Ciao
Purtroppo posso confermare il problema, ma l'app non mi lascia tanto spazio per risolverlo perchè non ha letteralmente nessuna opzione o impostazione (come probabilmente avrai notato anche tu)
L'unica cosa che posso consigliarti è di cambiare player (uno che funziona sicuramente per Android è [Televizo](https://play.google.com/store/apps/details?id=com.ottplay.ottplay))

**Comment by Ginomaster1234** [comment]
Grazie della dritta!

Nel frattempo segnalo a tutti che funzionano anche con IPTV EXTREME usando come video player "light interfacce" selezionabile da impostazioni oppure dalla tendina "riproduci con...

**Comment by Tundrak** [comment]
Perfetto!
Chiudo l'Issue
