### ISSUE TITLE
[Problema] SS IPTV VIDAA - ritardo audio-video

### ISSUE THREAD

**Issue by pasq96** [Tundrak/IPTV-Italia#136]
**Canale TV / Radio interessato**
Si verifica in quasi tutti i canali principali.

**Descrivi il problema**
All'avvio dell'app SS IPTV si piattaforma Hisense VIDAA capita che l'audio sia desincronizzato rispetto al video. Tale problema rientra dopo un paio di zapping.
Purtroppo non ci sono settaggi all'interno dell'app per regolare il ritardo. Si può fare qualcosa lato playlist.

**Screenshot**
No

**Dispositivo utilizzato**
 - Tipo di dispositivo: Smart TV VIDAA OS
 - Programma utilizzato: SS IPTV
 - Versione lista: ultima disponibile

**Altre informazioni**
No

**Comment by Tundrak** [comment]
Ciao
Putroppo i file playlist sono piuttosto limitati nella possibilità di specificare cosa deve fare il player per riprodurre gli stream e nella [documentazione](https://ss-iptv.com/it/users/documents/m3u) non si parla di nessuna opzione per sincronizzare i flussi.
Se dici che cambiando canale qualche volta il problema si risolve da solo (è davvero strano) ho paura che dovrai continuare a fare così
Sei piuttosto fortunato che il problema si risolva e non continui all'infinito :)
