### ISSUE TITLE
Aggiunta canali Discovery ALLEGO ANCHE LA SORGENTE

### ISSUE THREAD

**Issue by GIM2000TR** [Tundrak/IPTV-Italia#137]
Ciao, vi chiederei se possibile inserire nella playlist tutti i canali gratuiti Discovery. Sono riuscito a trovarli a questo link:

https://uaz-nao-tv-italiane.blogspot.com/p/tv-italiane-diretta-streaming-gratis.html?m=1

Ad esempio, primo fra tutti, per il canale **Nove**, l'url è questo:

https://uaznao.com/nove-in-diretta-streaming-anche-allestero/

**Comment by Tundrak** [comment]
Ciao!
Purtroppo ho brutte notizie: quel sito (e quello ufficiale) usano link protetti da DRM, che rendono impossibile la riproduzione in moltissimi player (e in generale fuori da un browser)
Purtroppo non si può fare niente, se vuoi degli aggiornamenti tieni controllata #1 che è l'issue che controlla i canali Discovery in generale ma difficilmente li troveremo presto
