### ISSUE TITLE
sul pc windows le liste si riproducono senza problemi con vlc. sul cell android sempre con vlc non si vedono i canali principali rai e mediaset. mi suggerite una soluzione ?

### ISSUE THREAD

**Issue by ziodario** [Tundrak/IPTV-Italia#138]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)

**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]
 - Programma utilizzato [es. VLC, Potplayer]
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by Tundrak** [comment]
Ciao!
Purtroppo è un problema conosciuto: la versione Android di VLC non riconosce le opzioni estese incluse nella lista che permettono a quella Windows di riprodurre i canali.
Non c'è modo di risolvere il problema, l'unica cosa che posso consigliarti di fare è usare un'altra app: ce ne sono diverse, una che funziona sicuramente è [Televizo](https://play.google.com/store/apps/details?id=com.ottplay.ottplay)

**Comment by ziodario** [comment]
ciao grazie per la risposta tempestiva. il programma che mi hai suggerito funziona benissimo ma non mi fa trasmettere al chromecast. esiste un app con cui lo potrei fare? grazie

**Comment by Tundrak** [comment]
Purtroppo non ne conosco nessuno, e anche provando a scaricare velocemente qualche app dal Play Store non trovo nulla
L'unico consiglio che posso darti è di trasmettere tutto lo schermo del telefono, se la tua situazione lo permette

**Comment by ziodario** [comment]
ok. grazie ancora. ho provato anch'io un paio di app ma niente. dovessi trovare qualcosa la postero qui. ciao
