### ISSUE TITLE
Nuovo canale regionale toscano RTV38

### ISSUE THREAD

**Issue by manuelvita96** [Tundrak/IPTV-Italia#14]
**Canale Richiesto**
Salve, grazie per questa lista curata. Vorrei aiutare inserendo qualche canale, al momento ho trovato lo streaming di RTV38 che è diffuso in tutta la Toscana e parte dell'Umbria. Ho messo il link alla pagina del player e il link della playlist m3u8. Grazie

**URL Streaming**
http://www.rtv38.com/livetest.html

http://streamcdnm17-845d8509d2cb4f249dd0b2ae5755b6c2.msvdn.net/live/S12268608/CXHH7K39hg9K/chunklist_b1700864_DVR.m3u8

**Comment by Tundrak** [comment]
Grazie per il contributo! (Parlo anche per #15)
Cercherò di aggiungere i canali alla lista regionale il prima possibile (la Toscana è la prossima regione in ordine di abitanti)

**Comment by Tundrak** [comment]
Aggiunto il canale nella nuova pre-release [Test Regionale 9](https://github.com/Tundrak/IPTV-Italia/releases/tag/regionale-pre9)!
