### ISSUE TITLE
EPG Radio Italiane? 

### ISSUE THREAD

**Issue by lightingdesigner** [Tundrak/IPTV-Italia#140]
**Canale Richiesto**
Scrivi il nome completo del canale TV / Radio che vuoi aggiunto in una delle due liste [es. Rai 1]
Se il canale è regionale, specificalo e indica la regione d'appartenenza.

**URL Streaming**
Copia il link del sito internet ufficiale del canale da cui puoi vedere / sentire la diretta. [es. https://www.raiplay.it/dirette/rai1]

**Comment by Tundrak** [comment]
Ciao!
Purtroppo, non penso che una cosa simile sia già stata creata da qualcuno, e non credo che riuscirei a farlo neanche io con le mie conoscenze e gli strumenti che ho a disposizione.
Mi dispiace
