### ISSUE TITLE
[Richiesta Canale] 720p: Cine 34, Iris

### ISSUE THREAD

**Issue by colemar** [Tundrak/IPTV-Italia#141]
I canali seguenti sono già presenti in lista con risoluzione 576p.

Cine 34 720p:
https://live03-col.msf.cdn.mediaset.net/live/ch-b6/b6-clr.isml/manifest_hr.mpd

Iris 720p (quello già presente in lista è 576p):
https://live03-col.msf.cdn.mediaset.net/live/ch-ki/ki-clr.isml/manifest_hr.mpd

Twenty Seven 720p (quello già presente in lista è 576p):
https://live03-col.msf.cdn.mediaset.net/live/ch-ts/ts-clr.isml/manifest_hr.mpd

Focus 720p:
https://live03-col.msf.cdn.mediaset.net/live/ch-fu/fu-clr.isml/manifest_hr.mpd

Estratti da:
https://www-o.mediaset.net/diretta/cine34_cB6
https://www-o.mediaset.net/diretta/iris_cKI
https://www-o.mediaset.net/diretta/_cTS
https://www-o.mediaset.net/diretta/focus_cFU

**Comment by Tundrak** [comment]
Chiedo scusa per il ritardo estremo nella risposta
Fortunatamente tra poco arriverà una nuova versione della lista con link agguiornati che arrivano addirittura al Full HD! :)
(Non quelli che hai suggerito tu in specifico, ma la risoluzione è ancora migliore)
