### ISSUE TITLE
 igrandi assenti sono ancora assenti.. Warner TV Discovery

### ISSUE THREAD

**Issue by 13031976** [Tundrak/IPTV-Italia#142]
Non so vedono  i canali Warner TV  il 9  Dmax 
Discovery +  i miei canali regionali Sardegna**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)

Uso android auto con fermata auto da dispositivo Android

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]
 - Programma utilizzato [es. VLC, Potplayer]
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by 13031976** [comment]
> Non si vedono i canali Warner TV il 9 ad esempio Dmax + i miei canali regionali Sardegna  -videolina -canale 40  della Sardegna nn vedo quasi nulla
> 
> Uso android auto con fermata auto da dispositivo Android
> 
> **Screenshot** Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.
> 
> **Informazioni sul dispositivo**
> 
> * Tipo di dispositivo: [es. Computer, Smart TV]
> * Programma utilizzato [es. VLC, Potplayer]
> * Versione lista [es. v04-2021]
> 
> **Altre informazioni** Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by Trifone46** [comment]
Buona sera  per chi vuole vedere i canali Rai Mediaset e Musicali più i canali Discovery in chiaro essiste un app che racchiude tutti i canali che vi ho indicato basta cercarla sul web e un app senza pubblicita e gratuita ma non posso fare il nome per coretezza in internet essiste l app di cui parlo perche e un app che a un mio amico sul suo cell .

**Comment by 13031976** [comment]
Nn trovo niente nn mi puoi indicare via mail qualcosa

**Comment by Trifone46** [comment]
Se mi da una sua mail personale ho altro contatto le posso mandare il sito web da li potra scaricare apk in alternativa le posso mandare apk se non riesce a scaricarla dal sito che include tutti i canali che le ho detto visibili dal sito e da app le chiedo solo una cortesia di non condividere il sito web e l app su questo sito per coretezza se mai condividere il sito web e app con amici ecc ma non su questo sito .

**Comment by 13031976** [comment]
Certo che le do la mail pensavo la rilevava da dove ho fatto richiesta.... comunque..

 La mail è : ***@***.***

x non sbagliare se mi dà anche l'apk cercherò di disturbarla il meno possibile... (Sto tentando in tutti i modi di fare funzionare un app su smartphone android..app di cui mi mancano le URL m3u x trasferirle al computer di bordo della macchina...) In realtà ho una URL sola e ci sono pochissimi canali, vorrei ampliare la lista ma in alternativa va bene pure l'app che mi dà lei ....grazie in anticipo x ora anche solo x avermi risposto

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Trifone46** [comment]
La sua mail qui non viene vissualizzata non ostante l abbia scritta le scrivo una mia mail Trifone46@gmail.com mi invii la sua mail a l indirizzo che le ho indicato per inviarli il tutto .

**Comment by Trifone46** [comment]
La sua mail qui non viene vissualizzata non ostante l abbia scritta le scrivo una mia mail Trifone46@gmail.com
mi invii la sua mail a l indirizzo che le ho indicato per inviarle il tutto .

**Comment by Tundrak** [comment]
Mi dispiace, ma per avere i canali Discovery su questa lista dovranno diventare disponibili da fonti ufficiali
Difficile (purtroppo) ma nel dubbio segui i progressi su #1
