### ISSUE TITLE
[Problema] Canali RAI anche con VPN

### ISSUE THREAD

**Issue by SimoSalv** [Tundrak/IPTV-Italia#144]
Buongiorno,
dopo aver seguito il tuo consiglio della VPN (perché sto utilizzando i tuoi canali dalla Grecia), riesco a vederli tutti, tranne quelli RAI.
Potresti dirmi come posso risolvere?
Grazie.

**Comment by Tundrak** [comment]
Che strano, non saprei
Evidentemente la Rai prova a bloccare il traffico attraverso le VPN
Forse il problema è legato alla VPN specifica che hai provato e con un'altra funzionerebbero, però non sono sicuro neanch'io
