### ISSUE TITLE
[Richiesta Canale]

### ISSUE THREAD

**Issue by fabiomichelini** [Tundrak/IPTV-Italia#146]
ByoBlu
(nazionale)

https://www.byoblu.com
https://09bd1346f7a44cc9ac230cc1cb22ca4f.msvdn.net/live/S39249178/EnTK3KeeN1Eg/playlist.m3u8

Domanda, ogni quanto aggiorni/verifichi la lista?
Grazie. Fabio

**Comment by SimoLRepo** [comment]
@fabiomichelini Vedere #37 e #53

**Comment by Tundrak** [comment]
Ho ripensato alla questione, se vuoi i dettagli guarda #53
In breve, Byoblu è stato aggiunto nella nuova [Versione Dicembre 2023](https://github.com/Tundrak/IPTV-Italia/releases/tag/v12-2023)!
