### ISSUE TITLE
[Problema] Nessuna traccia audio (Rai 1, Rai 2, Rai 3)

### ISSUE THREAD

**Issue by azgaresncf** [Tundrak/IPTV-Italia#148]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)
- Rai 1
- Rai 2
- Rai 3

**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.
Nessuna traccia audio è abilitata (è cambiato ordine)

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]
 - Programma utilizzato [es. VLC, Potplayer]
 - Versione lista [es. v04-2021]
- Tipo di dispositivo: Computer
- Programma utilizzato: VLC 
- Versione lista: v06-2023

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.
Una pull request sarà fatta subito dopo la creazione di questo adesivo.

**Comment by Tundrak** [comment]
Aspetta l'arrivo a breve della nuova release con i fix inclusi :)

**Comment by Tundrak** [comment]
Tutti i cambiamenti sono oar disponibili nella nuova [Versione Dicembre 2023](https://github.com/Tundrak/IPTV-Italia/releases/tag/v12-2023)!
