### ISSUE TITLE
Nuovo canale regionale toscano Granducato TV 

### ISSUE THREAD

**Issue by manuelvita96** [Tundrak/IPTV-Italia#15]
**Canale Richiesto**
Questa invece è Granducato TV sempre a copertura regionale. Grazie

**URL Streaming**
https://www.telegranducato.it/live-tv/
https://www.granducatotv.eu/tv/granducato/stream/alt.m3u8_v6.php?vid=2&cid=841&m3u8=.m3u8

**Comment by Tundrak** [comment]
Aggiunto il canale nella nuova pre-release [Test Regionale 9](https://github.com/Tundrak/IPTV-Italia/releases/tag/regionale-pre9)!

**Comment by MisterLiv** [comment]
Granducato tv non funziona l'audio

**Comment by Tundrak** [comment]
Forse puoi dare più informazioni?
Provando il link https://www.granducatotv.eu/tv/granducato/hls sento l'audio normalmente.

**Comment by MisterLiv** [comment]
Che app o programma usi?

Scarica Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Tundrak** [comment]
Riesco ad aprirlo con PotPlayer, MyIPTV Player e anche direttamente con ffplay. Questo segnala che lo stream è corrotto, per cui può essere che qualche player non lo riproduca correttamente però io non posso farci niente
![001](https://user-images.githubusercontent.com/77153792/146254187-9a6b4f1e-3a64-46c1-ae1c-8722e4477a13.png)
