### ISSUE TITLE
[Problema] Tv8, Cielo e SkyTG 24 non funzionano più

### ISSUE THREAD

**Issue by m4tt86** [Tundrak/IPTV-Italia#150]
I canali Tv8, Cielo e SkyTG 24 non funzionano più.

Questa URL:
http://hlslive-web-gcdn-skycdn-it.akamaized.net/TACT/11223/tv8web/master.m3u8?hdnea=st=1639498341~exp=1702463400~acl=/*~hmac=c3c4c2de19ff0df4b4bb20587ce59af5232eadab2995f445b7506525413805dd

E'scaduta oggi. Lo si può vedere dal parametro exp=1702463400 infatti è espresso in formato unixtime che convertito nel nostro orario equivale a: mercoledì 13 dicembre 2023 11:30:00 [GMT+01:00].

Avete idee?

**Comment by Tundrak** [comment]
Ciao!
Per fortuna esistono nuovi link (se sei impaziente li trovi in #151) che valgono fino a fine 2025
A breve uscirà una nuova versione della lista che li include

**Comment by Tundrak** [comment]
Aggiornati i link nella nuova [Versione Dicembre 2023](https://github.com/Tundrak/IPTV-Italia/releases/tag/v12-2023)!
