### ISSUE TITLE
Nuovi link funzionanti per Cielo, TV 8, Skytg 24

### ISSUE THREAD

**Issue by marcoricciuti** [Tundrak/IPTV-Italia#151]
skytg 24: https://hlslive-web-gcdn-skycdn-it.akamaized.net/TACT/12221/web/master.m3u8?hdnts=st=1701861650~exp=1765449000~acl=/*~hmac=84c9f3f71e57b13c3a67afa8b29a8591ea9ed84bf786524399545d94be1ec04d
Cielo: https://hlslive-web-gcdn-skycdn-it.akamaized.net/TACT/11219/cieloweb/master.m3u8?hdnea=st=1701861650~exp=1765449000~acl=/*~hmac=84c9f3f71e57b13c3a67afa8b29a8591ea9ed84bf786524399545d94be1ec04d
Tv8: https://hlslive-web-gcdn-skycdn-it.akamaized.net/TACT/11223/tv8web/master.m3u8?hdnea=st=1701861650~exp=1765449000~acl=/*~hmac=84c9f3f71e57b13c3a67afa8b29a8591ea9ed84bf786524399545d94be1ec04d

**Comment by m4tt86** [comment]
@marcoricciuti  grazie. Posso sapere come hai ricalcolato l'hmac facendo in modo che scadano nel 2025?

**Comment by micheleciondolo** [comment]
come cavolo hai fatto ad aggirare la scandenza. ti amo

**Comment by Tundrak** [comment]
Grazie mille per avere trovato i link, a breve uscirà una nuova versione stabile con tutti i canali funzionanti
@micheleciondolo I nuovi parametri sono esposti nella diretta di Sky TG 24 (https://video.sky.it/diretta/tg24) e possono essere usati anche per tutti gli altri canali senza cambiare niente
Seguite i progressi in #150 che è stata aperta prima

**Comment by Jianluca** [comment]
@marcoricciuti ciao, puoi creare un nuovo token duraturo?
grazie 🙏
