### ISSUE TITLE
[Problema] io ho un problema a avviare canale 5 su iptvextreme

### ISSUE THREAD

**Issue by mattia2559** [Tundrak/IPTV-Italia#152]
io ho iptvextreme no pro a si vede i canali tv ma esempio canale 5 non funziona

**Comment by Trifone46** [comment]
Ciao da oggi so che anno chiuso tutti i canali ufficiali riguardo mediaset se qualcuno riesce a trovare nuovi link li posti qui

**Comment by Tundrak** [comment]
Lo sappiamo, è un problema di tutti i canali Mediaset recente
Il problema sta per essere risolto, segui il progresso della situazione su #153
