### ISSUE TITLE
Tutti i canali mediaset non funzionano più

### ISSUE THREAD

**Issue by zeustv** [Tundrak/IPTV-Italia#153]

**Comment by Trifone46** [comment]
Ciao da oggi so che anno chiuso tutti i link ufficiali riguardo mediaset attualmente su quanto so al momento non ci sono ulteriori link disponibili

**Comment by micheleciondolo** [comment]
vi do un suggerimento :) vi incollo i link che ho ritrovato con un po di ricerca. se riuscite a integrarli nella vostra lista sarebbe fantastico  :) I link degli altri canali mediaset dovrebbero avere una struttura simile.
Tv8 anche non funziona piu, ma quello è un altro meccanismo:



#EXTINF:-1 tvg-id="Rete4.it" tvg-chno="4" tvg-logo="https://cdn.jsdelivr.net/gh/Tundrak/IPTV-Italia/logos/rete4.png" group-title="Mediaset",Rete 4
#EXTVLCOPT:http-user-agent=Mozilla/5.0
https://live02-seg.msf.cdn.mediaset.net/live/ch-r4/r4-clr.isml/index.m3u8
#EXTINF:-1 tvg-id="Canale5.it" tvg-chno="5" tvg-logo="https://cdn.jsdelivr.net/gh/Tundrak/IPTV-Italia/logos/canale5.png" group-title="Mediaset",Canale 5
#EXTVLCOPT:http-user-agent=Mozilla/5.0
https://live02-seg.msf.cdn.mediaset.net/live/ch-c5/c5-clr.isml/index.m3u8
#EXTINF:-1 tvg-id="Italia1.it" tvg-chno="6" tvg-logo="https://cdn.jsdelivr.net/gh/Tundrak/IPTV-Italia/logos/italia1.png" group-title="Mediaset",Italia 1
#EXTVLCOPT:http-user-agent=Mozilla/5.0
https://live02-seg.msf.cdn.mediaset.net/live/ch-i1/i1-clr.isml/index.m3u8

**Comment by micheleciondolo** [comment]
no questi non dovrebbero scadere, infatti alcuni vengono usati da altre liste. credo siano i link "esteri".
ad ogni modo funzionano pare. 
Il segreto è.. 
prendi la lista di tundrak.. vedi come si chiama il canale, ti faccio un esempio: 
la 5 ha come link https://live2-mediaset-it.akamaized.net/content/hls_h0_clr_vos/live/channel(ka)/index.m3u8 
quindi il canale si chiama "ka".
usando questo nuovo tipo di link sarà:
https://live02-seg.msf.cdn.mediaset.net/live/ch-ka/ka-clr.isml/index.m3u8
(ho sostituito ka a i1 (che sta per italia uno)).
in sostanza basta seguire questa logica e possiamo ripopolare tutti i canali che stavano su akamai MEDIASET.

a questo punto se ci fosse un'anima pia che facesse una nuova versione della lista con i nuovi canali tv8, cielo e skytg24, e tutti i mediaset corretti, sarebbe perfetto :)

**Comment by simonebartoli** [comment]
Lista Completa Mediaset
[channel_list.m3u.txt](https://github.com/Tundrak/IPTV-Italia/files/13677823/channel_list.m3u.txt)

Come funziona questa repo? Posso aprire una pull request con l'aggiornamento o solo l'admin puo' aggiornare?

**Comment by infid0** [comment]
Ciao, dato che avevo già ricreato i nuovi link per un'altra lista, condividerli con voi non mi costa nulla :3 

```
Rete 4: https://live02-seg.msf.cdn.mediaset.net/live/ch-r4/r4-clr.isml/index.m3u8
Canale 5: https://live02-seg.msf.cdn.mediaset.net/live/ch-c5/c5-clr.isml/index.m3u8
Italia 1: https://live02-seg.msf.cdn.mediaset.net/live/ch-i1/i1-clr.isml/index.m3u8
20: https://live02-seg.msf.cdn.mediaset.net/live/ch-lb/lb-clr.isml/index.m3u8
Iris: https://live02-seg.msf.cdn.mediaset.net/live/ch-ki/ki-clr.isml/index.m3u8
27: https://live02-seg.msf.cdn.mediaset.net/live/ch-ts/ts-clr.isml/index.m3u8
La5: https://live02-seg.msf.cdn.mediaset.net/live/ch-ka/ka-clr.isml/index.m3u8
Cine34: https://live02-seg.msf.cdn.mediaset.net/live/ch-b6/b6-clr.isml/index.m3u8
Focus: https://live02-seg.msf.cdn.mediaset.net/live/ch-fu/fu-clr.isml/index.m3u8
Topcrime: https://live02-seg.msf.cdn.mediaset.net/live/ch-lt/lt-clr.isml/index.m3u8
Boing: https://live02-seg.msf.cdn.mediaset.net/live/ch-kb/kb-clr.isml/index.m3u8
Cartoonito: https://live02-seg.msf.cdn.mediaset.net/live/ch-la/la-clr.isml/index.m3u8
Italia 2: https://live02-seg.msf.cdn.mediaset.net/live/ch-i2/i2-clr.isml/index.m3u8
TGcom24: https://live02-seg.msf.cdn.mediaset.net/live/ch-kf/kf-clr.isml/index.m3u8
Mediaset Extra: https://live02-seg.msf.cdn.mediaset.net/live/ch-kq/kq-clr.isml/index.m3u8
Radio 105: https://live02-seg.msr.cdn.mediaset.net/live/ch-ec/ec-clr.isml/index.m3u8
R101: https://live02-seg.msr.cdn.mediaset.net/live/ch-er/er-clr.isml/index.m3u8
RMC: https://live02-seg.msr.cdn.mediaset.net/live/ch-bb/bb-clr.isml/index.m3u8
Virgin: https://live02-seg.msr.cdn.mediaset.net/live/ch-ew/ew-clr.isml/index.m3u8
```
Tutti testati e funzionanti, compresi i canali delle radio che differenziano leggermente dai link dei canali tv... @Tundrak

**Comment by nortek1986** [comment]
> Ciao, dato che avevo già ricreato i nuovi link per un'altra lista, condividili con voi non mi costa nulla :3
> 
> ```
> Rete 4: https://live02-seg.msf.cdn.mediaset.net/live/ch-r4/r4-clr.isml/index.m3u8
> Canale 5: https://live02-seg.msf.cdn.mediaset.net/live/ch-c5/c5-clr.isml/index.m3u8
> Italia 1: https://live02-seg.msf.cdn.mediaset.net/live/ch-i1/i1-clr.isml/index.m3u8
> 20: https://live02-seg.msf.cdn.mediaset.net/live/ch-lb/lb-clr.isml/index.m3u8
> Iris: https://live02-seg.msf.cdn.mediaset.net/live/ch-ki/ki-clr.isml/index.m3u8
> 27: https://live02-seg.msf.cdn.mediaset.net/live/ch-ts/ts-clr.isml/index.m3u8
> La5: https://live02-seg.msf.cdn.mediaset.net/live/ch-ka/ka-clr.isml/index.m3u8
> Cine34: https://live02-seg.msf.cdn.mediaset.net/live/ch-b6/b6-clr.isml/index.m3u8
> Focus: https://live02-seg.msf.cdn.mediaset.net/live/ch-fu/fu-clr.isml/index.m3u8
> Topcrime: https://live02-seg.msf.cdn.mediaset.net/live/ch-lt/lt-clr.isml/index.m3u8
> Boing: https://live02-seg.msf.cdn.mediaset.net/live/ch-kb/kb-clr.isml/index.m3u8
> Cartoonito: https://live02-seg.msf.cdn.mediaset.net/live/ch-la/la-clr.isml/index.m3u8
> Italia 2: https://live02-seg.msf.cdn.mediaset.net/live/ch-i2/i2-clr.isml/index.m3u8
> TGcom24: https://live02-seg.msf.cdn.mediaset.net/live/ch-kf/kf-clr.isml/index.m3u8
> Mediaset Extra: https://live02-seg.msf.cdn.mediaset.net/live/ch-kq/kq-clr.isml/index.m3u8
> Radio 105: https://live02-seg.msr.cdn.mediaset.net/live/ch-ec/ec-clr.isml/index.m3u8
> R101: https://live02-seg.msr.cdn.mediaset.net/live/ch-er/er-clr.isml/index.m3u8
> RMC: https://live02-seg.msr.cdn.mediaset.net/live/ch-bb/bb-clr.isml/index.m3u8
> Virgin: https://live02-seg.msr.cdn.mediaset.net/live/ch-ew/ew-clr.isml/index.m3u8
> ```
> 
> Tutti testati e funzionanti, compresi i canali delle radio che differiscono leggermente dai link dei canali tv...@Tundrak

Hai per caso fatto una nuova playlist m3u aggiornata con tutti i canali?

**Comment by nortek1986** [comment]
> Lista Completa Mediaset [channel_list.m3u.txt](https://github.com/Tundrak/IPTV-Italia/files/13677823/channel_list.m3u.txt)
> 
> Come funziona questo repository? Posso aprire una pull request con l'aggiornamento o solo l'admin può' aggiornare?

@simonebartoli SEI UN DIO...grazie per la lista aggiornata uomo.

**Comment by infid0** [comment]
> Hai per caso fatto una nuova playlist m3u aggiornata con tutti i canali?

Certo, ma è molto personalizzata. Infatti la uso sulla mia smart TV per replicare i canali DVB-T del Lazio, dato che la mia antenna purtroppo funziona malissimo. :c 
Comunque non mi sembra rispettoso condividere altre playlist qui... Un po' di pazienza e vedrete che il buon @Tundrak appena potrà sistemerà tutto! :3 

> @simonebartoli SEI UN DIO...grazie per la lista aggiornata uomo. Ci sono 7 canali che non funzionano nella tua lista: Tv8,cielo,sky tg24,radio 105tv,r101tv,virgin radio,radio Montecarlo TV. Se riusciamo a recuperare almeno cielo e tv8 siamo a cavallo.

I canali free di Sky sono stati corretti qui: #151 come detto in precedenza un po' di pazienza e @Tundrak sistemerà tutto appena potrà! :3

**Comment by micheleciondolo** [comment]
> > Hai per caso fatto una nuova playlist m3u aggiornata con tutti i canali?
> 
> Certo, ma è molto personalizzata. Infatti la uso sulla mia smart TV per replicare i canali DVB-T del Lazio, dato che la mia antenna purtroppo funziona malissimo. :c Comunque non mi sembra rispettoso condividere altre playlist qui... Un po' di pazienza e vedrete che il buon @Tundrak appena potrà sistemerà tutto! :3
> 

Infatti, poi ci vuole una lista nuova, che elimina anche i canali secondari che non funzionano e che oltre a quelli della Rai metta anche Tv8, Cielo, SkyTg24 aggiornati.
Insomma aspettiamo @Tundrak

**Comment by infid0** [comment]
Ok facciamo così, oggi è una giornata un po' impegnativa per cui se stasera ho del tempo da dedicarci. faccio un fork della lista standard (quella senza loghi e info superflue) e sistemo tutti i canali non funzionanti. Poi la invio qui come pull request. Così quando torna, Tundrak si ritrova il lavoro alleggerito e permette a voi di usarla come playlist provvisoria... Buona giornata! :3

**Comment by Trifone46** [comment]
Ciao infid0 ho letto che farai una lista standard (senza loghi ecc ) tempo permettendo ti volevo chiedere se puoi includere questi link in quella lista ho gia chiesto piu volte se venivano inseriti ma in tutte le liste che aggiornano questi canali non vengono mai messi i link sono i seguenti
https://server.bellaradio.it:1443/live/bellaradiotv/playlist.m3u8 ( Bella Radio TV )
https://59253971be783.streamlock.net/KKTV01/livestream/playlist.m3u8 ( Kiss Kiss Italia )
https://www.lostream.it/hls/telea/video.m3u8 ( Tele A ) se me li potra inserire mi farebbe un grande favore glie le sarei grato in cambio le potrei mandare due link riguardo lo sport link molto importati ma in privato
Per il momento la ringrazio tanto per tutto quello che a fatto fino a ora e per l impegno nel aver trovato nuovi link

**Comment by infid0** [comment]
Ok, fatto. Questo vale come link provvisorio in attesa che @Tundrak accetti la patch. Se riesco a farlo in breve tempo, provo a sistemare anche la versione Plus. :3 

`https://raw.githubusercontent.com/Tundrak/IPTV-Italia/f2beba943f86760e80c49155c6023aaaad590b85/iptvita.m3u`

> Ciao infid0 ho letto che farai una lista standard (senza loghi ecc ) tempo permettendo ti volevo chiedere se puoi includere questi link in quella lista ho gia chiesto piu volte se venivano inseriti ma in tutte le liste che aggiornano questi canali non vengono mai messi i link sono i seguenti https://server.bellaradio.it:1443/live/bellaradiotv/playlist.m3u8 ( Bella Radio TV ) https://59253971be783.streamlock.net/KKTV01/livestream/playlist.m3u8 ( Kiss Kiss Italia ) https://www.lostream.it/hls/telea/video.m3u8 ( Tele A ) se me li potra inserire mi farebbe un grande favore glie le sarei grato in cambio le potrei mandare due link riguardo lo sport link molto importati ma in privato Per il momento la ringrazio tanto per tutto quello che a fatto fino a ora e per l impegno nel aver trovato nuovi link

Ciao. il fix di Kiss Kiss era previsto da tempo, mentre gli altri due canali sono regionali e non nazionali. Ecco perché non sono mai stati presenti nella main playlist. Non so, forse li trovi nella sezione "iptvregionale" vedi se sono qui... :/ 

`https://raw.githubusercontent.com/Tundrak/IPTV-Italia/main/iptvregionale-History/iptvregionale-pre9/iptvcampania-pre9.m3u`

**Comment by infid0** [comment]
Ok, fatto. Questi valgono come link provvisori in attesa che @Tundrak accetti le patch. C'è sia la playlist standard, che quella Plus. Per favore fatemi sapere se ci sono errori che purtroppo le ho dovute fare di fretta, grazie! :3 

`https://raw.githubusercontent.com/Tundrak/IPTV-Italia/f2beba943f86760e80c49155c6023aaaad590b85/iptvita.m3u`

`https://raw.githubusercontent.com/Tundrak/IPTV-Italia/e5c000b3ac61ce44878e64fddc3ec80af428a7a6/iptvitaplus.m3u`

**Comment by micheleciondolo** [comment]
grazie infid0 :)

**Comment by Trifone46** [comment]
Provati i link funzionano entrambi tutti i canali che a inserito in entrambe le liste funzionano senza problemi non ci sono errori
Solo su kiss kiss Italia il link che le avevo segnalato questo https://59253971be783.streamlock.net/KKTV01/livestream/playlist.m3u8 riguarda un altro kiss kiss Italia che preferivo rispetto a quello gia presente nella lista
Mille grazie per tutto

**Comment by infid0** [comment]
Se funziona tutto correttamente mi fa davvero piacere! Per la questione Kiss Kiss TV: il link presente nella lista è quello ufficiale preso dal loro sito. Inoltre questo è il canale tv **nazionale** presente nel digitale terrestre, mentre "Kiss Kiss Italia" è da considerarsi "regionale" in quanto non visibile su tutto il territorio via antenna. Per cui se alcuni canali sono "esclusi" è solo perché questa playlist (Tundrak) punta a replicare la tv dvb-t nazionale. Ci sono anche i canali regionali/locali, ma sono raccolti a parte, nella sezione **iptvregionale**. ;)
Comunque grazie a tutti per la collaborazione! :3

**Comment by fdambrosio** [comment]
grazie funzionano i canali mediaset !

**Comment by Tundrak** [comment]
Grazie mille a tutti per il progresso e il dialogo costruttivo su questa Issue :)
Mi sembra di essere sempre più indaffarato di prima, ma con tutto quello che ha smesso di funzionare questa settimana (letteralmente quasi ogni canale) devo dare attenzione anche a questo
Entro domani dovrebbe uscire la versione stabile definitiva

**Comment by Tundrak** [comment]
Trovare il bug è stato velocissimo: ovviamente basta usare VLC e l'audio dei canali Mediaset non viene riconosciuto (a parte i primi secondi)
Potrei dover ripiegare sui link https://live03-col.msf.cdn.mediaset.net/live/ch-XX/XX-clr.isml/manifest_hr.mpd (con XX come codice del canale) anche se sono "solo" in 720p perchè la compatibilità con VLC è necessaria per ridurre il numero di Issue aperte

**Comment by Tundrak** [comment]
Finalmente è arrivata la nuova [Versione Dicembre 2023](https://github.com/Tundrak/IPTV-Italia/releases/tag/v12-2023), con tutti gli aggiornamenti!
Speriamo che sopravviva almeno fino a Natale :)

**Comment by Trifone46** [comment]
Ciao infid0 da poco e stata rilasciato l aggiornamento di dicembre 2023 ma con il formato manifest.mpd i canali mediaset non vanno bene l audio si accavala più volte ripetendo le stesse parole e l audio tende a stoparsi di colpo per qualche secondo diciamo che i canali mediaset era meglio con il finale index.m3u8 in quanto non ci sono problemi come nel caso della lista provvisoria fatta da te sarebbe questa https://raw.githubusercontent.com/Tundrak/IPTV-Italia/e5c000b3ac61ce44878e64fddc3ec80af428a7a6/iptvitaplus.m3u inoltre la risoluzione del tuo caso e migliore ti volevo chiedere se ti e possibile aggiornare Donna Tv l unico che non va piu il nuovo link e questo
https://sportitaliaamd.akamaized.net/video_0/Donna_TV/hls/42EB42E58EA44362045EFEA804E3FCF0DB33C481/index.m3u8
Inoltre se ti e possibile aggiungere questo canale presente nel l ultimo aggiornamento dicembre 2023
https://09bd1346f7a44cc9ac230cc1cb22ca4f.msvdn.net/live/S39249178/EnTK3KeeN1Eg/playlist.m3u8 ( Byoblu )
Riguardo il formato se ti sara possibile usare il formato txt prendendo spunto da quella plus ciò per categoria sempre se avrai un po di tempo ti ringrazio in anticipo sempre per la tua disponibilita e generosita ti auguro una buona serata .

**Comment by infid0** [comment]
Ciao @Trifone46 ti ringrazio per la stima dimostrata ma queste playlist sono di Tundrak non mie. È lui che le gestiste con pazienza e che cerca di accontentare tutti. Quelle che ho pubblicato io erano soltanto correzioni di canali non funzionanti in attesa di approvazione, per questo motivo _provvisorie_. Comunque noto con piacere che Tundrak ti ha accontentato in un lampo, infatti gli stream da te richiesti sono già presenti nelle playlist ufficiali! :3 
Un saluto a tutti!

**Comment by Trifone46** [comment]
infid0 ti ringrazio per avermi risposto comprendo.quanto mi rimane di fatto che la lista ufficiale a i problemi che avevo indicato in precedenza e quindi preferisco usare la tua lista provvisoria almeno fino a quando funziona  quella con le categorie  sia per una questione che il finale dei link canali mediaset e in formato  index.m3u8 e sia per una questione di risoluzione e quindi il link non a problemi se si usa quel finale  index.m3u8 non ostante non va piu un canale Donna TV
Attualmente mi risulta che la lista ufficiale aggiornata dicembre 2023 i link mediaset il finale risulta il formato manifest.mpd di cui da tutti che ho descritto in conclusione usero la lista provvisoria che a messo lei a disposizione
Le ribadisco i miei saluti la ringrazio per la sua gentilezza educazione rispetto disponibilita e pazienza .

**Comment by Trifone46** [comment]
infid0 ti ringrazio per avermi risposto comprendo.quanto mi dici ma rimane di fatto che la lista ufficiale a i problemi che avevo indicato in precedenza e quindi preferisco usare la tua lista provvisoria almeno fino a quando funziona  quella con le categorie  sia per una questione che il finale dei link canali mediaset e in formato  index.m3u8 e sia per una questione di risoluzione e quindi il link non a problemi se si usa quel finale  index.m3u8 non ostante non va piu un canale Donna TV
Attualmente mi risulta che la lista ufficiale aggiornata dicembre 2023 i link mediaset il finale risulta il formato manifest.mpd di cui da tutti che ho descritto in conclusione usero la lista provvisoria che a messo lei a disposizione
Le ribadisco i miei saluti la ringrazio per la sua gentilezza educazione rispetto disponibilita e pazienza .

**Comment by Trifone46** [comment]
infid0 ti ringrazio per avermi risposto comprendo.quanto mi dici ma rimane di fatto che la lista ufficiale a i problemi che avevo indicato in precedenza e quindi preferisco usare la tua lista provvisoria almeno fino a quando funziona  quella con le categorie  sia per una questione che il finale dei link canali mediaset e in formato  index.m3u8 e sia per una questione di risoluzione e quindi il link non a problemi se si usa quel finale  index.m3u8 non ostante non va piu un canale Donna TV
Attualmente mi risulta che la lista ufficiale aggiornata dicembre 2023 i link mediaset il finale risulta il formato manifest.mpd di cui da tutti i problemi che ti ho descritto in conclusione usero la lista provvisoria che ai messo tu a disposizione
ti ringrazio per la tua gentilezza educazione rispetto disponibilita e pazienza .

**Comment by Tundrak** [comment]
@Trifone46 capisco il disagio.
Mi dispiace di aver potuto creare problemi con quei link ma sto cercando la compatibilità massima e i link .mpd funzionano relativamente dappertutto.
Capisco che però "relativamente" possa non essere abbastanza, per cui ho aggiornato la release con playlist identiche ma che usano i link .m3u8, la puoi trovare [dove immagini](https://github.com/Tundrak/IPTV-Italia/releases/tag/v12-2023)
