### ISSUE TITLE
Canali mediaset off[Problema]

### ISSUE THREAD

**Issue by nortek1986** [Tundrak/IPTV-Italia#154]
14/12/2023
Tutti i canali mediaset non funzionano più.
La RAI funziona

**Comment by comleoita** [comment]
Hanno cambiato i link.
SOLUZIONE:
**LINK in formato MPD**
`https://live03-seg.msf.cdn.mediaset.net/live/ch-r4/r4-clr.isml/manifest.mpd`

**LINK in formato M3U8**
`https://live02-seg.msf.cdn.mediaset.net/live/ch-r4/r4-clr.isml/index.m3u8`


I link che ho postato sono entrambi di Rete4, per avere gli altri canali basta sostituire il parametro "r4" presente due volte nel link con quello che, nel vecchio link non più funzionante, era tra parentesi.
Esempio:
link vecchio: https://live2-mediaset-it.akamaized.net/content/hls_h0_clr_vos/live/channel(**i1**)/index.m3u8 (italia1)
diventa in quello nuovo: https://live03-seg.msf.cdn.mediaset.net/live/ch-**i1**/**i1**-clr.isml/manifest.mpd (italia1)

**Comment by nortek1986** [comment]
Ok ti ringrazio. Se riuscissi a rifare la lista completa aggiornata e riupparla sarebbe fantastico.Il 14 Dic 2023 22:04, Compa ***@***.***> ha scritto:
Hanno cambiato i link.
SOLUZIONE:
LINK in formato MPD
https://live03-seg.msf.cdn.mediaset.net/live/ch-r4/r4-clr.isml/manifest.mpd
LINK in formato M3U8
https://live02-seg.msf.cdn.mediaset.net/live/ch-r4/r4-clr.isml/index.m3u8
I link che ho postato sono entrambi di Rete4, per avere gli altri canali basta sostituire il parametro "r4" presente due volte nel link con quello che, nel vecchio link non più funzionante, era tra parentesi.
Esempio:
link vecchio: https://live2-mediaset-it.akamaized.net/content/hls_h0_clr_vos/live/channel(**i1**)/index.m3u8 (italia1)
diventa in quello nuovo: https://live03-seg.msf.cdn.mediaset.net/live/ch-**i1**/**i1**-clr.isml/manifest.mpd (italia1)

**Comment by Tundrak** [comment]
Duplicato di #153
