### ISSUE TITLE
[canali Mediaset morti ! ☹️]

### ISSUE THREAD

**Issue by ztony91** [Tundrak/IPTV-Italia#155]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)

**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]
 - Programma utilizzato [es. VLC, Potplayer]
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by ztony91** [comment]
Canali Mediaset morti ☹️

**Comment by micheleciondolo** [comment]
ma perché non vedete gli issue aperti tipo un'ora fa, invece di aprirne 400 uguali?

**Comment by Tundrak** [comment]
Duplicato di #153

**Comment by ztony91** [comment]
Ciao perdonami per la mia poca praticità non mi ero accorto di aver replicato un issue già aperto, Ti riscrivo per avvisare che ho notato un altro problema oggi i canali Mediaset vanno in loop continuo, ho notato che il formato dei link mediaset e cambiato ed che caricate ancora  quelli in m3u8 che a questo punto suppongo siano ancora funzionanti però bisogna scaricare il file quindi una volta caricato non sarà più auto aggiornante,Mi chiedevo se il problema potrebbe essere proprio dovuto a questo,E se a questo punto forse potreste creare un link auto aggiornante con i vecchi formati che sembrino adare, Utilizzo la vostra lista da parecchio tempo con tivimate davvero una mitica soluzione mi trovo veramente benissimo colgo l'occasione per dirvi grazie per il vostro lavoro.Saluti, Claudio.Sent from Android deviceIl 15 dic 2023 09:56, miki ***@***.***> ha scritto:
ma perché non vedete gli issue aperti tipo un'ora fa, invece di aprirne 400 uguali?
