### ISSUE TITLE
Problema Canali Reti Mediaset

### ISSUE THREAD

**Issue by Maribu2000** [Tundrak/IPTV-Italia#158]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)
Canali reti Mediaset.

**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.
Non sono più visibili i canali delle reti Mediaset da un paio di giorni.

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]
 - Programma utilizzato [es. VLC, Potplayer]
 - Versione lista [es. v04-2021]
 Utilizzo sia VLC che IPTVPlayer ma il problema è presente su entrambi i player.

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.
Spero che tu possa aggiornare la lista con i link di streaming delle reti Mediaset funzionanti. Non so se leggerai questo post ma approfitto comunque per farti i complimenti per il lavoro eccezionale che hai fatto. La migliore lista di canali in chiaro che io abbia mai trovato fino ad oggi.

**Comment by Tundrak** [comment]
Duplicato di #153
