### ISSUE TITLE
canali mediaset non funzionanti

### ISSUE THREAD

**Issue by fabiomichelini** [Tundrak/IPTV-Italia#164]
canali mediaset,
da una settimana non si vedono,
usato VLC, altri player, libreria HLS javascript,
possibile che siano passati al protocollo DASH e richiedano anche credenziali? (gli stream su Infinity sembrano confermare)

**Comment by PilaScat** [comment]
mi aggiungo, da l'update di ieri non vanno più

**Comment by Tundrak** [comment]
Ho aggiunto playlist di ripiego all'[ultima release](https://github.com/Tundrak/IPTV-Italia/releases/tag/v12-2023) in modo da risolvere i problemi di chi non riesce a vedere i canali Mediaset con quella principale
Per i dettagli della scelta leggete il mio commento finale in #165

P.S.: i link della lista principale usano DASH, ma sono senza DRM: se non funzionano è perchè il tuo player non li riproduce correttamente (almeno con VLC non dovrebbero avere problemi)
