### ISSUE TITLE
Problema dei nuovi link mpd

### ISSUE THREAD

**Issue by Lc4B** [Tundrak/IPTV-Italia#165]
I nuovi link di mediaset mpd (come: `https://live03-col.msf.cdn.mediaset.net/live/ch-c5/c5-clr.isml/manifest.mpd`) hanno dei problemi di riproduzione, il video va in loop a piccoli pezzi mentre l'audio continua a funzionare, o viceversa, il video continua a funzionare e l'audio si blocca in loop di piccoli pezzi; mentre i link m3u8 provvisori (`https://live02-seg.msf.cdn.mediaset.net/live/ch-c5/c5-clr.isml/index.m3u8`) funzionano correttamente.

Dettagli (non so se utili):
Mi pare che i primi errori cominci a darli sempre dopo 1m e 20s circa di riproduzione.
Se provo a registrare un esempio delle parti in loop queste risultano vuote (della parte audio o video) nel file finale.
Utilizzo mpv v0.37.0-58-gf551a9da e la console mostra in continuazione dall'apertura della diretta le info:
```
[ffmpeg] https: HTTP error 404 Not Found
[ffmpeg/demuxer] dash: Failed to open fragment of playlist
```
e a volte con l'errore di loop:
`[cplayer] Audio/Video desynchronisation detected!`

**Comment by Trifone46** [comment]
Confermo quanto dice Lc4B ho i stessi problemi quando i link mediaset erano in index.m3u8 funzionavano in modo perfetto non mi davano neanche un minimo di problemi tante che la lista provvisoria mediaset che aveva creato infid0 con finale index.m3u8 funziona tutt'ora bene e non da un minimo di problemi

**Comment by Trifone46** [comment]
Confermo quanto dice Lc4B ho i stessi problemi quando i link mediaset erano in index.m3u8 funzionavano in modo perfetto non mi davano neanche un minimo di problemi tante che la lista provvisoria mediaset che aveva creato infid0 con finale index.m3u8 funziona tutt'ora bene e non da un minimo di problemi tante che ho deciso di utilizzare di nuovo la lista provvisoria perche i canali mediaset vanno bene

**Comment by Tundrak** [comment]
Mi dispiace di aver creato problemi con l'ultimo aggiornamento, e cerco di riassumere la situazione in questo commento.
Purtroppo con la lista cerco di ottenere la massima compatibilità possibile, ma vivo in un mondo dove esistono:
- VLC (il player usato dalla "persona media" che arriva qui e scarica la playlist), che funziona perfettamente con i link mpd ma per niente con quelli m3u8 (perchè è VLC ed è speciale)
- Un universo di decine di altri player usati da tante altre persone che funzionano con i link m3u8 e ogni tanto anche con quelli mpd, ma la grande maggioranza ha problemi di buffering

Faccio molta fatica a decidere e in ogni caso mi ritroverò decine di Issue della persona che per sfortuna usa il player sbagliato.

Comunque, c'è ancora speranza: ho aggiunto all'[ultima release](https://github.com/Tundrak/IPTV-Italia/releases/tag/v12-2023) playlist che usano i link m3u8 tanto amati da quasi tutti i player, così che tutti possano avere i canali Mediaset che vogliono guardare (dopo una semplice scelta)
Provale e dimmi se il problema è risolto!

**Comment by Trifone46** [comment]
Scaricando la lista che mi a indicato le confermo che il problema e stato risolto creando la stessa lista con link m3u8 mediaset va bene e tutti i restanti canali la ringrazio per tutto e per la sua disponibilita

**Comment by Lc4B** [comment]
ho provato anch'io un paio di canali m3u8 per circa 10 minuti l'uno e pare sia tutto apposto, grazie mille!
per quanto riguarda VLC a me funzionavano malissimo tutti i canali, poi ho capito che il problema era la mia versione troppo datata XD (comunque preferisco mpv quindi grazie ancora per la versione HLS! )

**Comment by Tundrak** [comment]
@Lc4B E' vero, fino alla versione 3.0.20 mi sembra che non funzionasse praticamente nessun link .mpd, e ora sono diventati l'unico modo per vedere la metà dei canali
