### ISSUE TITLE
canali LD

### ISSUE THREAD

**Issue by dannythevii** [Tundrak/IPTV-Italia#166]
**Canale Richiesto**
Scrivi il nome completo del canale TV / Radio che vuoi aggiunto in una delle due liste [es. Rai 1]
Se il canale è regionale, specificalo e indica la regione d'appartenenza.

**URL Streaming**
Copia il link del sito internet ufficiale del canale da cui puoi vedere / sentire la diretta. [es. https://www.raiplay.it/dirette/rai1]

**Comment by dannythevii** [comment]
Buongiorno e grazie infinite per il tuo lavoro
sarebbe possibile inserire anche i canali RAI e Mediaset non in HD?
per coloro che hanno una adsl non troppo prestante sarebbe utile.

grazie 1000 e tantissimi auguri a te e famiglia.
Daniele

**Comment by Tundrak** [comment]
Ciao!
Posso chiedere quale sistema operativo e quale player usi?
Quasi tutti i canali nella lista (sicuramente tutti quelli Rai e Mediaset) sono disponibili con diversi flussi e permettono di secgliere la risoluzione in una certa gamma per migliorare l'uso della rete
Tanti player hanno metodi per cambiare flusso, ma molti altri no

**Comment by dannythevii** [comment]
ciao
innanzitutto grazie per la risposta, scusa se rispondo solo ora...
la tua lista sta funzionando egregiamente su una tv LG e il player è SS IPTV in wifi.
è bello vedere un esponente di questa triste Italia fare qualcosa di utile per la comunità, grazie anche a nome di coloro che utilizzano il tuo lavoro.

auguro a te e alla tua famiglia un buon Natale e felice anno nuovo e di nuovo grazie.

Daniele

**Comment by Tundrak** [comment]
Non preoccuparti, anch'io posso metterci molto tempo :)
In teoria i player dovrebbero scegliere il flusso con la risoluzione migliore a sceonda della larghezza di banda disponibile, non posso provare personalmente ma in teoria anche SS IPTV dovrebbe cambiare risoluzione automaticamente al bisogno
Non capisco se tu abbia personalmente questo problema o stia soltando chiedendo in generale, perchè in teoria la lista così com'è dovrebbe adattarsi a tutte le velocità

**Comment by dannythevii** [comment]
grazie per la risposta
no, pensavo soltanto di migliorare questo bel progetto con un consiglio :-)
grazie di tutto e buone feste
Daniele

**Comment by Tundrak** [comment]
Oh, capisco
Allora in teoria dovrebbe essere tutto a posto, perchè tutte le risoluzioni sono già disponibili
Buone feste anche a te!
