### ISSUE TITLE
[Problema]Rai non va! 

### ISSUE THREAD

**Issue by Namaisape** [Tundrak/IPTV-Italia#167]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)

**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]
 - Programma utilizzato [es. VLC, Potplayer]
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by Namaisape** [comment]
I canali Rai non funzionano avete soluzioni?

**Comment by Tundrak** [comment]
E' possibile che i canali Rai non funzionino sul tuo player.
Posso avere più informazioni su sistema operativo e player che usi? (Le domande nel primo commento senza risposta)

**Comment by Tundrak** [comment]
Se non rispondi entro qualche giorno, chiuderò l'Issue per inattività
Comunque usando un player come VLC o Potplayer su Windows o Televizo su Android i canali dovrebbero essere a posto

**Comment by sman-80** [comment]
Ciao approfitto della stessa discussione
Su player ss IPTV da Smart tv LG
E su GSE IPTV su iphone
Non vanno i canali RAI Uno e Rai Due
Mentre funziona Rai tre ho provato anche ad inserire il canale mediacom.rai.it che funziona da browser Safari ma su ss IPTV non va
