### ISSUE TITLE
[Richiesta Canale] TUTTI i canali WBD sono ora visibili IN CHIARO grazie a Samsung TV Plus!

### ISSUE THREAD

**Issue by FrancescoRosi** [Tundrak/IPTV-Italia#168]
Grazie all'aggiunta dei canali Warner Bros. Discovery su Samsung TV Plus, tutti i canali del gruppo ~~tranne Warner TV~~ sono visibili **in chiaro**, senza alcun tipo di DRM, **e in 1080p**!

### URL Streaming
[9] NOVE - https://amg16146-wbdi-amg16146c1-samsung-it-1831.playouts.now.amagi.tv/playlist/amg16146-warnerbrosdiscoveryitalia-nove-samsungit/playlist.m3u8
[31] Real Time - 
https://amg16146-wbdi-amg16146c2-samsung-it-1835.playouts.now.amagi.tv/playlist/amg16146-warnerbrosdiscoveryitalia-realtime-samsungit/playlist.m3u8
[33] Food Network - https://amg16146-wbdi-amg16146c3-samsung-it-1836.playouts.now.amagi.tv/playlist/amg16146-warnerbrosdiscoveryitalia-foodnetwork-samsungit/playlist.m3u8
[37] Warner TV - https://amg16146-wbdi-amg16146c4-samsung-it-1837.playouts.now.amagi.tv/playlist/amg16146-warnerbrosdiscoveryitalia-warnertv-samsungit/playlist.m3u8
[38] Giallo - https://amg16146-wbdi-amg16146c5-samsung-it-1838.playouts.now.amagi.tv/playlist/amg16146-warnerbrosdiscoveryitalia-giallo-samsungit/playlist.m3u8
[41] K2 - https://amg16146-wbdi-amg16146c6-samsung-it-1839.playouts.now.amagi.tv/playlist/amg16146-warnerbrosdiscoveryitalia-k2-samsungit/playlist.m3u8
[44] Frisbee - 
https://amg16146-wbdi-amg16146c7-samsung-it-1840.playouts.now.amagi.tv/playlist/amg16146-warnerbrosdiscoveryitalia-frisbee-samsungit/playlist.m3u8
[52] DMAX - https://amg16146-wbdi-amg16146c8-samsung-it-1841.playouts.now.amagi.tv/playlist/amg16146-warnerbrosdiscoveryitalia-dmax-samsungit/playlist.m3u8
[56] HGTV - https://amg16146-wbdi-amg16146c9-samsung-it-1842.playouts.now.amagi.tv/playlist/amg16146-warnerbrosdiscoveryitalia-hgtv-samsungit/playlist.m3u8
[59] Motor Trend - https://amg16146-wbdi-amg16146c10-samsung-it-1843.playouts.now.amagi.tv/playlist/amg16146-warnerbrosdiscoveryitalia-motortrend-samsungit/playlist.m3u8

**Comment by FrancescoRosi** [comment]
**TROVATO ANCHE WARNER TV!**
https://amg16146-wbdi-amg16146c4-samsung-it-1837.playouts.now.amagi.tv/playlist/amg16146-warnerbrosdiscoveryitalia-warnertv-samsungit/playlist.m3u8

**Comment by Tundrak** [comment]
INCREDIBILE, grazie per la scoperta
Questo potrebbe completare una volta per tutte la lista (a meno che non arrivino gli avvocati di Discovery come tra l'altro è già successo in diversi casi su Github)
Se tutto va bene ci sarà un rilascio all'inizio di Gennaio (non sia mai che escano due versioni nello stesso mese)

**Comment by DarkSofter** [comment]
@Tundrak ho aggiunto i canali sulla mia playlist 4 o 5 giorni fa e confermo che tutto funziona perfettamente, il zapping e velocissimo anche con vpn. grazie mille @FrancescoRosi!

**Comment by Tundrak** [comment]
Tutti i canali aggiunti nell'ultima [Release Gennaio 2024](https://github.com/Tundrak/IPTV-Italia/releases/tag/v01-2024)!
Speriamo che rimangano :)

**Comment by rgiorgiotech** [comment]
Ciao a tutti, scrivo su questo issue per chiedere il motivo per cui, almeno su Real Time, in corrispondenza della pubblicità c'è un bumper che si ripete fino alla fine del rullo. È solo una curiosità, visto che indubbiamente delle pubblicità non mi interessa nulla. Tra l'altro ricaricando il flusso la pubblicità viene visualizzata, quindi sembra essere qualcosa di sovrapposto al flusso. Non mi è ben chiaro come funzioni. Grazie :)

**Comment by FrancescoRosi** [comment]
> Ciao a tutti, scrivo su questo issue per chiedere il motivo per cui, almeno su Real Time, in corrispondenza della pubblicità c'è un bumper che si ripete fino alla fine del rullo. È solo una curiosità, visto che indubbiamente delle pubblicità non mi interessa nulla. Tra l'altro ricaricando il flusso la pubblicità viene visualizzata, quindi sembra essere qualcosa di sovrapposto al flusso. Non mi è ben chiaro come funzioni. Grazie :)

Succede su tutti i canali WBD, non solo Real Time. Provo a spiegartelo nel miglior modo possibile 😉 

Quando parte la pubblicità su un "normale" canale Samsung TV Plus, cioè destinato alla visione solo su piattaforme FAST (TV Plus, Rakuten TV, ecc.), sul flusso video viene mandato in onda una schermata per informare il telespettatore che la programmazione sta per ritornare, del tipo "ritorneremo tra poco".

Questa schermata, però, viene visualizzata di solito solo per una decina di secondi prima della fine della pubblicità. Questo perché, all'inizio di un'interruzione pubblicitaria, Samsung TV Plus sovrappone la sua di pubblicità tramite software sulla TV, per poterle personalizzare meglio al telespettatore.

Quindi idealmente l'utente dovrebbe vedere solo le pubblicità inserita tramite software, poi quella schermata la mettono come "fallback" nel caso le pubblicità software non bastino per riempire tutto lo spazio dell'interruzione pubblicitaria. Tra l'altro, se non sbaglio, se ci si sintonizza sul canale _durante_ un'interruzione pubblicitaria, TV Plus non prova a metterne neanche una di pubblicità e la schermata rimane fino alla fine dell'interruzione. Almeno io mi ricordo così, anche se mi sembra un po' strano e senza senso...

Ovviamente, però, i canali WBD non sono canali prodotti con le piattaforme FAST in mente, quindi le cose cambiano un po'.

Su questi canali la schermata """""informativa""""" usata come fallback sarebbe il bumper in loop alla quale ti riferivi, ma viene inserita in un modo molto interessante... Invece di essere trasmessa direttamente sul flusso video destinato a TV Plus, diciamo che viene inserita tramite uno "switch". Se eri già sintonizzat* sul canale e parte la pubblicità, avviene questo switch, e il flusso passa da quello "normale" del canale (con la programmazione normale) a quello con il bumper in loop. Poi alla fine ovviamente ritorna quello normale. Se però ti sintonizzi sul canale durante la pubblicità, non avviene nessuno switch e rimane il flusso normale del canale, con la sua solita pubblicità visibile sul DTT, satellite, ecc. Ha molto senso ovviamente, almeno possono mostrare le pubblicità anche se qualcuno si sintonizza durante un'interruzione pubblicitaria, a differenza di tutti gli altri canali TV Plus.

Come ho già detto, la pubblicità di TV Plus dovrebbe coprire la schermata di fallback, ma essendo inserita tramite software che ovviamente non viene usato nella riproduzione di questi canali da fonti esterne a TV Plus, noi vediamo solo un bumper in loop fino alla fine della pubblicità.

Spero di essermi spiegato abbastanza bene 😉

**Comment by rgiorgiotech** [comment]
> Succede su tutti i canali WBD, non solo Real Time. Provo a spiegartelo nel miglior modo possibile 😉
> 
> Quando parte la pubblicità su un "normale" canale Samsung TV Plus, cioè destinato alla visione solo su piattaforme FAST (TV Plus, Rakuten TV, ecc.), sul flusso video viene mandato in onda una schermata per informare il telespettatore che la programmazione sta per ritornare, del tipo "ritorneremo tra poco".
> 
> Questa schermata, però, viene visualizzata di solito solo per una decina di secondi prima della fine della pubblicità. Questo perché, all'inizio di un'interruzione pubblicitaria, Samsung TV Plus sovrappone la sua di pubblicità tramite software sulla TV, per poterle personalizzare meglio al telespettatore.
> 
> Quindi idealmente l'utente dovrebbe vedere solo le pubblicità inserita tramite software, poi quella schermata la mettono come "fallback" nel caso le pubblicità software non bastino per riempire tutto lo spazio dell'interruzione pubblicitaria. Tra l'altro, se non sbaglio, se ci si sintonizza sul canale _durante_ un'interruzione pubblicitaria, TV Plus non prova a metterne neanche una di pubblicità e la schermata rimane fino alla fine dell'interruzione. Almeno io mi ricordo così, anche se mi sembra un po' strano e senza senso...
> 
> Ovviamente, però, i canali WBD non sono canali prodotti con le piattaforme FAST in mente, quindi le cose cambiano un po'.
> 
> Su questi canali la schermata """""informativa""""" usata come fallback sarebbe il bumper in loop alla quale ti riferivi, ma viene inserita in un modo molto interessante... Invece di essere trasmessa direttamente sul flusso video destinato a TV Plus, diciamo che viene inserita tramite uno "switch". Se eri già sintonizzat* sul canale e parte la pubblicità, avviene questo switch, e il flusso passa da quello "normale" del canale (con la programmazione normale) a quello con il bumper in loop. Poi alla fine ovviamente ritorna quello normale. Se però ti sintonizzi sul canale durante la pubblicità, non avviene nessuno switch e rimane il flusso normale del canale, con la sua solita pubblicità visibile sul DTT, satellite, ecc. Ha molto senso ovviamente, almeno possono mostrare le pubblicità anche se qualcuno si sintonizza durante un'interruzione pubblicitaria, a differenza di tutti gli altri canali TV Plus.
> 
> Come ho già detto, la pubblicità di TV Plus dovrebbe coprire la schermata di fallback, ma essendo inserita tramite software che ovviamente non viene usato nella riproduzione di questi canali da fonti esterne a TV Plus, noi vediamo solo un bumper in loop fino alla fine della pubblicità.
> 
> Spero di essermi spiegato abbastanza bene 😉

Grazie mille, sei stato davvero chiarissimo! Non avendo alcuna piattaforma FAST, non avevo idea di come funzionassero i canali su Samsung TV Plus, adesso ho capito perfettamente. Tra le altre cose, è interessante come il flusso contenente il bumper in loop parta esattamente nello stesso momento dell’inizio della pubblicità, ed è curioso soprattutto in relazione al fatto che i segmenti HLS solitamente hanno una durata di 6 secondi, e che quindi è “strano” pensare che nonostante la durata di un segmento, riescano a switchare tra un flusso e l’altro (e quindi inviare i segmenti del fallback) in perfetta sincronizzazione.
Spero di aver spiegato bene il mio dubbio.
In ogni caso adesso il funzionamento è chiarissimo, ti ringrazio ancora!

**Comment by starhip48** [comment]
> Grazie all'aggiunta dei canali Warner Bros. Discovery su Samsung TV Plus, tutti i canali del gruppo ~tranne Warner TV~ sono visibili **in chiaro**, senza alcun tipo di DRM, **e in 1080p**!
> 
> ### URL Streaming
> [9] NOVE - https://amg16146-wbdi-amg16146c1-samsung-it-1831.playouts.now.amagi.tv/playlist/amg16146-warnerbrosdiscoveryitalia-nove-samsungit/playlist.m3u8 [31] Real Time - https://amg16146-wbdi-amg16146c2-samsung-it-1835.playouts.now.amagi.tv/playlist/amg16146-warnerbrosdiscoveryitalia-realtime-samsungit/playlist.m3u8 [33] Food Network - https://amg16146-wbdi-amg16146c3-samsung-it-1836.playouts.now.amagi.tv/playlist/amg16146-warnerbrosdiscoveryitalia-foodnetwork-samsungit/playlist.m3u8 [37] Warner TV - https://amg16146-wbdi-amg16146c4-samsung-it-1837.playouts.now.amagi.tv/playlist/amg16146-warnerbrosdiscoveryitalia-warnertv-samsungit/playlist.m3u8 [38] Giallo - https://amg16146-wbdi-amg16146c5-samsung-it-1838.playouts.now.amagi.tv/playlist/amg16146-warnerbrosdiscoveryitalia-giallo-samsungit/playlist.m3u8 [41] K2 - https://amg16146-wbdi-amg16146c6-samsung-it-1839.playouts.now.amagi.tv/playlist/amg16146-warnerbrosdiscoveryitalia-k2-samsungit/playlist.m3u8 [44] Frisbee - https://amg16146-wbdi-amg16146c7-samsung-it-1840.playouts.now.amagi.tv/playlist/amg16146-warnerbrosdiscoveryitalia-frisbee-samsungit/playlist.m3u8 [52] DMAX - https://amg16146-wbdi-amg16146c8-samsung-it-1841.playouts.now.amagi.tv/playlist/amg16146-warnerbrosdiscoveryitalia-dmax-samsungit/playlist.m3u8 [56] HGTV - https://amg16146-wbdi-amg16146c9-samsung-it-1842.playouts.now.amagi.tv/playlist/amg16146-warnerbrosdiscoveryitalia-hgtv-samsungit/playlist.m3u8 [59] Motor Trend - https://amg16146-wbdi-amg16146c10-samsung-it-1843.playouts.now.amagi.tv/playlist/amg16146-warnerbrosdiscoveryitalia-motortrend-samsungit/playlist.m3u8

Ciao, scusami se rispondo a questo thread per un off-topic. Da dove hai preso i link di samsung tv plus? ho provato ad estrarli dal sito proprietario ma riesco a visualizzare solo i canali americani con vpn, dall'italia il sito non si apre. Mi interessava prendere i link di Tve la 1 e la 2, prima li avevo presi dalla repo famosa del ragazzo australiano (o neozelandese?) che qualche giorno fa è stata spenta.

**Comment by GiuDiMax** [comment]
Sapete se anche il canale Discovery è disponibile su samsung tv plus? ho visto sul loro sito che ora è in chiaro

**Comment by FrancescoRosi** [comment]
> Sapete se anche il canale Discovery è disponibile su samsung tv plus? ho visto sul loro sito che ora è in chiaro

Non ancora, però quando arriverà sul DTT in autunno (https://discoverychannel.it/discovery-channel-debutta-in-chiaro) probabilmente arriverà anche su TV Plus :)
