### ISSUE TITLE
[Richiesta Canale] La7 - Url diverso

### ISSUE THREAD

**Issue by comleoita** [Tundrak/IPTV-Italia#169]
Purtroppo alcuni film/programmi che trasmettono su La7 non vengono visualizzati sullo streaming perché, a detta loro, non hanno i diritti per la trasmissione. Per questo ho trovato, da TV Timvision, un link pulito senza DRM (uno dei pochi ancora rimasti) che ovvia il problema.
Il link è:

`https://d3749synfikwkv.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-74ylxpgd78bpb/Live.m3u8`

Spero possa essere utile.

**Comment by Tundrak** [comment]
Ciao e grazie per la segnalazione, non mi ero mai accorto di questo problema (mettono un messaggio al posto del programma durante la riproduzione?)
Non è che per caso riusciresti a ottenere anche un link per LA7d? A questo punto immagino che sia affetto dallo stesso problema e mi dispiacerebbe avere due link spaiati

**Comment by comleoita** [comment]
Si, mettono un cartello con il logo di La7.it a sinistra e poi scrivono che non hanno i diritti per lo streaming, simile a quello che succede con la rai.
Purtroppo ho provato diverse volte ma il link di la7d ha i DRM e quindi non funzionerebbe…

**Comment by Tundrak** [comment]
Il nuovo link è stato aggiunto alla lista nella nuova [Release Gennaio 2024](https://github.com/Tundrak/IPTV-Italia/releases/tag/v01-2024)!
