### ISSUE TITLE
[Problema] Mediaset estero

### ISSUE THREAD

**Issue by carinside** [Tundrak/IPTV-Italia#17]
Buongiorno,

è possibile inserire nella lista dei flussi dei canali mediaset visibili anche dall'estero?

Purtroppo da qualche tempo non sono più in grado di visualizzarli all'estero. Non mi piace usare VPN, quindi voi siete la mia unica speranza :)

Grazie mille in ogni caso

**Comment by subzeero81** [comment]
Ciao, 
grazie. nessuno di quei link funziona all'estero.
però da questo sito, dopo aver cliccato su canale 5 riesco a vederlo all'estero. Ho visto che la url è molto simile a quelle che mi hai inviato. Forse tu riesci a recuperarlo e inserirlo nella tua magnifica lista

Il sito è questo:

https://photocall.tv/ -> internacional -> logo mediaset -> canale 5

Spero di esseri di aiuto.

Buona serata

**Comment by Tundrak** [comment]
Purtroppo controllando il sito i link sono come questo:
http://live2t.msf.cdn.mediaset.net/Content/hls_h0_clr_vos/live/channel(c5)/index.m3u8
Però non funzionano neanche in Italia da soli perchè usano un token per l'autenticazione, quindi non posso aggiungerli :/
Mi dispiace
