### ISSUE TITLE
Problema Rai 4k

### ISSUE THREAD

**Issue by mariorossi05** [Tundrak/IPTV-Italia#170]
**Canale TV / Radio interessato**
Rai 4k (in tutte le liste)

**Descrivi il problema**
Non riesco a riprodurre il canale

**Informazioni sul dispositivo**
 - Tipo di dispositivo: Android
 - Programma utilizzato: Kodi
 - Versione lista: dicembre 2023

**Comment by Tundrak** [comment]
E' vero, Rai 4K non funziona più
Cercherò di trovare una soluzione, anche se potrebbero aver proibito per sempre la riproduzione senza DRM

**Comment by FrancescoRosi** [comment]
> E' vero, Rai 4K non funziona più
Cercherò di trovare una soluzione, anche se potrebbero aver proibito per sempre la riproduzione senza DRM

Sembra non funzionare anche con il DRM. Ho estratto l'URL mediapolis.rai.it di Rai 4K dall'applicazione HbbTV della Rai (Rai TV+), e ho aggiunto `&output=62` alla fine, così da ricevere una risposta in formato JSON dal server, che oltre a contenere l'URL della stream di Rai 4K contiene anche l'URL per la licenza (Widevine). Anche inserendo l'URL della licenza, però, non riesco a farlo andare. Non so se sto sbagliando qualcosa o se la Rai mi sta boicottando. Ecco il link Mediapolis se qualcun altro vuole provare:
https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=4465258&output=62

**Comment by Tundrak** [comment]
Sicuramente vogliono che la richesta venga fatta a modo loro, usando qualche header speciale, uno user-agent o referer apposito
Mi sa che nella prossima versione della lista Rai 4K non ci sarà :(

**Comment by comleoita** [comment]
> > E' vero, Rai 4K non funziona più
> > Cercherò di trovare una soluzione, anche se potrebbero aver proibito per sempre la riproduzione senza DRM
> 
> Sembra non funzionare anche con il DRM. Ho estratto l'URL mediapolis.rai.it di Rai 4K dall'applicazione HbbTV della Rai (Rai TV+), e ho aggiunto `&output=62` alla fine, così da ricevere una risposta in formato JSON dal server, che oltre a contenere l'URL della stream di Rai 4K contiene anche l'URL per la licenza (Widevine). Anche inserendo l'URL della licenza, però, non riesco a farlo andare. Non so se sto sbagliando qualcosa o se la Rai mi sta boicottando. Ecco il link Mediapolis se qualcun altro vuole provare: https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=4465258&output=62

Puoi ricevere due tipi di licenza, se alla fine del link metti ‘&forceuseragent=chrome’ trovi il link a widevine se metti hbbtv al posto di chrome trovi playready.
Il link non funziona perché il token che trovi dopo authorization lo devi mettere come header-> nv-authorizations: il token che hai trovato.

La richiesta poi la devi mandare via post al link pulito senza parametri.

**Comment by FrancescoRosi** [comment]
Rai 4K si può vedere nuovamente senza DRM o parametri strani (per adesso), si può riaggiungere?
https://raievent10-dash-live.akamaized.net/dash/live/664000/raievent10/manifest.mpd

P.S. Speriamo che rimanga così fino alla fine di Sanremo :D

**Comment by Tundrak** [comment]
Me ne sono accorto, Rai 4k tornerà presto nella lista.
La prossima volta devo aspettare di più prima di rimuovere un link

**Comment by Tundrak** [comment]
Pubblicata la nuova release [Versione Marzo 2024](https://github.com/Tundrak/IPTV-Italia/releases/tag/v03-2024) che contiene nuovamente Rai 4K (link formato m3u8)!
