### ISSUE TITLE
[Problema] segnalo canali Mediaset in loop continuo solo sulla lista auto aggiornante mente su lista scaricabile (HLS) TUTTO OK 

### ISSUE THREAD

**Issue by ztony91** [Tundrak/IPTV-Italia#175]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)

**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]
 - Programma utilizzato [es. VLC, Potplayer]
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by Tundrak** [comment]
Probabilmente è dovuto al player che usi, io ho provato con diversi e funziona tranquillamente
Se con l'altra non hai problemi usa quella

**Comment by ztony91** [comment]
Buonasera Grazie per la risposta Potresti consigliarmi un player che li legga correttamente?Sent from Android deviceIl 10 gen 2024 20:48, Tundrak ***@***.***> ha scritto:
Probabilmente è dovuto al player che usi, io ho provato con diversi e funziona tranquillamente
Se con l'altra non hai problemi usa quella

**Comment by ztony91** [comment]
Il problema  non c'è più adesso vanno come prima 👍♥️
