### ISSUE TITLE
[Problema] La Rai è andata!

### ISSUE THREAD

**Issue by micheleciondolo** [Tundrak/IPTV-Italia#178]
La rai non funziona più, irragiungibile da oggi pomeriggio credo

**Comment by Trifone46** [comment]
Strano che non ti funzionano io non sto riscontrando nessun problema con la rai

**Comment by micheleciondolo** [comment]
Grazie della risposta. Tu che player usi?  Non danno segni di vita Rai1, Rai 2 e Rai3

**Comment by Tundrak** [comment]
Potrebbe essere colpa di un aggiornamento rilasciato per il player che usi, perchè i canali si vedono tranquillamente
Come guardi la lista? Puoi provare con un altro player?

**Comment by micheleciondolo** [comment]
io usavo su ben 3 dispositivi l'applicazione M3U player. 
Al momento mi sembra funzionare solo tivimate.. Ma se non hai la versione pro è completamente inutile.
Non so cosa sia cambiato in questi giorni.

**Comment by Tundrak** [comment]
Non so
Sul mio computer Windows funzionano su Potplayer, VLC e anche Kodi 20.3 (con IPTV Simple Client e [questi accorgimenti](https://github.com/Tundrak/IPTV-Italia/issues/36#issuecomment-1003741371))
Su Android ho avuto fortuna con [Televizo](https://televizo.net) anche se non è disponibile sul Play Store

**Comment by micheleciondolo** [comment]
> Non so Sul mio computer Windows funzionano su Potplayer, VLC e anche Kodi 20.3 (con IPTV Simple Client e [questi accorgimenti](https://github.com/Tundrak/IPTV-Italia/issues/36#issuecomment-1003741371)) Su Android ho avuto fortuna con [Televizo](https://televizo.net) anche se non è disponibile sul Play Store

Grazie mille della risposta!
Considera che è assurdo. L'unico free che trovavo su android tv senza ads era questo "M3U IPTV". Funzionava alla perfezione sia su Android tv che su smartphone android. All'improvviso ha smesso di funzionare la rai su entrambi.
Inoltre su linux, non funziona né VLC né Kodi, sarà questione di sistema operativo. (parlo solo della rai). 

Ad ogni modo grazie! Avevo già individuato televizo e tivimate come valide alternative in cui funzionava tutto! Da stasera uso Televizo :)
Puoi chiudere la segnalazione!
