### ISSUE TITLE
[Problema] La5 non si vede

### ISSUE THREAD

**Issue by Ilpity** [Tundrak/IPTV-Italia#179]
Canale la5

**Descrivi il problema** 
Il canale presenta l'audio ma non le immagini 

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [Smart TV]
 - Programma utilizzato [iptv]
 - Versione lista [es. v04-2021]

**Comment by Tundrak** [comment]
Solo La5 e nessun altro canale Mediaset? Che strano
Che app iptv usi in specifico?
