### ISSUE TITLE
Rai1 Rai2 Rai3 non accessibili, file gennaio #0#4

### ISSUE THREAD

**Issue by carloreggiani** [Tundrak/IPTV-Italia#180]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)

**Descrivi il problema**
Sto provando su Android con l'App Web Video. Aster e il file iptvitaplus.v01-2024.HLS.m3u e Chromecast 4K: vedo tutti i canali esclusi i 3 RAI.

Problema noto?

Grazie!
Cadlo

**Comment by Tundrak** [comment]
Purtroppo sì, se ne è parlato nell'Issue #89 (con una "soluzione" per niente comoda)
L'unico consiglio che posso dare è di provare un'altra app: [Televizo](https://televizo.net) funziona, ma non permette il casting diretto (puoi comunque fare il casting di tutto lo schermo in altri modi)
