### ISSUE TITLE
La 5 canale 30 dt non funziona.quale lettore è da usare per la riproduzione? Grazie mille!

### ISSUE THREAD

**Issue by Domenicoarmeni2** [Tundrak/IPTV-Italia#181]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)

**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]
 - Programma utilizzato [es. VLC, Potplayer]
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by Domenicoarmeni2** [comment]
Tablet e smartphone

**Comment by Tundrak** [comment]
Ciao!
Mi dispiace che il tuo player non riesca a riprodurre certi canali
Su Android puoi usare [Televizo](https://televizo.net) che funziona con tutti i canali, anche se non è disponibile sul Play Store

**Comment by Domenicoarmeni2** [comment]
Grazie mille!!!
Funziona
Ma come faccio a scaricare epg?
Un caro saluto


Il Ven 2 Feb 2024, 20:16 Tundrak ***@***.***> ha scritto:

**Comment by Tundrak** [comment]
Sono contento che funzioni!
Io personalmente non fornisco EPG ma so che quello a questo link funziona: https://www.epgitalia.tv/gzip
Nell'app lo puoi aggiungere da Impostazioni > Guida ai programmi > Tasto + e poi inserisci il link nel campo "Collegamento all'EPG

**Comment by Domenicoarmeni2** [comment]
Grazie mille per la tua disponibilità e gentilezza.
Un caro saluto.
D.A.


Il Sab 3 Feb 2024, 19:10 Tundrak ***@***.***> ha scritto:
