### ISSUE TITLE
[Problema]

### ISSUE THREAD

**Issue by hackwing34** [Tundrak/IPTV-Italia#182]
**RAI  1-2-3-4.../ Radio interessato**
Quale canale TV? RAI  1-2-3-4...   / Radio ha il problema che vuoi descrivere? RAI? (È regionale?)

**Descrivi il problema**
DOPO UN LUNGO CRAICAMENTO IL CANALE NON FUNZIONA

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]
 - Programma utilizzato [M3U player]
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by Tundrak** [comment]
Purtroppo i canali Rai sono schizzinosi e non funzionano con tutte le app.
Posso solo consigliare di cambiare: so che [Televizo](https://televizo.net) funziona bene, anche se non è sul Play Store
