### ISSUE TITLE
[Problema]

### ISSUE THREAD

**Issue by armandoi75** [Tundrak/IPTV-Italia#185]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)
Non si vedono Canale 5, Italia 1 e Rete 4

**Comment by Tundrak** [comment]
Ciao, scusa per il (grande) ritardo
Se sei ancora interessato, posso avere qualche informazione in più sul tuo dispositivo? Che programma usi per guardare la lista?
