### ISSUE TITLE
[Problema] rai non e 19200 1080

### ISSUE THREAD

**Issue by Artakart** [Tundrak/IPTV-Italia#186]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)

**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]
 - Programma utilizzato [es. VLC, Potplayer]
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by Trifone46** [comment]
Buon giorno ho trovato dei link riguardo Rai 1 e Rai 2 la risoluzione e di 1920x1080 piu superiore rispetto ai link attualmente presenti nella lista aggiornata nel mese gennaio 2024  li posto qui in caso che qualcuno sia interessato a questi link

https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=7&forceUserAgent=raiplayappletv ( Rai 1 )

http://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=308718&output=7&forceUserAgent=raiplayappletv ( Rai 2 )

**Comment by Artakart** [comment]
Buon Giorno rai non e Full Hd, invece Mediaset full hd, Calanli do Rai 1080 720

**Comment by Artakart** [comment]
Buon Giorno rai non e Full Hd, invece Mediaset full hd, Calanli do Rai 1080 720, e non ce rai uno due tre full hd m3u orm3u8?, questi due non funziona

**Comment by Trifone46** [comment]
Salve a tutt gli ho riprovati funzionano se li aprite con un lettore tipo mx player e andate su strumenti e poi prorieta vedrete che sono con la risoluzione che vi ho indicato

**Comment by Artakart** [comment]
So how capito, io cerco playlist m3u full hd ho 4k grazie

**Comment by Tundrak** [comment]
Grazie @Trifone46 per la scoperta
Sicuramente nella prossima versione della lista aggiungerò quella variante dei link :)

**Comment by Nostradamus1973** [comment]
> Buon giorno ho trovato dei link riguardo Rai 1 e Rai 2 la risoluzione e di 1920x1080 piu superiore rispetto ai link attualmente presenti nella lista aggiornata nel mese gennaio 2024 li posto qui in caso che qualcuno sia interessato a questi link
> 
> https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=7&forceUserAgent=raiplayappletv ( Rai 1 )
> 
> http://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=308718&output=7&forceUserAgent=raiplayappletv ( Rai 2 )

Buongiorno,
Volevo pubblicare un aggiornamento. Ricevo un errore 403 per questi flussi.
Grazie e buona giornata.

**Comment by Artakart** [comment]
Grazie mille, ma non è in formato m3u?

**Comment by Tundrak** [comment]
Pubblicata la nuova release [Versione Marzo 2024](https://github.com/Tundrak/IPTV-Italia/releases/tag/v03-2024) con il supporto alla risoluzione 1920x1080 per i canali che la supportano!
