### ISSUE TITLE
Informazioni Canali

### ISSUE THREAD

**Issue by aviscuso20** [Tundrak/IPTV-Italia#191]
Ciao a tutti, volevo chiedere se anche ad altri come me usano Kodi per la playlist e non hanno nessuna informazione dei programmi su nessun canale, grazie

**Comment by Tundrak** [comment]
Ciao!
E' normale che le informazioni non vengano aggiunte automaticamente perchè non ne fornisco (in realtà non so se sia possibile aggiungere il riferimento dentro il ifle m3u che fornisco)
Tuttavia è ababstanza facile aggiungerle (se usi l'addon IPTV Simple Client): basta andare su Impostazioni (la ruota dentata) > Add-ons > My add-ons > PVR Clients > IPTV Simple Client > Configure > La voce con scritto Enabled o Abilitato > Scheda EPG > dentro XMLTV URL inserisci questo: http://www.epgitalia.tv/gzip > OK
Spero di essere stato chiaro

**Comment by aviscuso20** [comment]
ok ho afferrato... grazie mille della risposta e dell aiuto..ti farò sapere se funziona!

**Comment by ferrum** [comment]
Ciao, innanzitutto grazie per il tuo impegno nel mantenere questa repository. Perché non pinni il link EPG nella homepage così è di più facile accesso? :)
Comunque non so se è un problema mio ma non funziona, ovverosia non vedo alcuna informazione sul canale nonostante io inserisca quel link nell'apposito menu... 

Edit: risolto. Il problema è il numero del canale tra parentesi quadre presente nella lista m3u. Ho aperto il ticket #224 per maggiori info.
