### ISSUE TITLE
[Richiesta Canale] Supertennis

### ISSUE THREAD

**Issue by gcpmusic** [Tundrak/IPTV-Italia#192]
**Canale Richiesto**
Supertennis / Supertennix

**URL Streaming**
https://www.supertennis.tv/live-streaming

**Comment by Tundrak** [comment]
E' vero, il link corrente ha smesso di funzionare.
Nella prossima lista aggiungerò la versione aggiornata, nel frattempo se vuoi cambiare subito ecco il link funzionante: https://live-embed.supertennix.hiway.media/restreamer/supertennix_client/gpu-a-c0-16/restreamer/rtmp/hls/h24_supertennix/manifest.m3u8

**Comment by Trifone46** [comment]
Buona sera segnalato il nuovo link di Sportitalia https://di-kzbhv8pw.vo.lswcdn.net/sportitalia/sihd/playlist.m3u8 quello attualmente presente nella lista di gennaio 2024 non va piu

**Comment by Tundrak** [comment]
Pubblicata la nuova release [Versione Marzo 2024](https://github.com/Tundrak/IPTV-Italia/releases/tag/v03-2024) con il nuovo link di Supertennis!
