### ISSUE TITLE
[Problema] Rai 1 non funzionante

### ISSUE THREAD

**Issue by totalcaoos** [Tundrak/IPTV-Italia#194]
Buongiorno, vi risulta anche a voi rai 1 non funzionante o solo un mio problema, grazie.

**Comment by Trifone46** [comment]
Ciao strano che non ti funziona io non ho problemi si vede

**Comment by GianlucaRos** [comment]
non funzione nessun canale RAI, gli altri si

**Comment by Trifone46** [comment]
Salve io non sto riscontrando nessun problema con  tutti i canali rai strano che a voi non vanno

**Comment by Tundrak** [comment]
Puoi fornire qualche informazione in più?

Player che funzionano sicuramente sono:
- [PotPlayer](https://potplayer.daum.net) per Windows (o VLC con un po' di fortuna)
- [Televizo](https://play.google.com/store/apps/details?id=com.ottplay.ottplay) per Android

Hai provato l'altra versione della lista? (quelle che finiscono con HLS nella [pagina della release](https://github.com/Tundrak/IPTV-Italia/releases/tag/v01-2024))
Su certi player può risolvere il problema

**Comment by GianlucaRos** [comment]
Ciao,

1. Su PC funziona tutto, sia con VLC che con PotPlayer
2. su smart Android non si vedono i canali RAI ne con VLC ne con MyIPTV, tutti gli altri canali si vedono
3. Ho provato Televizo sempre su Android e li funziona tutto

**Comment by Tundrak** [comment]
Sono contento che tutto funzioni!
EPG è la guida dei canali, può essere utile ma non è necessaria
Se vuoi provarla puoi entrare nelle Impostazioni di Televizo (la ruota dentata) > Guida ai programmi > + > Scrivi un nome e dentro collegamento inserisci questo link http://www.epgitalia.tv/gzip > Spunta

**Comment by GianlucaRos** [comment]
Fatto, funziona anche questo !  EPG praticamente aggiunge sotto ad ogni canale il programma in corso.

Grazie ancora!
