### ISSUE TITLE
[Problema]

### ISSUE THREAD

**Issue by GianlucaRos** [Tundrak/IPTV-Italia#196]
**Canale TV / Radio interessato**

RAI 1, 2, 3, RAI NEWS 24 in entrambe le liste
**Descrivi il problema**
Source error su Android, sia con MyIPTV che con VLC.  Su PC Windows invece si ricevono tutti

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Android su Smasung S20 e S22
 - VLA, MyIPTV, Potplayer
 - Ultime disponibile

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by GianlucaRos** [comment]
Rettifica: su Android non si vede alcun canale RAI (VLC, MyIPTVPlayer) su PC vanno tutti

**Comment by GianlucaRos** [comment]
Confermo: un amico ha appena installato su smart Android MyIPTV e non vede nessun canale RAI, ok gli altri.  I canali RAI al contrario si vedono su PC

**Comment by Tundrak** [comment]
Ciao
VLC è così: su telefono non accetta l'impostazione di un User-Agent personalizzato per cui non funziona niente
L'unico consiglio che posso dare è di provare un'altra app ([Televizo](https://play.google.com/store/apps/details?id=com.ottplay.ottplay) funziona)
