### ISSUE TITLE
Aggiornare lista canali gennaio 2024

### ISSUE THREAD

**Issue by Trifone46** [Tundrak/IPTV-Italia#203]

**Comment by Tundrak** [comment]
Ciao.
I link dei canali che non funzionano verranno sostituiti presto
Per quanto riguarda gli altri, non verranno aggiunti alla lista principale perchè non sono nazionali (non voglio essere scortese, ma mi sembra di averlo detto chiaramente). Se vuoi averli puoi sempre inserirli tu nella tua lista personale

**Comment by Tundrak** [comment]
Pubblicata la nuova release [Versione Marzo 2024](https://github.com/Tundrak/IPTV-Italia/releases/tag/v03-2024) con tutti gli aggiornamenti!
