### ISSUE TITLE
[Richiesta Canale] BLEACH TV Italia canale 4107 Samsung tv plus italia

### ISSUE THREAD

**Issue by cloud90** [Tundrak/IPTV-Italia#204]
**Canale Richiesto**
BLEACH TV Italia canale 4107 Samsung tv plus italia

**URL Streaming**
sono riuscito a sniffare solo l'inizio qualcuno potrebbe aiutarmi a trovarlo completo?

https://amg17293-dynit-amg17293c1-samsung-it-2676.playouts.now.amagi.tv

**Comment by Tundrak** [comment]
Ciao
Il link completo è https://amg17293-dynit-amg17293c1-samsung-it-2676.playouts.now.amagi.tv/playlist/amg17293-dynitsrl-bleach-samsungit/playlist.m3u8

**Comment by starhip48** [comment]
ciao, scusami da dove hai trovato il link del canale su samsung tv plus? non riesco ad aprire il sito da pc senza vpn usa e con quello mi mostra solo i canali americani.
