### ISSUE TITLE
Canali Rai non funzionano

### ISSUE THREAD

**Issue by Trifone46** [Tundrak/IPTV-Italia#205]

**Comment by GianlucaRos** [comment]
Confermo.  Purtroppo anche su Televizo hanno smesso di funzionare, sia su smartphone (Samsung S22) sia si SmartTV (Sony Bravia).  Su SmartTV su KODI, va anche la RAI.  Problema solo con camali RAI

**Comment by Trifone46** [comment]
Attualmente ho trovato solo questi link con estensione manifest.mpd finale se qualcuno riesce a modificarli con estensione HLS.m3u finale e meglio
RAI 3
https://raisportdue1-dash-live.akamaized.net/dash/live/663973/raisportdue1/manifest.mpd
RAI Premium
https://raipremium1-dash-live.akamaized.net/dash/live/663979/raipremium1/manifest.mpd
RAI Movie
https://raimovie1-dash-live.akamaized.net/dash/live/663983/raimovie1/manifest.mpd
RAI Storia
https://raistoria1-dash-live.akamaized.net/dash/live/663959/raistoria1/manifest.mpd

**Comment by Tundrak** [comment]
L'aggiornamento per risolvere il problema sta per arrivare, domani o Sabato con tutti i nuovi link

**Comment by Tundrak** [comment]
Pubblicata la nuova release [Versione Marzo 2024](https://github.com/Tundrak/IPTV-Italia/releases/tag/v03-2024) con tutti gli aggiornamenti!

**Comment by Dell73** [comment]
non funzionano èpiù

**Comment by GianlucaRos** [comment]
su Televizo a me funziona tutto

**Comment by Dell73** [comment]
Io sul PC non mi va,con ott su android va..

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Trifone46** [comment]
Ciao prova a scaricare questo lettore Wiseplay e ottimo legge svariati link quasi di ogni genere e scarica la versione di Marzo 2024

**Comment by Dell73** [comment]
Ok grazie,io per il PC uso un estensione per Chrome

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________
