### ISSUE TITLE
Canali RAI (e solo quelli) non vanno

### ISSUE THREAD

**Issue by GianlucaRos** [Tundrak/IPTV-Italia#206]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)
Tutti i RAI

**Descrivi il problema**
Non si vedono i canali

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [Smart TV e Smartphone
 -  - Programma utilizzato 
 - Televizo
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by Tundrak** [comment]
Duplicato di #205
