### ISSUE TITLE
Canali Rai non funzionanti

### ISSUE THREAD

**Issue by SalvoSpeciale** [Tundrak/IPTV-Italia#207]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)
Rai 1 http://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=16
Rai 2 http://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=308718&output=16
Rai 3 http://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=308709&output=16
**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.
L'ingresso non può essere aperto:
VLC non è in grado di aprire il MRL 'http://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=16'. Controlla il registro per i dettagli.

**Screenshot**
![image](https://github.com/Tundrak/IPTV-Italia/assets/164952544/ea33a24d-f59a-4e5c-b9ec-e925e0cb7b7c)

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]   Notebook, Windows10
 - Programma utilizzato; [es. VLC, Potplayer]   VLC
 - Versione lista [es. v04-2021]    v01-2024 HLS

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by Trifone46** [comment]
Ciao  i  link che ai indicato da stamattina funzionano escusivamente se apri un browser qualsiasi da pc ho da cellulare con altre modalita no e neanche con qualsiasi lettore video

**Comment by Trifone46** [comment]
Ho trovato questo link riguarda Rai 3 HD Ma non ho trovato altro per quanto riguarda altri canali Rai
http://wzstreaming.rai.it/TVlive/liveStream/chunklist_w823540263.m3u8

**Comment by tommyv** [comment]
Try changing the user agent. I had it set on Mozilla and it didn't work until changed to AppleCoreMedia

**Comment by Trifone46** [comment]
Ciao tommyv ho provato a cambiare l agente utente con quello indicato da te e ti confermo che anche a me sono tornati a funzionare bene inoltro ho provato anche effettuare una prova mettendo come agente utente chrome e funzionano bene ma ho impostato come agente utente quello indicato da te Ti ringrazio per la tua collaborazione e per il tuo agliuto

**Comment by Trifone46** [comment]
Ciao tommyv ho provato a cambiare l agente utente con quello indicato da te e ti confermo che anche a me sono tornati a funzionare bene inoltro ho provato anche effettuare una prova mettendo come agente utente chrome e funzionano bene ma sto utilizzando come agente utente quello indicato da te Ti ringrazio per la tua collaborazione e per il tuo agliuto

**Comment by SalvoSpeciale** [comment]
Ciao Tommyv Funziona anche per me. Ho messo una stringa a caso.
Grazie

**Comment by Trifone46** [comment]
Continuo avere problemi con Rai 1 HD Qualcuno di voi sta riscontrando problemi

**Comment by Trifone46** [comment]
Ho notato che riguardo Rai 1 HD e l unico che da problemi usando questo link 
http://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=16 non si vede il resto dei canali Rai vanno bene anche se utilizzio l agente utente consigliato da tommyv non va neanche se utilizzio come agente utente chrome qualcuno riesce a trovare una soluzione .

**Comment by SalvoSpeciale** [comment]
Ciao Trifone.
Un altro problema che ho riscontrato con VLC è il link che deve essere
https:// e non http://...
Aggiusta il link con https  (https://mediapolis.... ) e dovrebbe funzionari
perfettamente

Il mer 27 mar 2024, 11:36 Trifone46 ***@***.***> ha scritto:

**Comment by SalvoSpeciale** [comment]
Ciao Trifone
Come user agent ho usato un nome a caso. Puoi mettere totoepeppino e
funziona

Il mer 27 mar 2024, 11:57 Salvatore Speciale <
***@***.***> ha scritto:

**Comment by Trifone46** [comment]
Ciao SalvoSpeciale ho eseguito il tutto nei minimi dettagli ma non va ti ringrazio per avermi risposto e per aver provato nel  l agliutarmi

**Comment by Trifone46** [comment]
Ho fatto tante verifiche e sono arrivato alla conclusione di avere problemi solo con Rai 1 HD con quel link i restanti canali Rai li vedo bene e non riscontro problemi .

**Comment by tommyv** [comment]
@Trifone46 you can try playing that stream via Streamlink that will pass it to VLC. 
See here https://streamlink.github.io/index.html

Also, are you behind VPN  ?

**Comment by Tundrak** [comment]
Duplicato di #205
