### ISSUE TITLE
user agent da aggiornare

### ISSUE THREAD

**Issue by writetome1** [Tundrak/IPTV-Italia#208]
**Canale TV / Radio interessato**
canali RAI

**Descrivi il problema**
Per la visualizzazione dei canali RAI è necessario utilizzare l'user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0
in sostituzione dell'user agent: Mozilla/5.0

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
Windows 10 - VLC
Android - IPTV 

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by peppelongo96** [comment]
Ciao.
Io uso PVR IPTV Simple client e nulla.
Ho provato sia con questo user agent che quello di Chrome.
Hai altri suggerimenti?

**Comment by Tundrak** [comment]
Duplicato di #205
