### ISSUE TITLE
non vedo i canali Rai su Fermata per android[Problema]

### ISSUE THREAD

**Issue by RotPit** [Tundrak/IPTV-Italia#209]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)

**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]
 - Programma utilizzato [es. VLC, Potplayer]
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by RotPit** [comment]
Canali Rai
Non si vedono i canali e mi dice che non si può aprire il percorso
Fermata con uso per Smartphone (Android auto)
Provato i player a disposizione su Fermata senza esito positivo

**Comment by Tundrak** [comment]
Duplicato di #205
