### ISSUE TITLE
Aggiornamento VLC Lista Canali

### ISSUE THREAD

**Issue by Trifone46** [Tundrak/IPTV-Italia#210]
Aggiornamento Canali Rai per risolvere il problema per chi usa VLC dovete inserire come parte iniziale http:// e dovete mettere come agente utente Mozilla/0.5 non dovreste avere piu problemi io ho fatto così e vedo tutti i canali Rai Riguardo la lista di gennaio 20224 Tundrak deve aggiornarla altrimenti i canali Rai continueranno a non funzionare . La modalita che vi ho indicato lo provata su altri lettori e attualmente non riscontro problemi .

**Comment by Tundrak** [comment]
Hai già aperto un'Issue per questo motivo, segui #205
