### ISSUE TITLE
20 Mediaset protetto da DRM

### ISSUE THREAD

**Issue by giocondo** [Tundrak/IPTV-Italia#24]
**Canale TV / Radio interessato**
20

**Descrivi il problema**
il link non è valido

**Informazioni sul dispositivo**
 - Tipo di dispositivo: PC
 - Programma utilizzato: mpv
 - Versione lista: ultima

**Altre informazioni**
Failed to open https://live3.msf.cdn.mediaset.net/Content/dash_d0_clr_vos/live/channel(lb)/manifest.mpd

**Comment by Tundrak** [comment]
Purtroppo sì, 20 al momento non funziona.
Come ho scritto nelle note dell'ultima [release](https://github.com/Tundrak/IPTV-Italia/releases/tag/v10-2021):
**Attenzione: Il canale 20 di Mediaset non è attualmente visibile, perchè è protetto da DRM. Mantengo comunque il link nel caso Mediaset cambi idea in futuro**.
Non capisco davvero perchè abbiano deciso di proteggere il canale solo adesso, ma lo hanno fatto e io non posso oppormi. Per cui posso solo sperare che rimuovano la DRM, anche se sembra molto improbabile.

**Comment by erkaprone** [comment]
Il problema secondo me è legato al fatto che 20 MEDIASET ha cambiato dimora di emissione dal multiplex La3  al multiplex Mediaset 3 e non più MUX3. Poichè 20 MEDIASET è proprietà Mediaset solo al 40% il restante 60% è del gruppo Television Broadcasting System s.r.l, probabilmente i diritti DRM della quota di maggioranza per l'utilizzo del multiplex Mediaset 3 non sono stati ancora versati dalla s.r.l. berlusconoide. (Fonte https://it.wikipedia.org/wiki/20_(rete_televisiva)) Perciò è solo questione di giorni e poi  sicuramente l'hyperlink cambierà come sono cambiati gli altri canali passando da https://live3**** a  https://live2****. Il termine "live#" identifica il MUX Mediaset.

**Comment by GioPan04** [comment]
Il canale 20 ora funziona correttamente. Testato sia con mpv che con jellyfin (ovviamente con quest'ultimo l'audio non fa, ma è un problema di jellyfin con tutti i canali mediaset)

**Comment by Tundrak** [comment]
Oh, è vero!
Sinceramente non me lo aspettavo, però è successo quindi ne sono contento
Ora posso chiudere l'Issue sperando che il problema non si ripresenti più
