### ISSUE TITLE
[Problema]

### ISSUE THREAD

**Issue by Tanato99** [Tundrak/IPTV-Italia#25]
su canale 5 dopo 1-2 minuti l'audio va in loop.

**Comment by Tundrak** [comment]
Ho controllato e non mi sembra che succeda.
Posso avere più informazioni sul programma che usi per guardare i canali?

**Comment by PowerBoy81** [comment]
Succede anche su Smart TV poiché usano l'estensione manifest.mpd per i flussi anziché .m3u

**Comment by ThomasCarella** [comment]
utilizzo mpv (https://mpv.io/)

**Comment by Tundrak** [comment]
Con l'ultimo aggiornamento tutti i link dei canali Mediaset sono cambiati e il problema sembra non ripetersi più.
Confermi così posso chiudere l'Issue?

**Comment by Tanato99** [comment]
si, grazie.
