### ISSUE TITLE
[Problema] DMAX non funziona

### ISSUE THREAD

**Issue by iitztoss** [Tundrak/IPTV-Italia#26]
**Canale TV / Radio interessato**
DMAX

**Informazioni sul dispositivo**
 - Kodi (Windows Store)
 - Versione lista Ottobre 2021

**Comment by PowerBoy81** [comment]
DMAX
https://sbshdlu5-lh.akamaihd.net/i/sbshdl_5@825063/master.m3u8

**Comment by Tundrak** [comment]
> DMAX
https://sbshdlu5-lh.akamaihd.net/i/sbshdl_5@825063/master.m3u8

Questo è il link all'interno della lista, però sembra che adesso non funzioni solo su alcuni player (come tutti i canali Discovery) :/
Vedrò se posso fare qualcosa o trovare nuovi link

**Comment by Tundrak** [comment]
Non so se sia cambiato qualcosa da parte mia, però ho riprovato adesso e i canali Discovery ora per me funzionano tranquillamente su Kodi
Dimmi se anche tu hai degli sviluppi

**Comment by iitztoss** [comment]
Ormai non uso più la lista, però ho provato e confermo che funziona
