### ISSUE TITLE
PROBLEMA CANALI RAI

### ISSUE THREAD

**Issue by GitAndreaHub** [Tundrak/IPTV-Italia#269]
Ciao, i canali della Rai non si vedono.

**Comment by Trifone46** [comment]
Ciao io non sto riscontrando problemi con i canali Rai si vedono

**Comment by GitAndreaHub** [comment]
Con IPTV EXTREME PRO non li apre su Google TV.

**Comment by Trifone46** [comment]
Io uso iptv PRO li vedo

**Comment by GitAndreaHub** [comment]
Ok non tutte le app funzionano con questa lista…
GSE IPTV funziona! Grazie.
