### ISSUE TITLE
Tracker per Nuova Versione

### ISSUE THREAD

**Issue by PowerBoy81** [Tundrak/IPTV-Italia#27]
**Canale Richiesto**
[19] RADIONORBA TV:
https://play.radionorba.it/#channel=radio-norba-tv

[53] CASA ITALIA 53:
https://casaitalia.tv/streaming-tv/

[203] RAI RADIO 2 VISUAL:
https://www.raiplay.it/dirette/rairadio2

**Comment by Tundrak** [comment]
Ecco i canali che aggiungerò da questa Issue e da #28 (Byoblu ce l'ho messo io) per tenerli tutti insieme:

[58] Rai Sport +
https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=358071
[60] Sportitalia
https://di-kzbhv8pw.vo.lswcdn.net/sportitalia/sihd_480p/chunklist.m3u8
[61] Solocalcio
https://di-kzbhv8pw.vo.lswcdn.net/sportitalia/smil:sisolocalcio.smil/playlist.m3u8
[262] Byoblu
https://09bd1346f7a44cc9ac230cc1cb22ca4f.msvdn.net/live/S39249178/EnTK3KeeN1Eg/playlist.m3u8
[831] RTV SAN MARINO
https://d2hrvno5bw6tg2.cloudfront.net/smrtv-ch01/_definst_/smil:ch-01.smil/playlist.m3u8

Radionorba è già nella lista regionale (regione Puglia), Italia 53 usa token e le due Web TV di Sportitalia non le aggiungo perchè sono Web TV (so che con le radio l'ho fatto, ma mi sembra una cosa diversa)

**Comment by PowerBoy81** [comment]
Per quanto riguarda RAI RADIO 2 VISUAL?
Il Ministero ha già concesso la LCN 203.
Ci sarebbe da aggiungere anche RTL 102.5 NEWS alla LCN 233. Grazie

**Comment by PowerBoy81** [comment]
[68] BOM CHANNEL
Si può estrapolare dalla loro App ufficiale?

https://play.google.com/store/apps/details?id=it.mediastreaming.tvbomchannel

**Comment by Tundrak** [comment]
> [68] BOM CHANNEL

Sinceramente non mi sento di fare tutto quel lavoro per un canale che probabilmente non guarderà quasi nessuno

**Comment by Tundrak** [comment]
Chiedo scusa per la lunga attesa, ma purtroppo è un periodo in cui ho molti impegni importanti, e inoltre ora è spuntata anche #30 ed è giusto lavorare su quella prima di poter rilasciare un aggiornamento

**Comment by Tundrak** [comment]
Aggiunti i canali nella nuova release [Versione Dicembre 2021](https://github.com/Tundrak/IPTV-Italia/releases/tag/v12-2021)!
