### ISSUE TITLE
[Aggiunta Canali]

### ISSUE THREAD

**Issue by PowerBoy81** [Tundrak/IPTV-Italia#28]
[58] RAI SPORT (SD):
https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=358071

[60] SPORTITALIA HD:
https://di-kzbhv8pw.vo.lswcdn.net/sportitalia/sihd_480p/chunklist.m3u8

[61] SPORTITALIA SOLOCALCIO HD:
https://di-kzbhv8pw.vo.lswcdn.net/sportitalia/smil:sisolocalcio.smil/chunklist_b3096000.m3u8

[WEB] SPORTITALIA LIVE 24 HD:
https://di-kzbhv8pw.vo.lswcdn.net/sportitalia/smil:silive24.smil/chunklist_b3096000.m3u8

[WEB] SPORTITALIA MOTORI HD:
https://di-kzbhv8pw.vo.lswcdn.net/sportitalia/smil:simotori.smil/chunklist_b3096000.m3u8

[831] RTV SAN MARINO HD:
https://d2hrvno5bw6tg2.cloudfront.net/smrtv-ch01/_definst_/smil:ch-01.smil/chunklist_b1692000_slita.m3u8

**Comment by Tundrak** [comment]
Chiudo quest'Issue e sposto tutto in #27
