### ISSUE TITLE
[Richiesta Canale]sky

### ISSUE THREAD

**Issue by ivano61qwe** [Tundrak/IPTV-Italia#29]
**Canale Richiesto**
Scrivi il nome completo del canale TV / Radio che vuoi aggiunto in una delle due liste [es. Rai 1]
Se il canale è regionale, specificalo e indica la regione d'appartenenza.

**URL Streaming**
Copia il link del sito internet ufficiale del canale da cui puoi vedere / sentire la diretta. [es. https://www.raiplay.it/dirette/rai1]

**Comment by Tundrak** [comment]
Cosa intendi per "Sky"?
Se parli dei canali come Cielo e TV8, al momento non c'è nessun link diretto (ce n'è uno per TG24)
Se però intendi i canali a pagamento (come quelli di cinema e sport), allora non posso aggiungerli, perchè non sono già disponibili sul digitale terrestre (l'unico modo legale per guardarli è comprare un abbonamento da [loro](https://www.sky.it/offerte))
