### ISSUE TITLE
VLC non riproduce canali Rai

### ISSUE THREAD

**Issue by Utente969** [Tundrak/IPTV-Italia#3]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere?
I canali Rai non si vedono

**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.
Apro il file con vlc e salta al canale di rete4

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.
No

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]
 - Programma utilizzato [es. VLC, Potplayer]
 - Versione lista [es. v04-2021]
 Uso Vlc su laptop

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.
No

**Comment by Tundrak** [comment]
Controllando, anch'io posso riprodurre il problema :(
Dev'essere cambiato qualcosa da poco con VLC, perchè sono sicuro di aver testato i canali della Rai prima di pubblicare l'ultimo aggiornamento e sugli altri 3 programmi che uso di solito per testare i canali funzionano perfettamente...
Per il momento penso sia meglio aspettare e vedere se la situazione evolve da sola, nel frattempo posso solo consigliarti di scaricare un altro programma, magari anche dedicato solo all'IPTV. Potplayer (il mio lettore video di scelta) non mi ha mai dato grandi problemi
Continuerò a monitorare il problema e a cercare di trovare una soluzione

**Comment by Tundrak** [comment]
Penso di aver trovato la soluzione al problema, ma ho bisogno che tu mi confermi che la soluzione funziona anche per te.
Dovresti scaricare questa lista ridotta di prova ([iptvtest.txt](https://github.com/Tundrak/IPTV-Italia/files/6489536/iptvtest.txt)), rinominarla con estensione .m3u, aprirla e controllare se i canali all'interno funzionano.
Segnalami anche se ti sembra di notare artefatti sullo schermo durante la riproduzione (se avviene).
Grazie per la pazienza e la collaborazione

**Comment by Utente969** [comment]
Ciao,
ho provato gli indirizzi: quelli mediaset okay; per quelli rai ho notato una non sincronia audio-video e non appena compare il video anche degli artefatti sulla meta bassa dello schermo che tendono a ridursi notevolmente con il passare dei secondi.

**Comment by Tundrak** [comment]
Sono contento che ora i canali si riescano almeno a vedere :)
Per quanto riguarda il problema audio, come consigliato in #5 puoi impostare un delay all'audio, su VLC puoi farlo velocemente con la tastiera con i tasti "j" (per anticipare) e "k" (per ritardare).
Purtroppo non so quanto possa fare per migliorare il video, in quanto altri player lo riproducono perfettamente, però per il momento non chiuderò l'Issue.
Appena posso (in queste settimane ho impegni IRL) caricherò versioni nuove delle playlist con i link corretti e cambierò la documentazione per scoraggiare l'uso di VLC.

**Comment by Tundrak** [comment]
Ciao!
So che l'Issue è davvero vecchia e magari non stai usando neanche più questa lista, ma stavo dando un'occhiata ai problemi più datati e, con tutti gli aggiornamenti in questi anni e soprattutto con i nuovi cambiamenti da #109 nell'ultima [Versione Giugno 2023](https://github.com/Tundrak/IPTV-Italia/releases/tag/v06-2023), spero di aver migliorato l'esperienza per gli utenti di VLC (io non ho più grandi problemi nella riproduzione di nessun canale). Per questo, chiudo l'Issue.
