### ISSUE TITLE
[Richiesta Canale] Supertennis

### ISSUE THREAD

**Issue by cloudsnake7** [Tundrak/IPTV-Italia#31]
**Canale Richiesto**
Supertennis, canale 64 (nazionale)

**URL Streaming**
https://www.supertennis.tv/live-streaming

**Comment by Tundrak** [comment]
Il link sarebbe questo, ma non ha un'estensione e diversi player non lo riconoscono:
https://eclexiafitms.streaming.mediaservices.windows.net/d4647546-f787-4cd1-a0a1-9d9c492c5bc0/f60ccca6-cca6-4bf8-b65d-47ceb9b3bbe9.ism/manifest(format=mpd-time-csf)
Non so se aggiungerlo comunque

**Comment by cloudsnake7** [comment]
Grazie per la risposta! Si tratta del canale in chiaro degli appassionati di tennis, sarebbe una grande aggiunta!

**Comment by Tundrak** [comment]
Di questo non ho dubbio, ho soltanto paura di ricevere Issue più in là perchè qualcuno non riesce a vederlo (per esempio, PotPlayer non lo riproduce)
Però immagino che sia giusto aggiungerlo comunque per chi può vederlo
