### ISSUE TITLE
[Problema] Topcrime has not worked for 2 days

### ISSUE THREAD

**Issue by Gm1977** [Tundrak/IPTV-Italia#32]
**Canale TV / Radio interessato**
canale TV  Topcrime

**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.
Topcrime has not worked for 2 days

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo:
 -  Computer Windows 11 64 bit

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by Gm1977** [comment]
also no longer works, network 4, channel 5, Italy 1, Italy 2
![Screenshot (1)](https://user-images.githubusercontent.com/32224120/146499984-3f5d9e66-d32e-4f53-a02a-d2bd695bd8b7.png)

**Comment by Gm1977** [comment]
also no longer works, network 4, channel 5, Italy 1, Italy 2

**Comment by Tundrak** [comment]
Oh, you're using Kodi.
Could you tell me which addon you use to watch the list?

**Comment by Gm1977** [comment]
PVR IPTV Simple Client
ᐧ

Il giorno ven 17 dic 2021 alle ore 18:22 Tundrak ***@***.***>
ha scritto:

**Comment by Gm1977** [comment]
PVR IPTV Simple Client

**Comment by Tundrak** [comment]
I may have found a solution.
Try to:
Get to the settings by clicking the Settings cog icon -> Addons -> My Addons -> PVR clients -> PVR IPTV Simple Client -> Configure
Click the cog on the bottom left until it says "Expert"
Open the Advanced Tab
Change User-Agent to "Mozilla/5.0" as in the picture then exit with OK twice
![image](https://user-images.githubusercontent.com/77153792/146649226-4727a355-d87c-4c18-a1ef-4cfc984886d0.png)

**Comment by Gm1977** [comment]
Good problem solved all channels work thank you very much

**Comment by Gm1977** [comment]
Good problem solved all channels work

thank you very much
Gabriel
ᐧ

Il giorno sab 18 dic 2021 alle ore 17:55 Tundrak ***@***.***>
ha scritto:
