### ISSUE TITLE
[Problema] I canali Rai saltano dopo circa 60 secondi

### ISSUE THREAD

**Issue by cloudsnake7** [Tundrak/IPTV-Italia#36]
**Canale TV / Radio interessato**
Canali Rai

**Descrivi il problema**
Dopo circa 60 secondi, lo streaming si interrompe e il programma (nel mio caso Kodi) mi riporta alla lista canali.

**Screenshot**
-

**Informazioni sul dispositivo**
 - Tipo di dispositivo: sia da smartphone che da smart box
 - Programma utilizzato Kodi
 - Versione lista: dicembre 2021

**Altre informazioni**
-

**Comment by ilmich** [comment]
Ciao,

che versione di Kodi utilizzi!? Perchè la versione dell'addond iptv per kodi 9.2 fa abbastanza schifo rispetto a quelle piu' moderni (non supporta il protocollo dash... se c'e' un calo di banda si inchioda & so on)

**Comment by cloudsnake7** [comment]
Ciao e grazie per la risposta!
Utilizzo Kodi v19.3.0, dovrebbe essere l'ultima scaricabile.

**Comment by ilmich** [comment]
Non ti posso aiutare operativamente perchè la mia versione di Kodi è la 18.
Ad ogni modo se utilizzi l'addon iptvsimple la documentazione ufficiale

https://github.com/kodi-pvr/pvr.iptvsimple/blob/Matrix/README.md

è abbastanza decente e dovresti riuscire a settare qualche opzione migliorativa (tipo utilizzare come 'lettore' input un addon chiamato inputstream.adaptive)
Fra l'altro ho scoperto che ha un sacco di funzioni carine (tipo il timeshift) e supporta finalmente il protocollo MPEG/DASH (che sostanzialmente rispetto alle liste m3u8 attuali ti consente di 'gestire' la qualità in base alla velocità di connessione e quindi gestisce meglio i cali di rete)
Magari @Tundrak  potrebbe creare una lista ad-hoc per kodi

**Comment by Tundrak** [comment]
La soluzione per questo problema sembra proprio usare inputstream.adaptive
Prova ad attivarlo da Impostazioni > Addons > My Addons > PVR Clients > PVR IPTV Simple Client > Configure > Premi l'ingranaggio finchè non diventa Expert > scheda Advanced > Use inputstream.adaptive e controlla se funziona
> Magari @Tundrak potrebbe creare una lista ad-hoc per kodi

Mi sembra un po' esagerato :D, però dalla documentazione pare che si possano usare linee con l'header #KODIPROP per imporre opzioni particolari, per cui vedrò se posso aggiungere quelle dato che lo sto già facendo per VLC

**Comment by cloudsnake7** [comment]
Grazie ragazzi, vi confermo che funziona alla grande!

**Comment by illtellyoulater** [comment]
Confermo anch'io, grazie @ilmich e @Tundrak !
