### ISSUE TITLE
Byoblu

### ISSUE THREAD

**Issue by ono-sendai-san** [Tundrak/IPTV-Italia#37]
**Canale TV / Radio interessato**
Byoblu.com

**Descrivi il problema**
https://www.newsguardtech.com/it/special-reports/special-report-un-bilancio-del-2021/

**Altre informazioni**
Già l'informazione in Italia è quella che è, perchè aggiungere palese disinformazione?
Allunaggio, Torri gemelle, scie chimiche, vaccini e autismo, Covid. What's next?
C'era proprio bisogno di avere questo canale nella lista?

**Comment by Tundrak** [comment]
L'ho aggiunto senza pensarci più di tanto e non mi era mai occorso che fosse così "anticonformista"
Probabilmente mi fidavo di più della TV italiana :)
Immagino che lo rimuoverò nella prossima release, ma non è una cosa ad altissima priorità per cui potrà volerci del tempo mentre aspetto altre Issue durante il mese

**Comment by ono-sendai-san** [comment]
Grazie per la risposta e scusa se sono stato rude.
Ho visto video di questi _cialtroni_ che paventavano cure domiciliari contro il covid misto complottisimo (ancora in era pre-vaccini) mentre parenti e conoscenti andavano al creatore. Per cui "poco" tollero questi speculatori.
Saluti

**Comment by Tundrak** [comment]
Rimosso nell'ultima release [v01-2022](https://github.com/Tundrak/IPTV-Italia/releases/tag/v01-2022)!

**Comment by finfa** [comment]
Salve.

Sono all'estero, per questo uso questo repository - che lei sia benedetto :)

Ora pero' non posso piu' guadare Byoblu. Grazie ad un individuo che non lo guarda e che "non tollera" [sic] che io ne abbia la possibilita'.

Non aggiungo altro.

**Comment by SimoLRepo** [comment]
> 

Innanzitutto modera termini e atteggiamento, non sei al bar e non discuti con i tuoi amici.

1) Il tuo caro NewsGuard non è attendibile. È criticato dalla stampa giornalistica anti establishment (https://it.wikipedia.org/wiki/NewsGuard#Controversie). Tra l'altro NewsGuard viene finanziata da lobbisti... (https://en.wikipedia.org/wiki/NewsGuard)

2) "palese disinformazione" è una tua opinione. È ovvio che non bisogna credere a tutto ciò che dicono, quantomeno si ha un'altra prospettiva di visione. Poi se preferisci un unico pensiero rimanendo nella tua bolla fai pure...

3) Riguardante "Allunaggio, Torri gemelle, scie chimiche, vaccini e autismo" ByoBlu non ne parla ormai da un pezzo...

4) L'affermazione "cialtroni" è diffamatoria...

5) Se "poco tolleri questi speculatori" sono fatti tuoi, non è obbligatorio che guardi quello specifico canale...

6) Le "cure domiciliari" esistono realmente, dovresti informarti meglio.

7) L'affermazione "ancora in era pre-vaccini" mi fa presupporre che tu ti affida ciecamente a questi farmaci con fine sperimentazione 2024 (fonte: clinicaltrials.gov). Siamo già arrivati alla 4ª dose... Inoltre la Svezia ha avuto molti meno morti a causa del COVID (Sars-CoV-2) rispetto ad altri paesi che hanno fatto tra l'altro vari lockdown, e non c'erano ancora vaccini. Inoltre fino ad ora il livello di infezione e pressoché invariato...

Quindi non sei autorizzato a dare ordini di rimozione...

**Comment by sfiorini** [comment]
For the reasons in this post, I have forked this repository a few months ago and created one in which I am accepting all requests no matter the political or religious believes. I have included Byoblu, although I personally do not watch it. My repo is: https://github.com/sfiorini/IPTV-Italy

Feel free to send channel requests with working links.

Thanks, Stefano
