### ISSUE TITLE
[Problema]

### ISSUE THREAD

**Issue by Arduro** [Tundrak/IPTV-Italia#39]
Salve

Il player che ho sulla Fire Tv Stick (Siptv) non è in grado di leggere flussi multipli ad esempio quelli della Rai o Mediaset dove ci sono vari formati video, es. 1280x720, 1024x576,  pertanto chiedo come posso recuperare il sigolo flusso video/audio ad esempio dal flusso Rai https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803

Grazie in anticipo

**Comment by Filippo-Marcel-Lisuzzo** [comment]
Interessa anche a me, stesso problema con i canali Rai su Amazon fire stick con Smart Iptv.

**Comment by Tundrak** [comment]
Purtroppo per i canali Rai i link singoli non funzionano perchè hanno token variabili, e l'unico modo per ottenerli (che io sappia) è usare il link di mediapolis.rai.it.
Quelli Mediaset si possono ottenere, però i flussi video sono separati da quelli audio: il formato è
`https://live2-mediaset-it.akamaized.net/content/hls_h0_clr_vos/live/channel(ID)/streamXX/streamPlaylist.m3u8`
sostituendo ad ID il codice del canale (per esempio `c5` per Canale 5) e a XX il codice dello stream secondo questo criterio:
|Canale|Codice Video|Codice Audio|
|-:|:-:|:-:|
|Canale 5|07|08|
|Tutti gli altri|04|05|

Per esempio lo stream video di Italia 1 sarebbe:
`https://live2-mediaset-it.akamaized.net/content/hls_h0_clr_vos/live/channel(i1)/stream04/streamPlaylist.m3u8`
Però l'audio sarà sempre separato, e sarebbe stato così anche per i link Rai.
Se il player che usate non può leggere flussi multipli, non posso dare altro consiglio se non di cambiarlo. Purtroppo non possiedo un Fire TV Stick, per cui non posso dare un consiglio informato.
