### ISSUE TITLE
Radio Norba TV

### ISSUE THREAD

**Issue by Utente969** [Tundrak/IPTV-Italia#4]
**Canale Richiesto**
Scrivi il nome completo del canale TV / Radio che vuoi aggiunto in una delle due liste [es. Rai 1]
Solo canali nazionali verranno accettati.
RadioNorba Tv

**URL Streaming**
Copia il link del sito internet ufficiale del canale da cui puoi vedere / sentire la diretta. [es. https://www.raiplay.it/dirette/rai1]
http:\\flash5.streaming.xdevel.com\radionorbatv\smil:radionorbatv.smil\playlist.m3u8?checkedby:hlscat.com

**Comment by Tundrak** [comment]
Grazie per il contributo!
Purtroppo, essendo il canale non nazionale non posso aggiungerlo alla lista principale.
Tuttavia, sono al lavoro per creare un'altra lista contenente i canali regionali più importanti. Quando la rilascerò (forse ci vorrà un po', voglio essere il più completo possibile), Radio Norba TV sarà sicuramente contenuta!

**Comment by Tundrak** [comment]
Aggiunto il canale nella nuova pre-release [Test Regionale 8](https://github.com/Tundrak/IPTV-Italia/releases/tag/regionale-pre8)!
Scusa per il grande ritardo, ma purtroppo gli impegni sono tanti :)

**Comment by Utente969** [comment]
Bene! Non fa niente. :)
