### ISSUE TITLE
Descrizioni e info canali

### ISSUE THREAD

**Issue by xifi-kif** [Tundrak/IPTV-Italia#40]
Ciao, sarebbe tecnicamente possibile implementare (e nel caso, se posso, come posso contribuire) a implementare le descrizioni dei programmi dei vari canali, tipo: https://www.raiplay.it/guidatv?channel=rai-1&date=12-01-2022
Lo chiedo principalmente per l'implementazione in kodi, ma non so se sia fattibile

**Comment by Tundrak** [comment]
Al momento non intendo aggiungere un epg alla lista, penso che sarebbe necessario troppo lavoro per implementarlo dall'inizio e in modo automatico (e comunque vorrei che questa repository rimanesse focalizzata sui canali in sè).
Ti ringrazio comunque per il pensiero :)
Tuttavia se ti interessa per Kodi conosco un [altro servizio](http://www.epgitalia.tv) **(NON creato o mantenuto da me)** che funziona: per usarlo puoi andare in Impostazioni > Addons > My Addons > PVR Clients > PVR IPTV Simple Client > Configure > Scheda EPG > Assicurati che Location sia impostato su Remote Path > In XMLTV URL inserisci http://www.epgitalia.tv/xml/guide.xml > conferma con OK.  (ci potrebbe volere qualche minuto perchè carichi all'inizio)

**Comment by sfiorini** [comment]
Late to the party...
Prima di tutto grazie per questa playlist. E' la migliore playlist IPTV per la TV Italiana.
Per quanto riguarda la guida, ho usato questa e funziona perfettamente : https://iptv-org.github.io/epg/guides/it/guidatv.sky.it.epg.xml

Ciao,
Stefano
Dallas, TX
