### ISSUE TITLE
HGTV Italy HD

### ISSUE THREAD

**Issue by MarcoViti** [Tundrak/IPTV-Italia#42]
Salve volevo sapere se è possibile avere lo streaming anche di HGTV, qui di seguito allego il link al file per vederlo dal vivo

https://www.discoveryplus.com/it/channel/hgtv?pc=322

Grazie

**Comment by Tundrak** [comment]
Duplicato di #1
Purtroppo i link senza DRM ai canali Discovery che non sono già aggiunti sembrano introvabili, appena li avrò li caricherò subito ma non so quando questo potrebbe succedere.
