### ISSUE TITLE
[Problema] Tvheadend e formato M3U

### ISSUE THREAD

**Issue by robustini** [Tundrak/IPTV-Italia#46]
Grazie in primis per la preziosa lista!
Sto notando un problema con Tvheadend, prende i dati corretti solo di tre canali, ed ho notato la differenza.
Quelli che importa correttamente iniziano con:

#EXTINF:-1

Quelli errati:

#EXTINF:-1,

Per me è un attimo rimuovere la virgola, ma siccome punto diretto alla tua lista ti dispiacerebbe correggere quel problema?
Grazie!

**Comment by Tundrak** [comment]
Grazie per la segnalazione!
Presto rilascerò la nuova versione contenente anche questo miglioramento

**Comment by Tundrak** [comment]
Rimosse le virgole nell'ultima release [v01-2022](https://github.com/Tundrak/IPTV-Italia/releases/tag/v01-2022)!
Attento al nuovo link autoaggiornante!
