### ISSUE TITLE
Non funzionano ne mediaset ne rai itala

### ISSUE THREAD

**Issue by Maik331** [Tundrak/IPTV-Italia#48]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)

**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]
 - Programma utilizzato [es. VLC, Potplayer]
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.
[T](https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803)

**Comment by Tundrak** [comment]
Ora vedo qual è il problema, però non ho ancora abbastanza informazioni per provare a risolverlo.
Puoi scrivere più informazioni (come il nome del programma o dell'app che usi, oppure il tuo dispositivo) qui sotto?
Da me tutti i canali funzionano correttamente

**Comment by Maik331** [comment]
Canale 5 Rete 4 italia1 cine 34 Geo bloccato
Il mio dispositivo android

Il Mer 2 Feb 2022, 18:55 Tundrak ***@***.***> ha scritto:

**Comment by Tundrak** [comment]
Sei in territorio italiano?
Perchè già in #17 veniva riportato che i canali Mediaset erano bloccati fuori dall'Italia, e purtroppo io non posso farci niente.

**Comment by micelf01** [comment]
Io sono nel UK, e funziona tutto bene. Grazie
