### ISSUE TITLE
[Problema] Canali Rai

### ISSUE THREAD

**Issue by MarkPorty** [Tundrak/IPTV-Italia#5]
Ciao, sembra che i canali rai 1,2 e 3 non siano presenti.

Grazie per il tuo tempo

**Comment by Tundrak** [comment]
Domanda: Stai per caso usando VLC per guardare i canali?
Se sì, allora quest'Issue è un duplicato di #3 e sto lavorando per risolverla, visto che ho capito qual è il problema.

**Comment by MarkPorty** [comment]
Grazie per la risposta, in realtà uso l'app Fermata Auto per Android Auto.



Il dom 16 mag 2021, 12:32 Tundrak ***@***.***> ha scritto:

**Comment by Tundrak** [comment]
Capisco.
Tuttavia il problema potrebbe comunque essere riconducibile a VLC, visto che è uno dei player inclusi nell'app.
Guardando le release di Fermata, ho notato che nell'ultima versione [1.7.8](https://github.com/AndreyPavlenko/Fermata/releases) è stata proprio introdotta l'opzione che serviva (l'user agent nelle playlist, che coincidenza :D), ma non è molto chiaro il modo in cui si può controllare.
Purtroppo io non possiedo una macchina con Android Auto, quindi la mia unica opzione è chiederti di diventare un beta tester (se per te non è un problema). Dovresti aggiornare l'app all'ultima versione 1.7.8 (se non l'hai già fatto) e provare a cercare un'opzione nelle impostazioni del tipo "User Agent": dovrebbe essere impostata a "Mozilla/5.0" per far funzionare i canali Rai.
Oppure puoi provare a impostare come player VLC invece di quello integrato e usare questa lista test con i primi tre canali modificati (https://ghostbin.co/paste/voak/raw).

Spero nella Tua collaborazione e ringrazio in anticipo

**Comment by MarkPorty** [comment]
Posso darti una mano, nessun problema.
Dammi un tuo riferimento, così da contattarti in privato.
Fermata auto si può usare anche con un apk sul cellulare ma non ho trovato
nessuna impostazioni simile a quella suggerita.
Ho trovato link di rai i 1 e Rai 3 che funzionano

Il dom 16 mag 2021, 17:53 Tundrak ***@***.***> ha scritto:

**Comment by MarkPorty** [comment]
Ho trovato e risolto il problema.
Quando si aggiunge mp3 playlist su Fermata Auto bisogna impostare come nell'immagine.
![Screenshot_2021-05-16-22-45-37-832_me aap fermata auto](https://user-images.githubusercontent.com/84259892/118412113-82c27b80-b698-11eb-8f62-931c991a0dc9.jpg)

**Comment by Tundrak** [comment]
Benissimo!
Adesso i problemi video e audio rimanenti sono uguali a quelli di #3 perchè Fermata usa VLC per riprodurre le dirette.
Chiudo quest'Issue perchè il problema principale è stato risolto, non so quanto sia in mio potere fare per migliorare la qualità video.
Grazie ancora per la collaborazione!
