### ISSUE TITLE
Tv8 e Cielo

### ISSUE THREAD

**Issue by Thove765** [Tundrak/IPTV-Italia#51]
Ciao ho trovato i link (penso) ufficiali di Tv8, Cielo, SkyTg24

I link sono i seguenti:
Tv8:            https://skyanywhere3-i.akamaihd.net/hls/live/510694/mtv8sdlive/stream1/streamLayer.m3u8
?hdntl=exp=1646134371~acl=/*~data=hdntl~hmac=20f8ea78adae257c24df9fa70e4ac9d62f291c2836d84122eff2c7db2204a403
Cielo:         https://skyanywhere3-i.akamaihd.net/hls/live/510693/cielo/stream1/streamPlaylist.m3u8
?hdntl=exp=1646133112~acl=/*~data=hdntl~hmac=ef3885a8b13a0855c99ebbe3d910938d2ce19a7cea785381b1e3a8296f14ed75
SkyTg24:    https://skyanywhere3-i.akamaihd.net/hls/live/510696/tg24/stream1/streamLayer.m3u8
?hdntl=exp=1646137671~acl=/*~data=hdntl~hmac=9198aac313a081c72750d1ef9e34ba5e84190ab6c717388293ac7973139c4a1b

Nei link "stream1" lo puoi sostituire con "stream2". La seconda riga va attaccata alla prima, te li ho spezzati perché me lo copiava male.

Fammi sapere se ti sono utili.

**Comment by Thove765** [comment]
Non so perché ma adesso sopra i link ci sono delle righe

**Comment by Tundrak** [comment]
Ciao!
Purtroppo i link non sono più validi, in quanto il token è scaduto. Purtroppo quelli di Sky sono fatti così );
Grazie comunque per il supporto, sono convinto che un giorno li troveremo
