### ISSUE TITLE
[Richiesta Canale]

### ISSUE THREAD

**Issue by BisiPeter** [Tundrak/IPTV-Italia#53]
**Canale Richiesto**
ByoBlu

**URL Streaming**
https://www.byoblu.com/diretta-tv/

**Comment by francescorosi27** [comment]
#37

**Comment by joeonlist** [comment]
Propongo l'aggiunta di ByoBlu alla lista dei canali.

Ho letto della rimozione di più di un anno fa.
La decisione spetta al maintainer del progetto ovviamente, ma mi permetto di suggerire di riconsiderare la NEUTRALITÀ dello strumento (questo progetto) anteponendola alle opinioni degli utenti circa questo o quel canale. Neutralità che preserva in ogni caso la LIBERTÀ DI NON SINTONIZZARE un certo canale a proprio piacimento. E preserva anche la LIBERTÀ DI TUTTI DI SINTONIZZARE lo stesso canale se lo vogliono.
Colgo l'occasione per ringraziare in ogni caso Tundrak che mantiene il progetto e lo ha condiviso in modo libero. Grazie davvero!


PS.
Segue una mia opinione che va oltre il suggerimento precedente, spero di aver stretto abbastanza...
Semplicemente, come in altre occasioni mi pare sempre preferibile arricchire la pluralità delle voci piuttosto che filtrarle in modo preventivo.
Leggendo l'issue che ne richiedeva la rimozione mi ha stupito già di per sé la pretesa di imporre a tutti una versione impoverita dello strumento sulla base di una personale opinione. E non nascondo che mi abbia stupito soprattutto l'accettazione così a cuor leggero dell'ideatore del progetto:
da chi immagina e condivide con gli altri una così utile facilitazione per visionare canali attraverso la rete in modo veloce efficiente, mi aspetterei una riflessione più ponderata nel distinguere le opinioni degli utenti dalle possibilità "tecniche" che lo strumento in questione può offrire, soprattutto quando questi pretendono di imporre a tutti la censura di una voce (al di là di quello che questa voce abbia da dire).
Al di là dello specifico canale in questione, spero che queste righe possano essere motivo di riflessione. Scusate se l'ho fatta lunga e grazie ancora per la condivisione del progetto. Un saluto!

**Comment by Tundrak** [comment]
Durante tutto questo tempo, ho ripensato alla questione.
Capisco che rimuovendo Byoblu (nonostante sia vero che non sono d'accordo con certe opinioni che trasmette) non ho fatto la cosa giusta, e mi sono lasciato convincere così facilmente a rimuoverlo senza pensare all'idea della lista in generale. Penso che questa lista debba effettivamente essere neutrale, e dovrei essere il primo a cercare di fare in modo che rimanga così.
La prossima volta penserò più attentamente prima di chiudere un'Issue velocemente

Per riassumere, Byoblu è tornato nella nuova [Versione Dicembre 2023](https://github.com/Tundrak/IPTV-Italia/releases/tag/v12-2023), ed è qui per restare (sempre che il link continui a funzionare)
