### ISSUE TITLE
[Problema] Canali Mediaset ( Rete4- Italia1 e Canale 5) usando Jellyfin manca l'audio.

### ISSUE THREAD

**Issue by nzapodege** [Tundrak/IPTV-Italia#56]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)

**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]
 - Programma utilizzato [es. VLC, Potplayer]
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by Tundrak** [comment]
Duplicato di #16
Purtroppo questo problema è già stato riportato, ma non so come potrei risolverlo, anche visto che i link funzionano tranquillamente su ogni altro programma senza modifiche.
Potrei darci un'altra occhiata nei prossimi giorni, ma non sono sicuro di poter fare niente, mi dispiace

**Comment by nzapodege** [comment]
Grazie per la risposta, il problema credo dipenda dal client Jellyfin. Da poco ne hanno rilasciato uno che codifica i canali con MPV videoplayer e con questa soluzione funziona l'audio anche sui canali mediaset. Il problema nasce quando come client utilizzo le app os o android che usano un webplayer generico.

   Da "Tundrak" ***@***.***
   A "Tundrak/IPTV-Italia" ***@***.***
   Cc "nzapodege" ***@***.***,"Author" ***@***.***
   Data Wed, 20 Apr 2022 09:09:59 -0700
   Oggetto Re: [Tundrak/IPTV-Italia] [Problema] Canali Mediaset ( Rete4- Italia1 e Canale 5) usando Jellyfin manca l'audio. (Issue #56)

   Duplicato di #16
   Purtroppo questo problema è già stato riportato, ma non so come potrei risolverlo, anche visto che i link funzionano tranquillamente su ogni altro programma senza modifiche.
   Potrei darci un'altra occhiata nei prossimi giorni, ma non sono sicuro di poter fare niente, mi dispiace

**Comment by AlessandroTischer** [comment]
> Grazie per la risposta, il problema credo dipenda dal client Jellyfin. Da poco ne hanno rilasciato uno che codifica i canali con MPV videoplayer e con questa soluzione funziona l'audio anche sui canali mediaset. Il problema nasce quando come client utilizzo le app os o android che usano un webplayer generico. 

Ciao, io non riesco ad aprire i canali mediaset con jellyfin, da nessun client. Hai avuto anche tu problemi?

**Comment by nzapodege** [comment]
Ciao, da questo link puoi scaricare il player e, attraverso questo codifica l'audio perfettamente. fammi sapere se hai risolto.

   https://github.com/jellyfin/jellyfin-media-player

   Da "AlessandroTischer" ***@***.***
   A "Tundrak/IPTV-Italia" ***@***.***
   Cc "nzapodege" ***@***.***,"Author" ***@***.***
   Data Sun, 18 Feb 2024 15:31:03 -0800
   Oggetto Re: [Tundrak/IPTV-Italia] [Problema] Canali Mediaset ( Rete4- Italia1 e Canale 5) usando Jellyfin manca l'audio. (Issue #56)

     Grazie per la risposta, il problema credo dipenda dal client Jellyfin. Da poco ne hanno rilasciato uno che codifica i canali con MPV videoplayer e con questa soluzione funziona l'audio anche sui canali mediaset. Il problema nasce quando come client utilizzo le app os o android che usano un webplayer generico.

   Ciao, io non riesco ad aprire i canali mediaset con jellyfin, da nessun client. Hai avuto anche tu problemi?

**Comment by nzapodege** [comment]
Ciao, si con questo client funziona solo su Pc\mac, no smartphone o firestick

   Da "AlessandroTischer" ***@***.***
   A "Tundrak/IPTV-Italia" ***@***.***
   Cc "nzapodege" ***@***.***,"Author" ***@***.***
   Data Tue, 20 Feb 2024 23:59:52 -0800
   Oggetto Re: [Tundrak/IPTV-Italia] [Problema] Canali Mediaset ( Rete4- Italia1 e Canale 5) usando Jellyfin manca l'audio. (Issue #56)

     Ciao, da questo link puoi scaricare il player e, attraverso questo codifica l'audio perfettamente. fammi sapere se hai risolto.

     https://github.com/jellyfin/jellyfin-media-player

     Da "AlessandroTischer" @.***
     A "Tundrak/IPTV-Italia" @.***
     Cc "nzapodege" @.,"Author" @.
     Data Sun, 18 Feb 2024 15:31:03 -0800
     Oggetto Re: [Tundrak/IPTV-Italia] [Problema] Canali Mediaset ( Rete4- Italia1 e Canale 5) usando Jellyfin manca l'audio. (Issue #56)
 Grazie per la risposta, il problema credo dipenda dal client Jellyfin. Da poco ne hanno rilasciato uno che codifica i canali con MPV videoplayer e con questa soluzione funziona l'audio anche sui canali mediaset. Il problema nasce quando come client utilizzo le app os o android che usano un webplayer generico.

     Ciao, io non riesco ad aprire i canali mediaset con jellyfin, da nessun client. Hai avuto anche tu problemi?

     —
     Reply to this email directly, view it on GitHub, or unsubscribe.
     You are receiving this because you authored the thread. Message ID: @.***>

   Grazie! Però quindi ti funziona solo da desktop... Nulla da fare se si è da smartphone o smart tv?
