### ISSUE TITLE
[Problema]

### ISSUE THREAD

**Issue by Gifhshady** [Tundrak/IPTV-Italia#59]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)
**M2O canale radio e tv, gli url non funzionano più**
**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]
 - Programma utilizzato [es. VLC, Potplayer]
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by Tundrak** [comment]
Grazie per la segnalazione!
I link sono effettivamente cambiati, ora quello per la tv sembra essere
https://streamcdng31-4c4b867c89244861ac216426883d1ad0.msvdn.net/live/S62628868/uhdWBlkC1AoO/playlist.m3u8
e quello per la radio
https://streamcdng8-4c4b867c89244861ac216426883d1ad0.msvdn.net/radiom2o/radiom2o/master_ma.m3u8
Li scrivo qui in caso tu voglia usarli subito, perchè aspetterò ancora prima di aggiungerli (meglio controllare che non cambino nuovamente). Lo farò quando riesco in quanto devo cambiare diverse altre cose e il tempo libero scarseggia

**Comment by Tundrak** [comment]
So che è passato un po' di tempo, però...
Aggiornato il canale nella nuova release [Versione Luglio 2022](https://github.com/Tundrak/IPTV-Italia/releases/tag/v07-2022)!
