### ISSUE TITLE
[Richiesta Canale] radio tivu azzurra

### ISSUE THREAD

**Issue by MarkPorty** [Tundrak/IPTV-Italia#6]
**Canale Richiesto**
Il canale di chiama Radio Tivu Azzurra ed è intermittente Siciliana con sede s Palermo

**URL Streaming**
TV
https://video.azotosolutions.com:9553/radiotivuazzurralive/radiotivuazzurralive/playlist.m3u8

Radio
https://164.132.178.50:2199/tunein/8022.pls

Sul sito trovi altri link utili qualora abbia sbagliato

https://www.radiotivuazzurra.it/

**Comment by Tundrak** [comment]
Grazie per il contributo!
Il lavoro per i canali regionali è tanto (è incredibile quanti canali cambino anche solo tra due province!), ma mi sto impegnando.
Inoltre, sto cercando di procedere per numero di abitanti nelle regioni, quindi la Sicilia è sicuramente tra le prossime! :)
Tieni monitorato https://github.com/Tundrak/IPTV-Italia/releases per i nuovi aggiornamenti, entro stasera conto di aggiungere i canali del Lazio, poi Campania, Veneto e Sicilia.

**Comment by Tundrak** [comment]
Aggiunto il canale nella nuova pre-release [Test Regionale 5](https://github.com/Tundrak/IPTV-Italia/releases/tag/regionale-pre5)!
