### ISSUE TITLE
[Problema] RealTime

### ISSUE THREAD

**Issue by nicogig** [Tundrak/IPTV-Italia#60]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)

RealTime

**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.

Errore 400 quando provo ad accedere al canale

**Informazioni sul dispositivo**
 - Tipo di dispositivo: Android TV
 - Programma utilizzato: tivimate 
 - Versione lista: Autoaggiornante da GitHub Raw

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by Tundrak** [comment]
Contenuta in #66
