### ISSUE TITLE
[Problema] Food Network

### ISSUE THREAD

**Issue by giuteo** [Tundrak/IPTV-Italia#61]
**Canale TV / Radio interessato**
Food Network 

**Descrivi il problema**
Cambio frequenza "Food Network", non più visibile

**Informazioni sul dispositivo**
 - Tipo di dispositivo: Computer, Smart TV, Smartphone
 - Programma utilizzato VLC, Kodi
 - Versione lista v04-2021

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by Tundrak** [comment]
Contenuta in #66
