### ISSUE TITLE
[Problema]

### ISSUE THREAD

**Issue by emersonviola** [Tundrak/IPTV-Italia#63]
**Canale TV / Radio interessato**
Food Network Canale 33

**Descrivi il problema**
Recentemente i.o canal e è andato offline. Vienne visualizato un messagio per risintonizzarsi sulla nova frequenza. Ora non si carica nemmeno piuù

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: Mi Box S
 - Programma utilizzato Ott Navigator
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by Tundrak** [comment]
Contenuta in #66
