### ISSUE TITLE
Canale non più funzionante

### ISSUE THREAD

**Issue by WikkyNikky** [Tundrak/IPTV-Italia#64]
Ciao sto utilizzando la playlist iptvitaplus.m3u all'interno di Kodi installato in una Fire tv Stick 4k.
Volevo segnalare che da qualche giorno non riesco a visualizzare più il canale n. 21 "food network". 
Grazie

**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)

**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]
 - Programma utilizzato [es. VLC, Potplayer]
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by Tundrak** [comment]
Contenuta in #66
