### ISSUE TITLE
Canali Discovery Italia

### ISSUE THREAD

**Issue by DannyIDC** [Tundrak/IPTV-Italia#66]
Ciao, ma i canali discovery italia sono satati tutti? Non c'è modo di poter estrapolare il flusso video? Nove, Food Network, DMAX, Motor Trend, HGTV ecc. sono saltati tutti. In giro non si trova nulla. C'è speranza?

**Comment by Tundrak** [comment]
Ciao e scusate per il grandissimo ritardo
Ho reindirizzato tutte le Issue aperte sulla questione Discovery a questa, perchè è la più nuova e contiene più o meno tutti i canali interessati
Purtroppo non posso davvero farci niente e nella prossima release (spero non troppo tardi) tutti i canali verranno rimossi
Discovery ha rimosso tutti i link che la lista usava introducendone degli altri protetti da DRM, che quindi non sono riproducibili su player generici
Se dei link "normali" venissero trovati, li aggiungerò subito, però dubito che succederà nel prossimo futuro
Tengo aperta quest'Issue ancora per qualche giorno per farla vedere di più, poi la chiudo

**Comment by Namaisape** [comment]
Grazie 🙏

**Comment by Trifone46** [comment]
Buon giorno segnalo un indirizzo iptv
http://inthemix.altervista.org/tv.m3u
dove ci sono molti canali inclusi
Pluto Tv
Rakuten Tv
Samsung Tv
Ci sono quasi tutti i canali discovery ma specifico che non sono sempre stabili non so perche e non so se ci sia modo di stabilizzarli in qualche modo
