### ISSUE TITLE
[Problema] Canali RAI non visibili

### ISSUE THREAD

**Issue by JackSlaterIV** [Tundrak/IPTV-Italia#67]
**Canale TV / Radio interessato**
Tutti i canali RAI.

**Descrivi il problema**
Non sono più riproducibili tramite player software.

**Informazioni sul dispositivo**
Testato su PC con VLC. Chiedo conferma ad altri utenti.

**Comment by lollopod** [comment]
Anche per me non funzionano (Android TV PVR Live)

**Comment by micelf01** [comment]
Lo stesso per me. pero se li sccedi tramite Raiplay, con la VPN, ache in UK si vedano in chiaro

**Comment by tommyv** [comment]
Edit the links, add `&output=16` at the end. 
For example, RAI1,  https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803 becomes https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=16

**Comment by shibotto** [comment]
This seems to work, but how did you get it? Using the inspector on the website I only get a `&output=64`, which is an XML file.

**Comment by tommyv** [comment]
Trial and error. Tried dividing 64 with 4. Some other combinations work as well.

**Comment by JackSlaterIV** [comment]
@tommyv Thanks but it doesn't work for me, tested on VLC. :(
I guess it was patched very fast.

**Comment by tommyv** [comment]
Works with ffmpeg (streamlink), so not patched (yet)

**Comment by micelf01** [comment]
doesnt work for me

**Comment by tommyv** [comment]
Streamlink output:

`root@compiler:/# streamlink 'https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=16'
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin hls for URL https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=16
Available streams: 432p (worst), 576p, 720p (best)`

**Comment by micelf01** [comment]
fatto. adesso si ci siamo!

**Comment by ztony91** [comment]
grandi !! con questo output=16) ho risolto io guardo da app tivimate, per caso sapete se 
si puo fare qualcosa anche per i canali discovery?

**Comment by JackSlaterIV** [comment]
Putroppo su VLC non va. Qualcuno sa come mai? 
Forse hanno messo un filtro che controlla l'user agent che effettua la richiesta?

**Comment by Tundrak** [comment]
Mi chiedo, perchè cambiare un sistema che funzionava?
Le liste autoaggiornanti ora contengono il giusto parametro (**&output=16**) e dovrebbero funzionare in tutti i posti dove funzionavano prima, per quanto riguarda una versione stabile ci vorrà un po' più di tempo per farmi controllare bene che la numerazione LCN dei canali sia corretta e che sia tutto a posto
