### ISSUE TITLE
[Problema]

### ISSUE THREAD

**Issue by thomasrouzo** [Tundrak/IPTV-Italia#68]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)
tutti i canali Rai
**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.
"None of the available exrators (c,d,b,g,i,b,b0,d,h0,e,j,f,h,f,a) could read the stream", nessun problema per i canali mediaset
**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV] -> compu, smartpone y androidtv

 - Programma utilizzato [es. VLC, Potplayer] --> vlc, ott navigator, iptv simple, smart iptv
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by tommyv** [comment]
Edit the links, add &output=16 at the end.
For example, RAI1, https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803 becomes https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=16

**Comment by Tundrak** [comment]
Duplicato di #67
I link ora funzionano sulle liste autoaggiornanti, presto rilascerò una versione completa
