### ISSUE TITLE
Salve, uso la lista iptvita plus dall'estero con un VPN, mi funzionano tutti i canali, solo la Rai non si apre, ho provato diversi VPN, da che dipende? 

### ISSUE THREAD

**Issue by 1957alfa** [Tundrak/IPTV-Italia#69]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)

**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]
 - Programma utilizzato [es. VLC, Potplayer]
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by micelf01** [comment]
un intervento e già stato aperto. E meglio aggiungere che aprirne un altro. Se apri Raiplay con la VPN funziona!

**Comment by 1957alfa** [comment]
Non uso Raiplay, però ho un altra lista di Tivustream, e qui la Rai mi funziona è la vostra lista che non funziona la Rai.

Enviado desde Yahoo Mail para Android 
 
  El mar, 19 de jul. de 2022 a la(s) 0:08, ***@***.***> escribió:   


un intervento e già stato aperto. E meglio aggiungere che aprirne un altro. Se apri Raiplay con la VPN funziona!

**Comment by 1957alfa** [comment]
Enviado desde Yahoo Mail para Android 
 
  El mar, 19 de jul. de 2022 a la(s) 0:17, Michele ***@***.***> escribió:   Non uso Raiplay, però ho un altra lista di Tivustream, e qui la Rai mi funziona è la vostra lista che non funziona la Rai.

Enviado desde Yahoo Mail para Android 
 
  El mar, 19 de jul. de 2022 a la(s) 0:08, ***@***.***> escribió:   


un intervento e già stato aperto. E meglio aggiungere che aprirne un altro. Se apri Raiplay con la VPN funziona!

**Comment by tommyv** [comment]
Edit the links, add &output=16 at the end.
For example, RAI1, https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803 becomes https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=16

**Comment by 1957alfa** [comment]
Salve, sono riuscito a editare con un programma che si chiama IPTV Tester, la Rai 1 funciona, però vorrei sapere se la stessa formula "&output=16" vale anche per gli altri canali Rai, ho provato a metterli anche a Rai 2 e Rai 3, però quando apro il riproduttore si cancellano, dove sbaglio?Grazie

Enviado desde Yahoo Mail para Android 
 
  El jue, 21 de jul. de 2022 a la(s) 5:25, Michele ***@***.***> escribió:   Salve, mi scusi ho capito il cambio che devo fare, però non so dove e come farlo, mi può aiutare per favore, grazie.

Enviado desde Yahoo Mail para Android 
 
  El jue, 21 de jul. de 2022 a la(s) 0:33, ***@***.***> escribió:   


Edit the links, add &output=16 at the end.
For example, RAI1, https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803 becomes https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=16

**Comment by 1957alfa** [comment]
È corretto, adesso mi funzionano tutti i canali Rai.Grazie milleMichele Alfano 

Enviado desde Yahoo Mail para Android 
 
  El jue, 21 de jul. de 2022 a la(s) 16:41, Michele ***@***.***> escribió:   Salve, sono riuscito a editare con un programma che si chiama IPTV Tester, la Rai 1 funciona, però vorrei sapere se la stessa formula "&output=16" vale anche per gli altri canali Rai, ho provato a metterli anche a Rai 2 e Rai 3, però quando apro il riproduttore si cancellano, dove sbaglio?Grazie

Enviado desde Yahoo Mail para Android 
 
  El jue, 21 de jul. de 2022 a la(s) 5:25, Michele ***@***.***> escribió:   Salve, mi scusi ho capito il cambio che devo fare, però non so dove e come farlo, mi può aiutare per favore, grazie.

Enviado desde Yahoo Mail para Android 
 
  El jue, 21 de jul. de 2022 a la(s) 0:33, ***@***.***> escribió:   


Edit the links, add &output=16 at the end.
For example, RAI1, https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803 becomes https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=16

**Comment by micelf01** [comment]
Ma perche a me no mi funziona?

**Comment by 1957alfa** [comment]
Salve, stavo comunicandomi, per errore del telefono si è cancellata la email. Volevo spiegare come ho fatto a farlo funzionare, volevo mandare foto, però con la email che ho recuperato mi ritornano indietro. Non sono molto pratico e non saprei come altrimenti mandare foto per spiegare meglio.

**Comment by Tundrak** [comment]
Duplicato di #67
I link ora funzionano sulle liste autoaggiornanti, presto rilascerò una versione completa

**Comment by 1957alfa** [comment]
Salve, mi scusi ho capito il cambio che devo fare, però non so dove e come farlo, mi può aiutare per favore, grazie.

Enviado desde Yahoo Mail para Android 
 
  El jue, 21 de jul. de 2022 a la(s) 0:33, ***@***.***> escribió:   


Edit the links, add &output=16 at the end.
For example, RAI1, https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803 becomes https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=16

**Comment by Tundrak** [comment]
Ciao
In teoria adesso i link dovrebbero funzionare senza problemi con l'ultima versione della lista. Basta usare uno dei [link autoaggiornanti](https://github.com/Tundrak/IPTV-Italia#come-usarla) così non c'è bisogno di fare nessun cambio manuale.

**Comment by 1957alfa** [comment]
Buongiorno volevo notificare che da tempo non vedo Rai 1, in realtà nemmeno con altre liste si vede, è possibile sapere che succede e come posso soluzionare.Grazie per tutto quello che fate.Saluti dalla GermaniaMichele Alfano 

Gesendet von Yahoo Mail auf Android 
 
  Am Fr., Okt. 14, 2022 at 21:20 schrieb ***@***.***>:   


Ciao
In teoria adesso i link dovrebbero funzionare senza problemi con l'ultima versione della lista. Basta usare uno dei link autoaggiornanti così non c'è bisogno di fare nessun cambio manuale.

**Comment by Tundrak** [comment]
Ciao!
Non so quanto essere in Germania possa peggiorare la situazione, però di sicuro qua in Italia i canali funzionano perfettamente.
Posso sapere quale app/programma usi per visualizzare la lista? Non si vede solo Rai 1 o tutti i canali Rai in generale?

**Comment by 1957alfa** [comment]
Salve, uso la app Televizo, solo Rai 1 non si apre

Gesendet von Yahoo Mail auf Android 
 
  Am Mi., Juni 21, 2023 at 20:37 schrieb ***@***.***>:   


Ciao!
Non so quanto essere in Germania possa peggiorare la situazione, però di sicuro qua in Italia i canali funzionano perfettamente.
Posso sapere quale app/programma usi per visualizzare la lista? Non si vede solo Rai 1 o tutti i canali Rai in generale?

**Comment by Tundrak** [comment]
Se stai usando il link autoaggiornante, è strano (io vedo tutto tranquillamente)
Potresti provare a dirmi se almeno una di queste due varianti funziona nella lista dentro a questo file zip? Se una va puoi sostituirla tu manualmente [prova.zip](https://github.com/Tundrak/IPTV-Italia/files/11835846/prova.zip)

**Comment by 1957alfa** [comment]
Ciao, purtroppo la prova che mi hai mandato non ha funzionato, ho provato anche a prendere tutti i Rai 1, da tutte le liste autoaggiornanti che avevo raccolto nel tempo, purtroppo nessuno di esso funziona, quindi non è colpa della tua lista, non so spiegarmi questo e nemmeno so da quanto di preciso non funziona la Rai 1, ho provato con altri Player e con altri VPN, niente da fare, avevo trovato un Rai 1 in SD (credo si dice così) che funzionava, come pure da un'altra lista che non serve il VPN, ho preso Rai 1, e li ho aggiunto nella tua lista, dopo circa 15 minuti la SD si è spenta e si vedono solo le strisce colorate, mentre quella che funziona senza VPN ha momenti di blocco, un poco complicato, va bene vuol dire che vedrò gli altri programmi finché non trovo una soluzione.Molte grazie.Michele Alfano 

Gesendet von Yahoo Mail auf Android 
 
  Am Do., Juni 22, 2023 at 17:42 schrieb ***@***.***>:   


Se stai usando il link autoaggiornante, è strano (io vedo tutto tranquillamente)
Potresti provare a dirmi se almeno una di queste due varianti funziona nella lista dentro a questo file zip? Se una va puoi sostituirla tu manualmente prova.zip

**Comment by 1957alfa** [comment]
Ciao, c'è una novità, prima usavo il TV box, adesso mi sono spostato su un Smart tv, Android, non è stato facile, mettere le applicazioni che mi servivano, però c'è l'ho fatto, funziona perfettamente, tutti i programmi. Però ci stavo lavorando al problema di Rai 1 e credo che nonostante non ho conoscenze, sono riuscito a farla funzionare, non so se così è corretto, avevo trovato una lista che funzionava Senza VPN, ho preso l'ultimo URL di Rai 1 e ho cambiato quello della tua lista, ha funzionato, poi mi è venuto l'idea della Smart che avevo.

Grazie per la pazienzaSalutiMichele Alfano

Gesendet von Yahoo Mail auf Android 
 
  Am Fr., Juni 23, 2023 at 19:05 schrieb ***@***.***>:   


Mi dispiace di non riuscire a risolvere il problema. Aggiornami se riesci a trovare una soluzione / un link che funziona

**Comment by 1957alfa** [comment]
Notizia dell'ultima ora, il guasto si tolto da solo, in tutte le liste è tornato a funzionare la Rai 1, doveva essere qualcosa nel segnale, perché anche a mia figlia che vive in un altra città non riceveva la Rai 1.Ancora salutiMichele Alfano

Gesendet von Yahoo Mail auf Android 
 
  Am Fr., Juni 23, 2023 at 19:28 schrieb Michele ***@***.***>:   Ciao, c'è una novità, prima usavo il TV box, adesso mi sono spostato su un Smart tv, Android, non è stato facile, mettere le applicazioni che mi servivano, però c'è l'ho fatto, funziona perfettamente, tutti i programmi. Però ci stavo lavorando al problema di Rai 1 e credo che nonostante non ho conoscenze, sono riuscito a farla funzionare, non so se così è corretto, avevo trovato una lista che funzionava Senza VPN, ho preso l'ultimo URL di Rai 1 e ho cambiato quello della tua lista, ha funzionato, poi mi è venuto l'idea della Smart che avevo.

Grazie per la pazienzaSalutiMichele Alfano

Gesendet von Yahoo Mail auf Android 
 
  Am Fr., Juni 23, 2023 at 19:05 schrieb ***@***.***>:   


Mi dispiace di non riuscire a risolvere il problema. Aggiornami se riesci a trovare una soluzione / un link che funziona
