### ISSUE TITLE
[Problema]

### ISSUE THREAD

**Issue by aleZZ2001** [Tundrak/IPTV-Italia#72]
**Canale TV / Radio interessato**
Tutti i canali Rai

**Descrivi il problema**
Tutti i canali rai si fermano dopo 1 minuto con ffmpeg

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [Qualsiasi Dispositivo]
 - Programma utilizzato [Plex tramite xTeVe]
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by Tundrak** [comment]
Prova a controllare adesso con gli ultimi cambiamenti nella lista autoaggiornante, forse andrà meglio?

**Comment by aleZZ2001** [comment]
> Prova a controllare adesso con gli ultimi cambiamenti nella lista autoaggiornante, forse andrà meglio?

Ho provato proprio con l'ultima versione, penso sia un problema lato ffmpeg ma non so veramente cosa fare

**Comment by Tundrak** [comment]
Scusa per il lungo tempo di risposta
Ffmpeg "liscio" sul mio computer riesce ad aprire i link Rai e a tenerli aperti per più di un minuto, però sospetto che Plex e plugin (come hai scritto di usare) possano aggiungere delle opzioni problematiche che bloccano la riproduzione
Forse puoi trovare dei log da qualche parte che mostrano il comando specifico che usa per aprirle con tutte le flag e opzioni?

**Comment by aleZZ2001** [comment]
> 

Ciao, mi ero dimenticato di dirti che sono riuscito a risolvere il problema mettendo il flag -re prima del -i. Solo che ora c'è un altro problema, da circa 2 giorni non funziona Italia 1
