### ISSUE TITLE
[Problema]

### ISSUE THREAD

**Issue by alegamer4008** [Tundrak/IPTV-Italia#76]
Ciao! , pensavo che queste iptv avrebbero funzionato visto che ho notato che sono molto recenti, (pubblicate 10 giorni fa), ma a quanto pare non ne funziona quasi nessuna, ora ti faccio una lista dei canali che non funzionano:

Rai 1: non funziona
Rai 2: non funziona
Rai 3: non funziona
Rete 4: non funziona
Canale 5: non funziona
Italia 1: non funziona
20 Mediaset: non funziona
Rai 4: non funziona
IRIS: non funziona
Rai 5: non funziona
Rai movie: non funziona
Rai Premium: non funziona
Twenty Seven: non funziona
La5: non funziona
Cine34: non funziona
Focus: non funziona
Top Crime: non funziona
Boing: non funziona
Rai Gulp: non funziona
Rai yoyo: non funziona
Cartoonito: non funziona
Super!: non funziona
Rai News 24: non funziona
Italia 2: non funziona
Sky TG24: non funziona
TGCOM24: non funziona
Rai Storia: non funziona
Mediaset Extra: non funziona
Rai Scuola: non funziona
Rai Sport + HD: non funziona
SoloCalcio: non funziona
Donna TV: non funziona
Radio 105 TV: non funziona
R101 TV: non funziona
RadioItaliaTV: non funziona
Padre Pio TV: non funziona
Radio Kiss Kiss TV: non funziona
Rai Radio 2 Visual: non funziona
Virgin Radio: non funziona
Radio Montecarlo TV: non funziona

I Canali Che Funzionano sono invece:

RTV San Marino: funziona
M20 TV: funziona
Radio Capital TV: funziona
Radio Zeta: funziona
RDS Social TV: funziona
Radio Freccia: funziona
RTL 102.5 NEWS: funziona
VH1: funziona
DeeJay TV: funziona
Alma TV: funziona
SuperTennis: funziona
Sportitalia: funziona
GM24: funziona
RTL 102.5: funziona
QVC: funziona
La7D: funziona
TV2000: funziona
LA7: Funziona

Quindi circa il 90% dei canali non funzionano, e quindi mi chiedo se almeno avete testato l'iptv prima di pubblicarla.

 - Tipo di dispositivo: [Testato su: computer e telefono]
 - Programma utilizzato [VLC, Iptv extreme]
 - Versione lista [v07-2022]

**Comment by Tundrak** [comment]
Ciao!
Mi dispiace che tu stia avendo questa esperienza, ma confermo che i canali Rai e Mediaset funzionano decisamente tutti (anche perchè sennò starei ricevendo molte più Issue al riguardo :D)
Allego anche questo video di VLC che riproduce la lista (è uno dei player che hai specificato)

https://user-images.githubusercontent.com/77153792/183993185-9033b290-0d1f-476e-ac19-026645b5b41f.mp4

A questo punto però non sono sicuro di cosa blocchi tutti quei canali per te specificamente, sono davvero tanti

**Comment by Tundrak** [comment]
Stai ancora avendo questi problemi?
Ho controllato ancora e i canali per me funzionano quasi tutti
