### ISSUE TITLE
[Problema] Cambio risoluzione stream

### ISSUE THREAD

**Issue by peppelongo96** [Tundrak/IPTV-Italia#77]
**Canale TV / Radio interessato**
Tutti

**Descrivi il problema**
Salve. Uso kodi con iptv simple client. Mi chiedevo se esiste un modo per cambiare (nel caso ridurre) la risoluzioni dello stream. Purtroppo ho la tv box in un posto dove non posso andare oltre i 3 mbps/s. O nel caso, se posso agevolare il buffering con qualche settaggio.

**Comment by Tundrak** [comment]
Ciao!
Fortunatamente con IPTV Siple Client puoi cambiare la risoluzione dei canali che lo supportano (anche se purtroppo non mi risulta che si possa fare automaticamente, dovrai cambiare l'impostazione ogni volta che ne apri uno)
In sostanza, mentre si sta visualizzando un canale in riproduzione basta premere sull'icona Settings in basso a destra (l'ingranaggio), poi premere Select Program e selezionare lo stream che si vuole usare (vengono mostrati tutti i bitrate disponibili)
Se vuoi conoscere la risoluzione dello stream, puoi usare l'opzione Video settings e leggere la prima linea in alto (Video stream)

**Comment by Tundrak** [comment]
Buonasera!
Alla fine sei riuscito a risolvere il problema?

**Comment by peppelongo96** [comment]
> 
Sì grazie mille!
