### ISSUE TITLE
[Richiesta Canale] RSI LA1/LA2

### ISSUE THREAD

**Issue by peppelongo96** [Tundrak/IPTV-Italia#78]
Salve!
Non esiste un modo per aggiungere alla lista i canali della Radiotelevisione Svizzera di lingua Italiana?

**Comment by Tundrak** [comment]
Ciao!
Purtroppo, un requisito che mi do per aggiungere canali alla lista è che siano visibili da tutta l'Italia (quindi nell'ordine LCN).
I canali RSI non sono decisamente visibili in tutta Italia, e anche volendo inserirli, sono geobloccati alla Svizzera (con DRM, dall'Italia il link dello stream di LA1 sembra poter essere [questo](https://rsila1-euwe.akamaized.net/f2374fe2-89ec-41aa-a0ef-d1faa4ca31f0/rsi1.ism/manifest(format=m3u8-aapl,encryption=cbcs-aapl,filter=nodvr)) ma se riesci ad aprirlo puoi notare anche tu che è criptato)
Mi dispiace, ma non penso che potrò mai aggiungerli
