### ISSUE TITLE
Super! 47

### ISSUE THREAD

**Issue by dapuzz** [Tundrak/IPTV-Italia#79]
Ciao
Ho notato da qualche giorno è sparito Super! canale 47 DTV
https://viacomitalytest-lh.akamaihd.net/i/sbshdlive_1@357018/master.m3u8

Ci sono alternative?
Grazie in anticipo!

**Comment by Tundrak** [comment]
E' vero!
Il nuovo link dello stream pare essere https://vimnitaly.akamaized.net/hls/live/2094034/super/master.m3u8
Non so se rilascerò un aggiornamento presto (cerco di fare in modo che siano relativamente corposi), ma nel frattempo se vuoi puoi aggiungerlo tu manualmente nella tua lista

**Comment by Tundrak** [comment]
Un po' in ritardo come immaginavo, ma il nuovo link è ora nella [Versione Gennaio 2023](https://github.com/Tundrak/IPTV-Italia/releases/tag/v01-2023)!
