### ISSUE TITLE
Richiesta canali in HD

### ISSUE THREAD

**Issue by chry1102** [Tundrak/IPTV-Italia#8]
Salve, vorrei sapere se è possibile rendere disponibili nella lista la versione in alta definizione di alcuni canali Mediaset come Canale 5, Italia 1 o Rete 4, che al momento se non sbaglio sono in definizione standard. Grazie in anticipo.

**Comment by Tundrak** [comment]
Purtroppo, da quello che vedo sembra che Mediaset non abbia messo a disposizione link per canali in HD (non lo sono neanche quelli visibili nel loro sito Mediaset Infinity), anche se il sito ultimamente è stato rinnovato e quindi magari possiamo aspettarceli nel prossimo futuro :)
Comunque faccio notare che anche la risoluzione dei canali Rai (nonostante ci sia scritto HD vicino al nome) è comunque di 1024x576 (TV standard, la stessa di quelli Mediaset ma con un bitrate un po' più alto). Questo rende gli unici canali in "vero" HD (1280x720) disponibili nella lista quelli di Discovery e alcune eccezioni come RDS, QVC, VH1 e Padre Pio TV.
Continuerò comunque a monitorare tutti i siti, e appena vedrò link in alta definizione li aggiungerò subito!

**Comment by chr869** [comment]
Va bene, grazie mille della risposta. Speriamo che in futuro vengano resi disponibili i canali in alta definizione e magari che vengano eliminati del tutto quelli in definizione standard. Arrivederci!

**Comment by PowerBoy81** [comment]
Al momento solo CANALE 5 in streaming è in HD.

**Comment by Tundrak** [comment]
Dopo tutto questo tempo, posso confermare che praticamente tutti i canali Rai e Mediaset sono disponibili in almeno 720p (e la maggior parte in 1080p), con la nuova [Versione Dicembre 2023](https://github.com/Tundrak/IPTV-Italia/releases/tag/v12-2023)!
Bastava aspettare un paio di anni :) @chry1102 Se sei ancora qui ti ringrazio per la fiducia
