### ISSUE TITLE
Telelombardia, telenova,antenna3, telecolor

### ISSUE THREAD

**Issue by Davegahan17** [Tundrak/IPTV-Italia#80]
**Canale Richiesto**
Scrivi il nome completo del canale TV / Radio che vuoi aggiunto in una delle due liste [es. Rai 1]
Se il canale è regionale, specificalo e indica la regione d'appartenenza.

**URL Streaming**
Copia il link del sito internet ufficiale del canale da cui puoi vedere / sentire la diretta. [es. https://www.raiplay.it/dirette/rai1]

**Comment by Tundrak** [comment]
Ciao!
Questi canali sono regionali, e Telecolor è già incluso nella pre-release [iptvregionale](https://github.com/Tundrak/IPTV-Italia/releases/tag/regionale-pre9) che però non mantengo spesso perchè richiede tanto lavoro
Gli altri canali non sono inclusi perchè realizzano gli stream con Youtube, per cui i link cambiano spesso e non sono supportati da tutti i player. Antenna 3 non ha nemmeno uno stream sul sito ufficiale
Sicuramente se la situazione cambierà aggiungerò i link nella lista regionale, ma per ora vedo difficile che succeda qualcosa

**Comment by Davegahan17** [comment]
Grazie sei stato molto gentile.  ..sono un fanatico dei regionali

⁣Ottieni TypeApp per Android ​

Il giorno 14 Ott 2022, 21:15, alle ore 21:15, Tundrak ***@***.***> ha scritto:
