### ISSUE TITLE
TV8 e Cielo

### ISSUE THREAD

**Issue by DannyIDC** [Tundrak/IPTV-Italia#82]
Ciao, per vedere Cielo e TV8 io uso i seguenti link:
https://www.mytivu.it/Application/Channels/TV8.php
https://www.mytivu.it/Application/Channels/Cielo.php

Tramite il programma SS IPTV che sulla smart LG riesco ad eseguirlo tramite il comando presente sulla lista m3u mime-type="application/vnd.apple.mpegurl, ciò non avviene invece con altri player come per esempio TiviMate che ho sulla firestick. Sai se esiste un comando che fa aprire il file m3u8 nascosto dal PHP?
È strano che SS IPTV riesca ed altri player che ritengo superiori non lo facciano. Penso esista un comando come mime-type per ovviare al problema, io non riesco a trovare nulla in merito. Ciao.

**Comment by Trifone46** [comment]
Buon giorno segnalo un indirizzo iptv
http://inthemix.altervista.org/tv.m3u
dove ci sono molti canali inclusi
Pluto Tv
Rakuten Tv
Samsung Tv
Ci sono quasi tutti i canali discovery ma specifico che non sono sempre stabili non so perche e non so se ci sia modo di stabilizzarli in qualche modo

**Comment by comleoita** [comment]
Il file php contiene una banale richiesta ad un file json nei server akamaized.
Questo contiene il link aggiornato in formato m3u8 e poi con header(“location: ….”) viene fatto un redirect appunto al link m3u8 estrapolato prima. Purtroppo alcuni player iptv non vanno con questo modo…

**Comment by Trifone46** [comment]
Buon giorno segnalato che da ieri in giornata il link a cui fa riferimento cielo non si vede più in alternativa se si trova qualche altra soluzione puo scriverlo qui

**Comment by Trifone46** [comment]
ATTENZIONE DA UN PAIO DI GIORNI IL LINK PER VEDERE CIELO NON FUNZIONA PIU .

**Comment by Tundrak** [comment]
Novità: alcuni contributori hanno trovato link per i canali Sky, ora sono nella nuova [Versione Gennaio 2023](https://github.com/Tundrak/IPTV-Italia/releases/tag/v01-2023)!
