### ISSUE TITLE
[Problema] RAI 1, disconnessione dopo ~100 sec

### ISSUE THREAD

**Issue by illtellyoulater** [Tundrak/IPTV-Italia#83]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)

Rai 1

**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.

Dopo circa 100 secondi il lettore video (Kodi nel mio caso) viene disconnesso dal canale. Questo succede solo con Rai 1 e nessuno degli altri canali della lista. In realtà succede sin da quando ho iniziato ad usarla ma non avevo segnalato il problema pensando fosse temporaneo.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]
 - Programma utilizzato [es. VLC, Potplayer]
 - Versione lista [es. v04-2021]

TV box con Kodi con lista canali autoaggiornante.

**Comment by Tundrak** [comment]
Ciao!
Se stai usando come addon PVR IPTV Simple Client prova a seguire i passaggi contenuti in [quest'altra Issue](https://github.com/Tundrak/IPTV-Italia/issues/36#issuecomment-1003741371), facendo così io e anche altri non riscontriamo più problemi
Dimmi se funziona anche per te

**Comment by Miccio-AN** [comment]
Ciao!
Anche io confermo la risoluzione del problema con questo sistema.

Grazie
