### ISSUE TITLE
SKY TG 24 non si apre

### ISSUE THREAD

**Issue by learnro** [Tundrak/IPTV-Italia#84]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)

**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]
 - Programma utilizzato [es. VLC, Potplayer]
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by Trifone46** [comment]
Questo e un link per vedere la diretta Sky TG 24
https://www.mytivu.it/Application/Channels/SkyTG24.php

**Comment by Tundrak** [comment]
E' vero, mi dispiace.
Purtroppo Sky e Discovery non forniscono link "puliti" per i loro canali, quindi probabilmente dovrò rimuovere anche questo dalla lista in un futuro aggiornamento
(Se il link di Trifone96 ti soddisfa ti invito ad aggiungerlo manualmente alla tua lista, ma io non lo inserirò nella mia prima di tutto perchè non è ufficiale, e nel caso di quello in particolare perchè non è un link diretto a un file playlist e alcuni lettori hanno problemi con i reindirizzamenti)

**Comment by Tundrak** [comment]
Sei fortunato! Alcuni contributori hanno trovato un nuovo link, ora nella nuova [Versione Gennaio 2023](https://github.com/Tundrak/IPTV-Italia/releases/tag/v01-2023)
