### ISSUE TITLE
[Richiesta Canale] Radio Bruno

### ISSUE THREAD

**Issue by simonebartoli** [Tundrak/IPTV-Italia#85]
**Canale Richiesto**
Radio Bruno

**URL Streaming**
https://www.radiobruno.it/radio-bruno-tv/

**Comment by Trifone46** [comment]
Questo e un link per vedere la diretta di Radio Bruno 
https://router.xdevel.com/video0s975758-473/stream/playlist.m3u8

**Comment by Tundrak** [comment]
Ciao!
Purtroppo Radio Bruno non è un canale visibile in tutta Italia, per cui non verrà aggiunto alla lista nazionale.
Tuttavia è già presente nella lista della regione Emilia-Romagna (in cui viene trasmesso principalmente) scaricabile insieme a diverse altre a [questo link](https://github.com/Tundrak/IPTV-Italia/releases/tag/regionale-pre9). Alcuni canali nella stessa lista non funzionano, ma quello e la maggior parte sì.
