### ISSUE TITLE
[Problema] Rai 1, 2, 3 non si vedono

### ISSUE THREAD

**Issue by ciukkino89** [Tundrak/IPTV-Italia#86]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)
Rai 1, 2, 3
**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.
I canali rai non si vedono

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV] ps3
 - Programma utilizzato [es. VLC, Potplayer] movian, plugin iptv 
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by Trifone46** [comment]
Strano che non ti funzionano i canali Rai io uso la lista che ai indicato e non sto avendo nessun problema specifico che come lettore utilizzo iptv pro

**Comment by Tundrak** [comment]
Ciao.
Mi dispiace se non sono ancora riuscito a trovare una soluzione, ma ho paura che Movian non supporti correttamente i link che reindirizzano ad altri siti web (come quelli di Rai). Purtroppo non posso fare niente per questo, ma continuo lo stesso a monitorare la situazione ogni tanto per vedere se qualcosa cambia.
Ti chiedo però di mantenere la discussione sull'Issue orginale #45 da te aperta e non crearne di nuove, se scrivi lì vengo ancora notificato

**Comment by ciukkino89** [comment]
Scusa hai ragione, me ne ero dimenticato...Grazie per la risposta, pensavo di sbagliare qualcosa io, ci sono alternative funzionanti a movian?Il 19 dic 2022 20:27, Tundrak ***@***.***> ha scritto:

Ciao.

Mi dispiace se non sono ancora riuscito a trovare una soluzione, ma ho paura che Movian non supporti correttamente i link che reindirizzano ad altri siti web (come quelli di Rai). Purtroppo non posso fare niente per questo, ma continuo lo stesso a monitorare la situazione ogni tanto per vedere se qualcosa cambia.

Ti chiedo però di mantenere la discussione sull'Issue orginale #45 da te aperta e non crearne di nuove, se scrivi lì vengo ancora notificato

**Comment by Tundrak** [comment]
Vedendo che stai usando una PS3, purtroppo non saprei.
Cercando velocemente su Google, forse potresti provare Plex però avresti bisogno anche di un computer e non so comunquse se così funzionerebbe
