### ISSUE TITLE
[Problema] canali Rai principali

### ISSUE THREAD

**Issue by JackSlaterIV** [Tundrak/IPTV-Italia#87]
**Canale TV / Radio interessato**
Canali Rai principali: rai 1, rai 2, rai 3, rai 4, rai 5, rai movie, rai premium.

**Descrivi il problema**
Non si vedono. Chiedo conferma ad altri utenti.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: Computer
 - Programma utilizzato VLC
 - Versione liste: v07-2022

**Comment by Tundrak** [comment]
Perchè VLC ha sempre qualche problema?
L'unica differenza che vedo tra questi e altri canali Rai che funzionano è che i primi sono apparentemente serviti da un nuovo CDN (qualcosa.msvdn.net) a differenza degli altri, ancora sul fidato nomecanale-live.akamaized.net
Vedrò se capisco dov'è il blocco, anche perchè altri player riescono tranquillamente a riprodurli

**Comment by comleoita** [comment]
su vlc non funzionano, mentre sugli altri client iptv vanno bene.
Io uso questi:
https://raiuno1-dash-live.akamaized.net/dash/live/652296/raiuno1/manifest.mpd
che si ricavano mettendo alla fine del link del relinker della rai questo "&forceUserAgent=hbbtv"

**Comment by JackSlaterIV** [comment]
@comleoita 
Ho provato a fare ciò che suggerisci su VLC (Windows), e non funziona. Usando Media Player Classic funziona.

Secondo me VLC invia sempre il suo "user agent", e quelli della Rai hanno creato un filtro apposito per VLC, ma non per gli altri player. Spiegazione molto semplice. 
Inoltre avevo anche provato la lista cercando di lanciare VLC con il parametro ":http-user-agent=", ma non va ugualmente.
Non vedo altre spiegazioni.

**Comment by comleoita** [comment]
Prova a installare su edge o chrome “Hls m3u8 mpd player” e così
funzionerà. Io non uso vlc proprio per questo motivo.

Il giorno dom 25 dic 2022 alle 11:30 JackSlaterIV ***@***.***>
ha scritto:

**Comment by Tundrak** [comment]
Mi stavo scervellando per tentare di capire, e poi ho provato a scaricare una versione di sviluppo di VLC da [qui](https://nightlies.videolan.org) e i link Rai con i redirect funzionano perfettamente :/
Forse allora la colpa non era nostra, e possiamo sperare che in un aggiornamento futuro i problemi si risolvano
Il link dash di @comleoita non funziona comunque, però mi viene da pensare che il problema sia sempre da parte di VLC e che magari verrà risolto a tempo debito
Io tengo aperta quest'Issue per il momento, ma spero di chiuderla presto

**Comment by comleoita** [comment]
Molto probabilmente la colpa è di vlc, visto che sulla tv quel link .mpd funziona senza problemi.

**Comment by alespita82** [comment]
sembra che abbiano cambiato di nuovo sistema, ora sono passai su raiuno1-live.akamaized.net
neanche con vlc usando user agent mozilla si aprono

**Comment by mircolac** [comment]
Non so se questo possa esservi utile ma ho provato a caricare la lista oggi su vlc (da pc) e, per quanto riguarda i canali rai, notavo che il video era ottimo ma l'audio non si sentiva (era praticamente muto)
Sotto Audio > traccia audio apparivano 4 tracce audio, di cui la quarta denominata 'Traccia 5'. Selezionando questa ora l'audio sta funzionando regolarmente

![image](https://user-images.githubusercontent.com/15798772/213199870-96d1fecc-c9e6-40d2-8fa4-3e222f01cd35.png)

**Comment by matteolaltrelli** [comment]
Ho provato a caricare la lista su una smart Tv LG su app SSIPTV, tutti i canali sono funzionanti tranne RAI1. Suggerimenti?

**Comment by mircolac** [comment]
> 

riprova ora. Fino a ieri sera non funzionava neanche a me, ora va. Quello che invece continua a non andare è LA7...

**Comment by matteolaltrelli** [comment]
> > 
> 
> riprova ora. Fino a ieri sera non funzionava neanche a me, ora va. Quello che invece continua a non andare è LA7...

Riprovato più volte Rai1 non va, LA7 non ha nessun problema sulla mia applicazione.

**Comment by nortek1986** [comment]
io sul pc non ho problemi a vedere tutta la lista,mentre su telefono non c'è verso di vedere la rai...ho provato tantissime app....quella che mi fa funzionare piu canali è my iptv player (praticamente tutti apparte la rai)

**Comment by Tundrak** [comment]
Ciao @nortek1986, grazie per i complimenti :)
Personalmente non uso la lista sul telefono, ma ho provato a scaricare qualcosa e pare che l'app [Televizo](https://play.google.com/store/apps/details?id=com.ottplay.ottplay) li riproduca tranquillamente. Non so se funzioni bene con Android Auto
(il fatto che Rai 4K funzioni ovunque è normale, quel canale ha un link diverso da tutti gli altri e più "standard", senza redirect)

**Comment by Tundrak** [comment]
Con i nuovi cambiamenti alla lista da #109 nell'ultima [Versione Giugno 2023](https://github.com/Tundrak/IPTV-Italia/releases/tag/v06-2023), spero di aver migliorato l'esperienza per gli utenti di VLC (io non ho più problemi nella riproduzione di nessun canale). Per questo, chiudo l'Issue.
