### ISSUE TITLE
Canali Rai e Mediaset Android[Problema]

### ISSUE THREAD

**Issue by Lelds93** [Tundrak/IPTV-Italia#89]
**Rai e Mediaset**

Ciao, sia con VLC e sia con altri player IPTV non riesco a vedere i canali Rai e i canali mediaset.Se inserisco la lista si avvia solo da La7 in poi 
App provate : VLC, IPTV EXTREME, WEB VIDEO CASTER

**Comment by Tundrak** [comment]
Ciao
VLC è senza speranza: per qualche motivo le loro stesse opzioni per cambiare l'User Agent (operazione necessaria per vedere i canali Rai e Mediaset) non funzionano su Android da [anni](https://code.videolan.org/videolan/vlc-android/-/issues/2572) e finchè non le riparano non si può fare niente.
(Davvero, non usare VLC per quardare IPTV in generale)
IPTV Extreme sembra strano però: puoi provare a seguire i passaggi in #10 per impostare l'User Agent? Forse aiutano

**Comment by Lelds93** [comment]
Ciao
Effettivamente impostando l'User Agente su Mozilla si vedono sia i canali Rai che i canali Mediaset lasciando come player advanced.Peccato non riesca a vederli tramite Web video caster :(
Grazie mille 😊

**Comment by Tundrak** [comment]
Ho controllato meglio e in realtà i canali che non funzionano si vedono tranquillamente anche su Web Caster se copi i link singolarmente dal file della playlist (tipo https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=16) e li incolli a mano nella sezione browser. Probabilmente dalla sezione IPTV non vanno per qualche bug con i redirect?
Forse l'unico modo per risolvere il problema sarebbe segnalarlo agli sviluppatori dell'app, magari lo possono risolvere loro
