### ISSUE TITLE
[Richiesta Canale] link alternativi Rai 1 e Rai 3.

### ISSUE THREAD

**Issue by MarkPorty** [Tundrak/IPTV-Italia#9]
![IMG_20210603_231508](https://user-images.githubusercontent.com/84259892/120713149-cc48fe00-c4c1-11eb-85ff-f301d230940a.jpg)

Sembrano funzionare meglio rispetto a quello che usi.
Se puoi scrivermi in privato vorrei mandarti un link

**Comment by Tundrak** [comment]
Come posso contattarti in privato?
Anche se sinceramente preferirei mantenere la discussione qui per averla disponibile a tutti e per evitare di dover inviare qui informazioni personali

Comunque, per il momento controllando i link dell'immagine quello di Rai 3 sembra buono, invece quello di Rai 1 non penso di accettarlo nonostante funzioni perchè voglio aggiungere solo link "ufficiali", e quello proviene da un sito armeno.
