### ISSUE TITLE
[Problema]

### ISSUE THREAD

**Issue by bollicine79** [Tundrak/IPTV-Italia#92]
Ciao, veramente gia ti ho scritto ieri, il mio problema e che i canali rai hanno l'html di mezzo, e flussonic media server non li legge, non si potrebbe togliere l'html?

**Comment by Tundrak** [comment]
Ciao.
Non c'era bisogno di aprire un'altra Issue per lo stesso motivo, avrei comunque visto la prima controllando adesso
Purtroppo i canali Rai ottengono il token attraverso una pagina di "mezzo" che li reindirizza a quella giusta, e quella è servita come text/html. Puoi ottenere link DASH alternativi senza redirect (tra l'altro, anche a risoluzione maggiore) seguendo le istruzioni in [questo commento](https://github.com/Tundrak/IPTV-Italia/issues/87#issuecomment-1364647716) di un'altra Issue, che risultano in link come quello in esempio. Io non li includerò nella mia lista (anche se di qualità più alta) perchè causano problemi extra con VLC (sto tentando di limitare i danni anche se VLC è terribile perchè lo usano tutti, e i link con redirect / html almeno _ogni tanto_ funzionano), se però funzionano per te li puoi sostituire tu manualmente
