### ISSUE TITLE
Prova canali TV 8 e Cielo

### ISSUE THREAD

**Issue by Infinitas79** [Tundrak/IPTV-Italia#94]
Puoi verificare questi? Sono corretti?
Rispettivamente TV 8 e Cielo

http://hlslive-web-gcdn-skycdn-it.akamaized.net/TACT/11223/tv8web/master.m3u8?hdnea=st=1639498341~exp=1702463400~acl=/*~hmac=c3c4c2de19ff0df4b4bb20587ce59af5232eadab2995f445b7506525413805dd

https://hlslive-web-gcdn-skycdn-it.akamaized.net/TACT/11219/cieloweb/master.m3u8?hdnea=st=1639498341~exp=1702463400~acl=/*~hmac=c3c4c2de19ff0df4b4bb20587ce59af5232eadab2995f445b7506525413805dd

**Comment by Trifone46** [comment]
Buon giorno infinitas79 confermo che rispettano TV 8 e Cielo funzionano con chrome e si vedono bene grazie per aver trovato questi link .

**Comment by Trifone46** [comment]
Buon giorno Infinitas79 confermo che rispettano TV 8 e Cielo funzionano con chrome e si vedono bene grazie per aver trovato questi link .m

**Comment by Trifone46** [comment]
Buon giorno Infinitas79 confermo che rispettano TV 8 e Cielo funzionano con chrome e si vedono bene grazie per aver trovato questi link .

**Comment by Infinitas79** [comment]
In realtà, nella mia ignoranza, dopo inutili ricerche e tentativi per estrapolare link m3u8 puliti, alla fine ho preso il link postato da Admiral-Benson (sky tg24 funzionante) e ho cambiato nome e codice dei canali. Per questo chiedevo una verifica da chi se ne intende ;) Se si trova anche un solo canale Discovery funzionante, magari si può fare la stessa cosa. Suggerisco di togliere la s da https, almeno per i canali rai, in modo da rendere tutta la lista m3u fruibile anche con ss-iptv. Capire che il mio problema con i canali rai fosse quello, non è stato per niente facile

**Comment by Trifone46** [comment]
Ho trovato un link per Nove funziona non so se si puo utilizzare con la stessa modalita ?

Nove
http://92.104.184.8:8080/play/a05q

**Comment by Trifone46** [comment]
Ho trovato un link per Nove funziona se viene inserito in una lista e in contemporanea se viene aperto con iptv pro ho quello non pro non so se si puo utilizzare con la stessa modalita ?

Nove
http://92.104.184.8:8080/play/a05q

**Comment by Trifone46** [comment]
Ho trovato un link per Nove funziona se viene inserito in una lista e in contemporanea se viene aperto con iptv pro ho quello non pro non so se si puo utilizzare con la stessa modalita da come ai descritto nel precedente post ?

Nove
http://92.104.184.8:8080/play/a05q

**Comment by Infinitas79** [comment]
Grazie. Ho completato la lista. Su ss-iptv vanno bene. Io inserisco ogni canale singolarmente da quando ho avuto problemi con i canali Rai. Ma questi saranno duraturi? Intanto io li uso :D

#EXTINF:-1,Discovery-italia NOVE
http://92.104.184.8:8080/play/a0ga
#EXTINF:-1,Discovery-italia NOVE
http://92.104.184.8:8080/play/a05q
#EXTINF:-1,Discovery-italia Real Time
http://92.104.184.8:8080/play/a0g9
#EXTINF:-1,Discovery-italia Real Time
http://92.104.184.8:8080/play/a05r
#EXTINF:-1,Discovery-italia food network I
http://92.104.184.8:8080/play/a0ge
#EXTINF:-1,Discovery-italia food network I
http://92.104.184.8:8080/play/a05p
#EXTINF:-1,Discovery-italia DMAX
http://92.104.184.8:8080/play/a0gb
#EXTINF:-1,Discovery-italia DMAX
http://92.104.184.8:8080/play/a05
#EXTINF:-1,Discovery-italia Giallo
http://92.104.184.8:8080/play/a0gc
#EXTINF:-1,Discovery-italia Giallo
http://92.104.184.8:8080/play/a05m
#EXTINF:-1,Discovery-italia K2
http://92.104.184.8:8080/play/a05n
#EXTINF:-1,Discovery-italia K2 /Family club
http://92.104.184.8:8080/play/a0gf
#EXTINF:-1,Discovery-italia MOTOR TREND
http://92.104.184.8:8080/play/a0gd
#EXTINF:-1,Discovery-italia FRISBEE
http://92.104.184.8:8080/play/a05l
#EXTINF:-1,Discovery-italia Frisbee / /Family club
http://92.104.184.8:8080/play/a0gg

**Comment by Tundrak** [comment]
> ho preso il link postato da Admiral-Benson (sky tg24 funzionante) e ho cambiato nome e codice dei canali

Idea incredibile, non ci avrei mai pensato

Sento che questi link di Sky mi tireranno un pugno nello stomaco personalmente quando scadranno a fine anno e comincerò a ricevere centinaia di Issue sul fatto che non funzionano, ma la richiesta è grande ed è giusto aggiungerli

**Comment by Tundrak** [comment]
In tempo record, aggiunti i canali Sky nella nuova [Versione Gennaio 2023](https://github.com/Tundrak/IPTV-Italia/releases/tag/v01-2023)!

**Comment by Trifone46** [comment]
Buon giorno volevo segnalare a infinitas79 un link riguardo i canali discovery
WarnerTv
http://188.12.112.110:4000/play/a058 volevo sapere se può utilizzare la stessa modalita come a fatto con gli altri canali discovery

**Comment by Trifone46** [comment]
Buon giorno volevo segnalare a infinitas79 un link riguardo i canali
discovery
WarnerTv
http://188.12.112.110:4000/play/a058 volevo sapere se può utilizzare la
stessa modalita come a fatto con gli altri canali discovery
Il giorno lunedì 23 gennaio 2023, Tundrak ***@***.***> ha
scritto:

**Comment by Infinitas79** [comment]
Ciao. Per ora ho trovato questi (sia per pc sia per ss-iptv) ma la qualità è pessima e non so quanto dureranno
Provateli 

Real Time
https://vsd96.mycdn.me/hls/3050800941680.m3u8/sig/lC-O6k42yw0/expires/1677406848954/srcIp/176.32.22.63/urls/45.136.22.53/clientType/1/srcAg/UNKNOWN_ANDROID/mid/4154672881264/video.m3u8?p

Giallo
https://vsd130.mycdn.me/hls/3041394625136.m3u8/sig/qAO9ww4lBQY/expires/1677407141539/srcIp/176.32.22.63/urls/185.226.53.64/clientType/1/srcAg/UNKNOWN_ANDROID/mid/4144906903152/video.m3u8?p

Nove
https://vsd122.mycdn.me/hls/3054037305968.m3u8/sig/lqZyXiBQJL0/expires/1677434045995/srcIp/176.32.22.63/urls/185.226.53.68/clientType/1/srcAg/UNKNOWN_ANDROID/mid/4158335557232/video.m3u8?p

Dmax
https://vsd149.mycdn.me/hls/3168534071920.m3u8/sig/ltuMGDgK4IU/expires/1677434280724/srcIp/176.32.22.63/urls/45.136.21.63/clientType/1/srcAg/UNKNOWN_ANDROID/mid/4270313250416/video.m3u8?p

**Comment by Trifone46** [comment]
Il link che avevo segnalato Warner TV funziona se viene inserito in una lista e in contemporanea se viene aperto con iptv pro ho quello non pro riguardo i canali che a segnalato confermo che non vanno bene la qualita e molto scarsa

**Comment by Trifone46** [comment]
Erano link che già conoscevo e mi ricordavo che dopo un po non funzionano più e così e stato .

**Comment by Trifone46** [comment]
Nove
https://ok.ru/video/4158335557232

**Comment by Trifone46** [comment]
Buon giorno ho trovato questi link per i canali discovery ma funzionano solo aprendo un qualsiasi browser se qualcuno riesce a farli funzionare con iptv pro puo segnalarlo qui

Nove
https://ok.ru/video/4158335557232

Real-time
https://ok.ru/video/4154672881264

Dmax
https://ok.ru/video/4270313250416

Giallo
https://ok.ru/video/4144906903152

**Comment by Infinitas79** [comment]
È sempre uaznao

Gli m3u8 dei link che hai messo sono questi, ma sicuramente scadono e la qualità è bassa

 Giallo

https://vsd130.mycdn.me/hls/3041394625136.m3u8/sig/rsYc1DdWJ_E/expires/1678372518745/srcIp/176.32.16.103/urls/185.226.53.64/clientType/1/srcAg/UNKNOWN_ANDROID/mid/4144906903152/video.m3u8?p

Nove

https://vsd145.mycdn.me/hls/3054037305968.m3u8/sig/kW9qlnFJ8Vs/expires/1678375116785/srcIp/176.32.16.103/urls/185.226.52.67/clientType/1/srcAg/UNKNOWN_ANDROID/mid/4158335557232/video.m3u8?p

Real Time

https://vsd121.mycdn.me/hls/3050800941680.m3u8/sig/4xyYdhDnZIQ/expires/1678375206610/srcIp/176.32.16.103/urls/185.226.53.56/clientType/1/srcAg/UNKNOWN_ANDROID/mid/4154672881264/video.m3u8?p

Dmax

https://vsd119.mycdn.me/hls/3168534071920.m3u8/sig/ecba4uI3BiI/expires/1678375282721/srcIp/176.32.16.103/urls/45.136.21.63/clientType/1/srcAg/UNKNOWN_ANDROID/mid/4270313250416/video.m3u8?p

**Comment by Trifone46** [comment]
Non ce modo di non farli scadere ?

**Comment by Trifone46** [comment]
Buon giorno per chi cerca canali discovery ho trovato un app gratuita senza pubblicita include ulteriori canali Mediaset Rai Ecc ma se volete il link ve lo posso passare ma non qui .
