### ISSUE TITLE
Salve, Esiste un link per Radio Italia TV in HD ?

### ISSUE THREAD

**Issue by philbel66** [Tundrak/IPTV-Italia#97]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)

**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]
 - Programma utilizzato [es. VLC, Potplayer]
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by Tundrak** [comment]
Ciao!
Purtroppo no, dal sito ufficiale (https://www.radioitalia.it/info/radio-italia-tv) si ottiene il link che è contenuto nella mia lista, con stream in 720x576
Comunque ogni tanto monitoro tutti i canali per vedere se arrivano link migliori, quindi stai sicuro che quando Radio Italia TV sarà disponibile in HD la potrai trovare sulla lista :)

**Comment by philbel66** [comment]
Grazie mille. Io vivo a Parigi quindi lo streaming e per me l'unico mode di
vedere le "RadioTV" italiane (m2o, RTL, 105,...)
