### ISSUE TITLE
Salve, il link per Sky TG24 non funziona. C'e un aggiornamento ? Grazie[Problema]

### ISSUE THREAD

**Issue by philbel66** [Tundrak/IPTV-Italia#98]
**Canale TV / Radio interessato**
Quale canale TV / Radio ha il problema che vuoi descrivere? In quale lista risiede? (È regionale?)

**Descrivi il problema**
Descrivi brevemente e in modo conciso qual è il problema.

**Screenshot**
Se necessario, aggiungi qui screenshot o video che aiutano a capire il problema.

**Informazioni sul dispositivo**
 - Tipo di dispositivo: [es. Computer, Smart TV]
 - Programma utilizzato [es. VLC, Potplayer]
 - Versione lista [es. v04-2021]

**Altre informazioni**
Se devi scrivere altre informazioni riguardo al problema, fallo qui.

**Comment by Tundrak** [comment]
Ciao!
Da me [il link](https://hlslive-web-gcdn-skycdn-it.akamaized.net/TACT/12221/web/master.m3u8?hdnea=st=1639498341~exp=1702463400~acl=/*~hmac=c3c4c2de19ff0df4b4bb20587ce59af5232eadab2995f445b7506525413805dd) funziona.
Puoi darmi qualche informazione in più?

**Comment by philbel66** [comment]
Ho capito perche. Sono in Francia, quindi ho dovuto attivare il mio VPN.
Pero questo flusso e solo un SD e c'est sempre una loop meteo repetitiva di
bassa qualita al posto della publicitta... Non esiste un link piu
"broadcast" ?
Grazie di tutto

**Comment by Tundrak** [comment]
Mi dispiace deluderti anche in questa Issue, ma questo è il flusso che si trova sul sito di Sky, per cui non si può ottenere in modo differente.

**Comment by philbel66** [comment]
Salve, avrai links in mp3 o m3u delle radio italiane ? Sara per inserire
nella playlist del mio firestick (vivo in francia...) ?
Grazie

**Comment by Tundrak** [comment]
Ciao!
La playlist già esiste: il link autoaggiornante è questo https://github.com/Tundrak/IPTV-Italia/raw/main/ipradioita.m3u (lo trovi sempre nel [readme](https://github.com/Tundrak/IPTV-Italia#come-usarla)
Non posso garantire che funzionino senza VPN, però di sicuro le puoi provare

**Comment by philbel66** [comment]
Infatti, non riuscivo con VLC pero sulla mia Firestick funziona, anche
senza VPN... Invece la qualité non e ottima. I flussi DAB sono migliori.
Non esiste la versione RTL 102.5 "normale" in DAB ?
Ti ringrazio
Filippo

**Comment by philbel66** [comment]
E se ti posso fare una domanda... Mi potresti trovare il flusso di questa
webradio : https://cafedelmar.com/radio  ?

**Comment by Tundrak** [comment]
Se intendi il flusso offerto in radio, non credo ci sia modo di ottenere proprio quello: l'unico che viene offerto sul web è quello che ho nella lista a 128kbps (fino a poco fa ce n'era un altro in mp3 ma è stato chiuso)

Il link della webradio è https://streams.radio.co/se1a320b47/listen

**Comment by philbel66** [comment]
Salve, mi potreste trovare il stream di questa radio ? Stream Detector non
mi risulta niente...
https://www.radiogamma.it/ascolta.php

Grazie mille

**Comment by philbel66** [comment]
Hi,
Is it possible for you to find the URL of this TV ?

https://iptv-org.github.io/channels/fr/Europe1TV#HD

Regards
